#This is AntDen Dockerfile#version 1.0
#Author: lijinfeng2011@gmail.com
#Base image 基础镜像

FROM openc3/job-base-nginx:latest
MAINTAINER lijinfeng2011

RUN yum -y install perl-DBD-MySQL.x86_64 mysql-devel
RUN /data/Software/mydan/perl/bin/cpan install Dancer
RUN /data/Software/mydan/perl/bin/cpan install Dancer::Plugin::Database
RUN /data/Software/mydan/perl/bin/cpan install Logger::Syslog

RUN /data/Software/mydan/perl/bin/cpan install DBD::mysql

RUN /data/Software/mydan/perl/bin/cpan install Twiggy

RUN /data/Software/mydan/perl/bin/cpan install Dancer2

RUN /data/Software/mydan/perl/bin/cpan install Dancer2::Plugin::WebSocket

#RUN /data/Software/mydan/perl/bin/cpan force install Mail::Sender
#sed -i 's/warnings::warnif(/#warnings::warnif(/' /data/Software/mydan/perl/lib/site_perl/5.24.0/Mail/Sender.pm

