#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_parse_resource_timer_task import OperateTimeTaskFile


def main():
    data_list = OperateTimeTaskFile().get_all()

    for item in data_list:
        print(json.dumps(item, default=str))


if __name__ == '__main__':
    main()
