#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use MYDB;
use FindBin qw( $RealBin );
use MYDan::Util::OptConf;
use keepalive;

=head1 SYNOPSIS

 $0 name

=cut

keepalive->new( MYDB->new( "$RealBin/../conf/conn" ) )->role( $ARGV[0] );
