#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );
use Data::Dumper;
use Code;

use MYDan::Util::OptConf;

=head1 SYNOPSIS

 $0 [--projectid projectid] [--calljob foo] [--version release-001]

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( projectid=i calljob=s version=s ) )->dump();

$option->assert( qw( projectid calljob version ) );

Code->new( 'build.plugin/send.plugin/calljob' )->run( %o );
