#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use Data::Dumper;
use Code;

=head1 SYNOPSIS

 $0 

=cut

my @node = Code->new( 'dockerimage' )->run( );
print Dumper \@node;
