#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

my @node = <STDIN>;
chomp @node;

my %res;
for my $x ( @node )
{
    my ( $host, $stat ) = split /\s+/, $x;
    $res{$host} = $stat ? 1 : $res{$host} ? 1 : 0;
}

map{ printf "$_ %s\n", $res{$_} ? 1 : 0 }keys %res;

my @host = grep{ ! $res{$_} }keys %res;

## Start

my @err = `c3mc-mon-agent-install-errnode`;
chomp @err;
my %err = map{$_ => 1}@err;

map{ printf "%s %s\n", $_, $err{$_} ? 0 : 1 }@host;
map{ print "$_ 0\n" unless defined $res{$_}}keys %err;
