#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

my @node = <STDIN>;
chomp @node;

my %res;
for my $x ( @node )
{
    my ( $host, $stat ) = split /\s+/, $x;
    $res{$host} = $stat ? 1 : $res{$host} ? 1 : 0;
}

map{ printf "node_alive{instance=\"$_\"} %s\n", $res{$_} ? 1 : 0 }keys %res;
printf "node_alive_monitor_time %s\n", int time;
