use ci;
insert into `openc3_ci_project` select `id`, `status`, `autofindtags`, `callonlineenv`, `calltestenv`, `findtags_at_once`, `autobuild`, `name`, `excuteflow`, `calljobx`, `calljob`, `webhook`, `webhook_password`, `webhook_release`, `rely`, `buildimage`, `buildscripts`, `follow_up`, `follow_up_ticketid`, `callback`, `groupid`, `tag_regex`, `addr`, `ticketid`, `notify`, `slave`, `last_findtags`, `last_findtags_success`, `edit_user`, `edit_time`  from `project`;
insert into `openc3_ci_rely` select `id`, `projectid`, `path`, `addr`, `ticketid`, `tags`, `edit_user`, `edit_time`  from `rely`;
insert into `openc3_ci_repository` select `id`, `addr`, `type`, `username`, `password` from `repository`;
insert into `openc3_ci_ticket` select `id`, `name`, `type`, `share`, `ticket`, `describe`, `edit_user`, `create_user`, `edit_time`, `create_time` from `ticket`;
insert into `openc3_ci_images` select `id`, `name`, `share`, `describe`, `edit_user`, `create_user`, `edit_time`, `create_time` from `images`;
insert into `openc3_ci_version` select `id`, `projectid`, `uuid`, `name`, `user`, `slave`, `status`, `starttimems`, `finishtimems`, `starttime`, `finishtime`, `calltype`, `pid`, `runtime`, `tagger`, `taginfo`, `reason`, `create_time`  from `version`;
insert into `openc3_ci_keepalive` select `id`, `slave`, `time` from `keepalive`; 
insert into `openc3_ci_favorites` select `id`, `ciid`, `name`, `user` from `favorites`;

use jobs;
insert into `openc3_job_project` select `id`, `status`, `edit_user`, `edit_time`  from `project`;
insert into `openc3_job_approval` select `id`, `taskuuid`, `uuid`, `user`, `name`, `submitter`, `oauuid`, `notifystatus`, `cont`, `opinion`, `remarks`, `create_time`, `finishtime` from `approval`;
insert into `openc3_job_plugin_approval` select `id`, `jobuuid`, `uuid`, `name`, `cont`, `approver`, `deployenv`, `action`, `batches`, `everyone`, `timeout`, `pause`, `create_time` from `plugin_approval`; 
insert into `openc3_job_plugin_cmd` select `id`, `jobuuid`, `uuid`, `name`, `user`, `node_type`, `node_cont`, `scripts_type`, `scripts_cont`, `scripts_argv`, `timeout`, `pause`, `deployenv`, `action`, `batches`, `create_time` from `plugin_cmd`; 
insert into `openc3_job_scripts` select `id`, `projectid`, `name`, `type`, `cont`, `create_user`, `create_time`, `edit_user`, `edit_time`, `status` from `scripts`;
insert into `openc3_job_plugin_scp` select `id`, `jobuuid`, `uuid`, `name`, `user`, `src`, `src_type`, `sp`, `dst`, `dst_type`, `dp`, `chown`, `chmod`, `timeout`, `scp_delete`, `pause`, `deployenv`, `action`, `batches`, `create_time` from `plugin_scp`; 
insert into `openc3_job_jobs` select `id`, `projectid`, `uuid`, `name`, `uuids`, `status`, `mon_ids`, `mon_status`, `create_user`, `create_time`, `edit_user`, `edit_time` from `jobs`;
insert into `openc3_job_crontab` select `id`, `name`, `jobuuid`, `cron`, `mutex`, `create_user`, `create_time`, `edit_user`, `edit_time`, `status` from `crontab`;
insert into `openc3_job_crontablock` select `id`, `crontabid`, `timeid`, `create_time` from `crontablock`;
insert into `openc3_job_keepalive` select `id`, `slave`, `time`  from `keepalive`;
insert into `openc3_job_userlist` select `id`, `projectid`, `username`, `create_user`, `create_time`, `edit_user`, `edit_time`, `status` from `userlist`;
insert into `openc3_job_nodegroup` select `id`, `projectid`, `name`, `plugin`, `params`, `create_user`, `create_time`, `edit_user`, `edit_time`, `status` from `nodegroup`;
insert into `openc3_job_task` select `id`, `projectid`, `uuid`, `name`, `user`, `slave`, `status`, `starttimems`, `finishtimems`, `starttime`, `finishtime`, `calltype`, `jobtype`, `jobuuid`, `pid`, `runtime`, `mutex`, `notify`, `variable`, `reason` from `task`;
insert into `openc3_job_subtask` select `id`, `parent_uuid`, `subtask_type`, `uuid`, `nodecount`, `starttime`, `finishtime`, `runtime`, `status`, `pause` from `subtask`;
insert into `openc3_job_pause` select `id`, `taskuuid`, `pluginuuid`, `plugin_type`, `unlock_user`, `unlock_time`, `create_time` from `pause`; 
insert into `openc3_job_fileserver` select `id`, `projectid`, `name`, `size`, `md5`, `create_user`, `create_time`, `edit_user`, `edit_time`, `status` from `fileserver`;
insert into `openc3_job_variable` select `id`, `jobuuid`, `name`, `value`, `describe`, `create_user`, `create_time` from `variable`;
insert into `openc3_job_notify` select `id`, `projectid`, `user`, `status`, `create_user`, `create_time`, `edit_user`, `edit_time` from `notify`; 
insert into `openc3_job_environment` select `id`, `key`, `value`, `create_user`, `create_time` from `environment`;
insert into `openc3_job_cmdlog` select `id`, `projectid`, `user`, `node`, `usr`, `cmd`, `time`  from `cmdlog`;
insert into `openc3_job_nodelist` select `id`, `projectid`, `name`, `inip`, `exip`, `create_user`, `create_time`, `edit_user`, `edit_time`, `status` from `nodelist`;
insert into `openc3_job_token` select `id`, `projectid`, `token`, `describe`, `isjob`, `jobname`, `create_user`, `create_time`, `edit_user`, `edit_time`, `status`  from `token`;
insert into `openc3_job_vv` select `id`, `projectid`, `node`, `name`, `value`, `update_time` from `vv`; 
insert into `openc3_job_smallapplication` select `id`, `jobid`, `type`, `title`, `describe`, `parameter`, `edit_user`, `create_user`, `edit_time`, `create_time` from `smallapplication`;

use jobx;
insert into `openc3_jobx_group` select `id`, `projectid`, `name`, `note`, `group_type`, `group_uuid`, `edit_time` from `group`;
insert into `openc3_jobx_group_type_list` select `id`, `uuid`, `node`, `create_time` from `group_type_list`; 
insert into `openc3_jobx_group_type_percent` select `id`, `uuid`, `percent`, `create_time` from `group_type_percent`; 
insert into `openc3_jobx_task` select `id`, `projectid`, `uuid`, `name`, `group`, `user`, `slave`, `status`, `starttimems`, `finishtimems`, `starttime`, `finishtime`, `calltype`, `pid`, `runtime`, `variable`, `reason` from `task`; 
insert into `openc3_jobx_subtask` select `id`, `parent_uuid`, `uuid`, `nodelist`, `nodecount`, `starttime`, `finishtime`, `runtime`, `status`, `confirm`  from `subtask`; 
insert into `openc3_jobx_keepalive` select `id`, `slave`, `time` from `keepalive`;
insert into `openc3_jobx_monitor` select `id`, `time`, `time_s`, `stat`, `host`, `type`, `key`, `val` from `monitor`;
insert into `openc3_jobx_flowline_version` select `id`, `flowlineid`, `jobxuuid`, `version`, `create_time` from `flowline_version`;

use agent;
insert into `openc3_agent_region` select `id`, `projectid`, `name`, `create_time` from `region`;
insert into `openc3_agent_project_region_relation` select `id`, `projectid`, `regionid`, `create_time` from `project_region_relation`; 
insert into `openc3_agent_proxy` select `id`, `regionid`, `projectid`, `ip`, `status`, `fail`, `reason`, `version`, `edit_time` from `proxy`;
insert into `openc3_agent_agent` select `id`, `relationid`, `projectid`, `ip`, `status`, `fail`, `reason`, `version`, `edit_time` from `agent`;
insert into `openc3_agent_install` select `id`, `uuid`, `projectid`, `regionid`, `type`, `ip`, `user`, `slave`, `pid`, `status`, `success`, `fail`, `username`, `password`, `starttimems`, `finishtimems`, `starttime`, `finishtime`, `runtime` from `install`; 
insert into `openc3_agent_install_detail` select `id`, `uuid`, `type`, `ip`, `starttime`, `finishtime`, `status`, `reason` from `install_detail`;
insert into `openc3_agent_keepalive` select `id`, `slave`, `time` from `keepalive`;
insert into `openc3_agent_check` select `id`, `projectid`, `user`, `status`, `slave`, `last_check`, `last_success`, `create_time` from `check`;
insert into `openc3_agent_inherit` select `id`, `projectid`, `inheritid`, `create_time` from `inherit`;
insert into `openc3_agent_monitor` select `id`, `projectid`, `ip`, `status`, `fail`, `reason`, `version`, `edit_time` from `monitor`;

use connector;
insert into `openc3_connector_group` select `id`, `projectid`, `name`, `note`, `group_type`, `group_uuid`, `edit_time` from `group`;
insert into `openc3_connector_group_type_list` select `id`, `uuid`, `node`, `create_time` from `group_type_list`;
insert into `openc3_connector_group_type_percent` select `id`, `uuid`, `percent`, `create_time` from `group_type_percent`; 
insert into `openc3_connector_task` select `id`, `projectid`, `uuid`, `name`, `group`, `user`, `slave`, `status`, `starttimems`, `finishtimems`, `starttime`, `finishtime`, `calltype`, `pid`, `runtime`, `variable`, `reason` from `task`;
insert into `openc3_connector_subtask` select `id`, `parent_uuid`, `uuid`, `nodelist`, `nodecount`, `starttime`, `finishtime`, `runtime`, `status`, `confirm` from `subtask`;
insert into `openc3_connector_keepalive` select `id`, `slave`, `time` from `keepalive`; 
insert into `openc3_connector_log` select `id`, `projectid`, `user`, `info`, `create_time`  from `log`; 
insert into `openc3_connector_userinfo` select `id`, `name`, `pass`, `sid`, `expire` from `userinfo`; 
insert into `openc3_connector_userauth` select `id`, `name`, `level` from `userauth`;
insert into `openc3_connector_usermesg` select `id`, `user`, `time`, `mesg` from `usermesg`; 
insert into `openc3_connector_usermail` select `id`, `user`, `time`, `title`, `content` from `usermail`;
insert into `openc3_connector_tree` select `id`, `name`, `len`, `update_time` from `tree`; 
insert into `openc3_connector_nodelist` select `id`, `projectid`, `name`, `inip`, `exip`, `type`, `create_user`, `create_time`, `edit_user`, `edit_time`, `status`  from `nodelist`;
insert into `openc3_connector_auditlog` select `id`, `time`, `user`, `title`, `content` from `auditlog;
