#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


def display_instance_list(account, region_id):
    """
        展示实例列表
    """
    output = subprocess.getoutput("c3mc-device-data-get curr compute aws-ec2 \
        $(c3mc-cloud-get-real-field compute aws-ec2 account RegionId _name_ InstanceId PrivateIpAddress PublicIpAddress)")

    result = []
    data_list = output.split("\n")
    for line in data_list:
        parts = line.split("\t")
        if parts[0] != account or parts[1] != region_id:
            continue
        result.append({
            "name": parts[2],
            "instance_id": parts[3],
            "private_ip": parts[4],
            "public_ip": parts[5]
        })
        
    return result


def main(params):
    account = params["account"]
    region = params["region"]
    data_list = display_instance_list(account, region)
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]))
