#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use OPENC3::PP::Server;

=head1 SYNOPSIS

 $0

=cut

OPENC3::PP::Server->new(
    name => 'agent_server_carry',
    interval => 60,
    timeout => 12,
)->run(

    "cat $RealBin/../conf/promesd.temp | c3_agent_pp_carry --output $RealBin/../conf/openc3_carry.yml"
);
