#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use Code;

=head1 SYNOPSIS

 $0

=cut

$0 = 'agent_server_carry';

$ENV{PATH} = "$ENV{PATH}:/data/Software/mydan/AGENT/pp:/data/Software/mydan/Connector/pp";

warn ">> start\n";

while(1)
{
    die if system "cat $RealBin/../conf/promesd.temp | c3_agent_pp_carry --output $RealBin/../conf/openc3_carry.yml";

    sleep 60;
}
