#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use Code;

=head1 SYNOPSIS

 $0

=cut

my $db = MYDB->new( "$RealBin/../conf/conn" );

$0 = 'agent_server_inherit';
Code->new( 'server/inherit' )->run( db => $db );
