#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use Code;

=head1 SYNOPSIS

 $0

=cut

$0 = 'agent_server_promesd';

my $exip = `cat /etc/job.exip`;
chomp $exip;
Code->new( 'server/promesd' )->run( serveraddr => "$exip:65112" );
