#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use OPENC3::PP::Server;

=head1 SYNOPSIS

 $0

=cut

my $nodetemp = "$RealBin/../conf/promesd.temp";
my $tempfile = "$nodetemp.$$";

OPENC3::PP::Server->new(
    name => 'agent_server_promesd',
    interval => 1800,
    timeout => 3600,
)->run(
   "c3_connector_pp_treemap | awk -F';' '{print \$1}'| c3_job_pp_nodeinfo -c projectid,inip | tee $tempfile | c3_agent_pp_sdformat --output $RealBin/../../prometheus/config/openc3_node_sd.yml",
    "mv $tempfile $nodetemp",
);
