#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use Code;

=head1 SYNOPSIS

 $0

=cut

$0 = 'agent_server_rule';

$ENV{PATH} = "$ENV{PATH}:/data/Software/mydan/AGENT/pp";

warn ">> start\n";

while(1)
{
    die if system "c3_agent_pp_rule --output $RealBin/../../prometheus/config/openc3_rule.yml";

    warn "reload rule fail: $!" if system "curl -XPOST http://OPENC3_PROMETHEUS_IP:9090/-/reload 2>/dev/null";

    sleep 6;
}
