#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use OPENC3::PP::Server;

=head1 SYNOPSIS

 $0

=cut

OPENC3::PP::Server->new(
    name => 'agent_server_rule',
    interval => 60,
    timeout => 12,
)->run(
    "c3_agent_pp_rule --output $RealBin/../../prometheus/config/openc3_rule.yml",
    "curl -XPOST http://OPENC3_PROMETHEUS_IP:9090/-/reload 2>/dev/null",
);
