#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json

import boto3


def get_ec2_by_id(access_id, access_key, region, instance_id):
    """
        输出aws ec2的详情(json格式)
    """
    client = boto3.client(
        "ec2",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region,
    )
    response = client.describe_instances(
        InstanceIds=[instance_id])
    if len(response["Reservations"]) == 0 or len(response["Reservations"][0]["Instances"]) == 0:
        raise Exception("根据instance_id {} 未找到ec2".format(instance_id))
    return response["Reservations"][0]["Instances"][0]


def main(access_id, access_key, region, instance_id):
    data = get_ec2_by_id(access_id, access_key, region, instance_id)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
