#!/bin/bash

cd /data/Software/mydan/Connector/local && /data/Software/mydan/AGENT/device/bin/downloadx > devicesynctime.txt.temp && mv devicesynctime.txt.temp devicesynctime.txt

SAVETREE=$(c3mc-sys-ctl sys.device.sync.tree)
if [ "X$SAVETREE" == "X1" ];then
    c3mc-device-save-tree
fi

BINDTREE=$(c3mc-sys-ctl sys.device.sync.bind)
if [ "X$BINDTREE" == "X1" ];then
    c3mc-device-dump-bind | c3mc-base-savebind 
fi

PRICEVALUE=$(c3mc-sys-ctl sys.device.sync.price)
if [ "X$PRICEVALUE" == "X1" ];then
    c3mc-price-dump | c3mc-price-load
fi

/data/Software/mydan/AGENT/device/bin/ingestion >/dev/null

cd /data/Software/mydan/Connector/local && c3mc-device-ingestion-jumpserver               > jumpserver.txt.temp && mv jumpserver.txt.temp jumpserver.txt

cd /data/Software/mydan/Connector/local && c3mc-device-dump-treeinfo                      > devicetreeinfo.txt.temp && mv devicetreeinfo.txt.temp devicetreeinfo.txt
cd /data/Software/mydan/Connector/local && c3mc-device-metrics                            > devicesyncinfo.txt.temp && mv devicesyncinfo.txt.temp devicesyncinfo.txt
cd /data/Software/mydan/Connector/local && /data/Software/mydan/AGENT/device/bin/metrics  > deviceextmetrics.txt.temp && mv deviceextmetrics.txt.temp deviceextmetrics.txt

cd /data/open-c3-data/device/curr && /data/Software/mydan/AGENT/device/bin/instancealias  > instancealias.temp && mv instancealias.temp instancealias.txt
