#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import re


def get_account_by_uuid(account_uuid):
    """
        根据accountuuid查询账号信息
    """
    filename = re.sub(r"\.\d+$", "", account_uuid)
    account_file = f"/data/Software/mydan/AGENT/device/conf/account/{filename}"

    line_index = int(account_uuid.split(".")[-1])

    f = open(account_file)
    return f.readlines()[line_index - 1]


def main(account_uuid):
    account_info = get_account_by_uuid(account_uuid)
    print(account_info)


if __name__ == '__main__':
    main(sys.argv[1])
