#!/bin/bash

if [ ! -f /data/open-c3-data/c3mc-device-account-proxy.yml ]; then
    exit
fi

c3mc-device-account-proxy > /data/open-c3-data/proxy.private.yaml.temp.$$ && mv /data/open-c3-data/proxy.private.yaml.temp.$$ /data/open-c3-data/proxy.private.yaml
