#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

=head1 SYNOPSIS

 $0 ctrl timemachine

=cut

my $ctrl = shift @ARGV;

die "ctrl err" unless $ctrl && ( $ctrl eq 'get' || $ctrl eq 'set' );

my $timemachine = @ARGV ? $ARGV[0] : 'curr';

my $path = sprintf "/data/open-c3-data/device/%s/cache", $timemachine eq 'curr' ? 'curr' : "timemachine/$timemachine";
my $file = "$path/c3mc-device-bind-info.txt";

if( $ctrl eq 'set' )
{
    system "mkdir -p $path" unless -d $path;
    exec "c3mc-device-bind-info $timemachine > $file.$$.temp && mv $file.$$.temp $file";
}
else
{
    -f $file ? exec( "cat $file" ) : exec( "c3mc-device-bind-info $timemachine");
}
