#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys


def get_account_by_uuid(account_uuid):
    """
        根据accountuuid查询账号信息
    """
    parts = account_uuid.split(".")
    account_file = "/data/Software/mydan/AGENT/device/conf/account/{}".format(parts[0])

    f = open(account_file)
    return f.readlines()[int(parts[1]) - 1]


def main(account_uuid):
    account_info = get_account_by_uuid(account_uuid)
    print(account_info)


if __name__ == '__main__':
    main(sys.argv[1])
