#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

=head1 SYNOPSIS

 $0

=cut

my    $cluster = `c3mc-sys-ctl agent.authrotate.cluster`;
my    $version = `c3mc-sys-ctl agent.authrotate.version`;
chomp $cluster;
chomp $version;

die "cluster format error" unless $cluster && $cluster =~ /^[a-zA-Z\d]+[a-zA-Z\d_\-\.]*[a-zA-Z\d]+$/;
die "version format error" unless $version && $version =~ /^\d+$/;

die "not allow: test" if $cluster eq 'test';

my $name  = "${cluster}_${version}";

my    @x = `c3mc-agent-authrotate-data`;
chomp @x;
my %data;

for( @x )
{
    next unless $_ =~ /^(\d+\.\d+\.\d+\.\d+):\s+([a-zA-Z\d]+[a-zA-Z\d_\-\.]*[a-zA-Z\d]+)$/;
    $data{ $1 } { $2 } = 1;
}

for my $ip ( keys %data )
{
    my %tmp;
    for my $x (keys %{ $data{ $ip } } )
    {
        next unless $x eq 'c3_test' || $x =~/^c3_test_(\d+)$/;
        $tmp{ $x } = 1;
    }

    next unless keys %tmp;

    my $del = join ' ', map{ "'$_.pub'" } keys %tmp;
    system "/data/Software/mydan/dan/tools/rcall -r '$ip' exec \"cd /opt/mydan/etc/agent/auth && rm $del\"";
}
