#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;
use MYDan::Util::OptConf;

=head1 SYNOPSIS

 $0 bpmuuid action

=cut

my $option = MYDan::Util::OptConf->load();
$option->assert() unless @ARGV;

die "nonode" unless $ENV{NODE};

sub success
{
    map{ print "$_:ok\n"; } split /,/, $ENV{NODE};
    exit;
}

my ( $bpmuuid, $action ) = @ARGV;

die "bpmuuid err" unless $bpmuuid && $bpmuuid =~ /^BPM\d+$/;
die "action err"  unless $action  && $action  =~ /^[a-zA-Z0-9][a-zA-Z0-9\-_\.]+$/;

die "Error" if system "/data/Software/mydan/JOB/bpm/bin/bpmtask '$bpmuuid' '$action'";
success();
