#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import sys

import boto3


class Rds:
    def __init__(self, access_id, access_key):
        self.access_id = access_id
        self.access_key = access_key
        self.client = self.create_client()

    def create_client(self):
        client = boto3.client(
            "pricing",
            aws_access_key_id=self.access_id,
            aws_secret_access_key=self.access_key,
            region_name="us-east-1",
        )
        return client

    def query_instance_type_attributes(self, region, instance_type):
        FLT = '[{{"Field": "instanceType", "Value": "{t}", "Type": "TERM_MATCH"}},' \
            '{{"Field": "deploymentOption", "Value": "Single-AZ", "Type": "TERM_MATCH"}},' \
            '{{"Field": "regionCode", "Value": "{r}", "Type": "TERM_MATCH"}}]'
        f = FLT.format(r=region, t=instance_type)
        data = self.client.get_products(
            ServiceCode='AmazonRDS', Filters=json.loads(f))
        res = json.loads(data['PriceList'][0])['product']['attributes']
        res["memory"] = res["memory"][:-len(" GiB")]
        return res


def main(access_id, access_key, region, instance_type):
    info = Rds(access_id, access_key).query_instance_type_attributes(
        region, instance_type)
    print(json.dumps(info, default=str))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
