#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib
use strict;
use warnings;

$|++;

use MYDB;
use MYDan::Util::OptConf;
use LWP::UserAgent;
use JSON;
use Configini;

=head1 SYNOPSIS

 $0 --user user1

=cut

my $option = MYDan::Util::OptConf->load();
my %o      = $option->get( qw(    user=s ) )->dump();
             $option->assert( qw( user   ) );

die "user format error" unless $o{user} =~ /^[a-zA-Z0-9][a-zA-Z0-9\.\-_\@]+$/;

my $db = MYDB->new( "/data/Software/mydan/Connector/conf/conn", delayedconnection => 1 );

my $x = $db->query( sprintf "select leader1,leader2 from openc3_connector_userleader where user='$o{user}'" );
if( @$x )
{
    print $x->[0][0], "\n";
    print $x->[0][1], "\n";
    exit;
}

my ( $userleader, %env );
$userleader = Configini::get( 'userleader'    );
%env        = Configini::env( 'userleaderenv' );

my @leader;

if( $userleader ){

    my $ua = LWP::UserAgent->new;
    $ua->timeout( 15 );
    $ua->default_header( %env ) if %env;

    my ( $res, $err );
    for my $i ( reverse 1 .. 3 )
    {
        $res = $ua->get( $userleader . $o{user});

        $err = sprintf "get userleader fail: $userleader: %s", YAML::XS::Dump $res;
        $err =~ s/appkey:\s+['"]?[a-zA-Z0-9]{32}['"]?\b/appkey: ******/g;

        last if $res->is_success;
        if( $i > 1 )
        {
            warn sprintf( "userleader code %s", $res->code );
            sleep 3;
        }
    }

    die sprintf( "$err: code %s", $res->code ) unless $res->is_success;

    my $v = eval{JSON::decode_json $res->decoded_content};
    die "$err: data no JSON: $@" if $@;
    die $err unless $v->{stat};
    die "$err: data no ARRAY: $@" unless $v->{data} && ref $v->{data} eq 'ARRAY';

    @leader = @{$v->{data}};
}

map{ print "$_\n" }@leader;
