#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess
import os
import time

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.cdb.v20170320 import cdb_client, models

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_qcloud_cdb import QcloudCdb


password_dir = "/data/open-c3-data/device/curr/auth"

def record_cdb_password(file_name, file_content):
    if not os.path.exists(password_dir):
        os.makedirs(password_dir)

    file_path = os.path.join(password_dir, file_name)
    with open(file_path, "w") as file:
        file.write(file_content)


class Mysql:
    def __init__(self, access_id, access_key, region, params):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.params = params
        self.client = self.create_client()
        self.lib_qcloud_cdb = QcloudCdb(self.access_id, self.access_key, self.region)

    def create_client(self):
        cred = credential.Credential(
            self.access_id, self.access_key)
        httpProfile = HttpProfile()
        httpProfile.endpoint = "cdb.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        return cdb_client.CdbClient(cred, self.region, clientProfile)

    def get_bool_value(self, text_bool):
        return text_bool == "是"

    def get_request(self):
        req = models.CreateDBInstanceHourRequest()
        if self.params["charge_type"] == "包年包月":
            req = models.CreateDBInstanceRequest()

        api_params = {
            # MySQL 版本
            "EngineVersion": self.params["engine_version"],
            # 私有网络 ID
            "UniqVpcId": self.params["vpc_id"],
            # 私有网络下的子网 ID
            "UniqSubnetId": self.params["subnet_id"],
            # 项目 ID
            "ProjectId": int(self.params["project_id"]),
            # 实例数量
            "GoodsNum": int(self.params["count"]),
            # 内存
            "Memory": int(self.params["instance_config"]),
            # 硬盘
            "Volume": int(self.params["disk_size"]),
            # 可用区
            "Zone": self.params["zone"],
            # 实例类型
            # "InstanceRole": self.params["instance_role"],
            # 购买灾备实例和只读实例会导致参数过于复杂，目前只支持创建主实例，后需有需求在考虑增加只读或者灾备实例
            "InstanceRole": "master",
            # 自定义端口
            "Port": int(self.params["port"]),
            # 设置 root 帐号密码
            "Password": self.params["password"],
            # "ParamList": [
            #     {
            #         # 字符集
            #         "Name": "character_set_server",
            #         "Value": self.params["charset_type"]
            #     },
            #     {
            #         # 排序规则
            #         "Name": "collation_server",
            #         "Value": self.params["charset_sort_type"]
            #     },
            #     {
            #         # 表名大小写敏感
            #         "Name": "lower_case_table_names",
            #         "Value": self.params["lower_case_table_names"]
            #     }
            # ],
            # 告警策略名数组
            "AlarmPolicyIdList": self.params["alarm_policies"].split(","),
            # 安全组
            "SecurityGroup": self.params["security_group_ids"].split(","),
            # 实例引擎类型
            "EngineType": self.params["engine_type"],
            # 用于保证请求幂等性的字符串
            "ClientToken": self.params["bpm_uuid"],
            # 参数模板
            "ParamTemplateId": int(self.params["param_template_id"]),
        }


        if "tag" in self.params:
            tag_list = json.loads(self.params["tag"])
            if len(tag_list) > 0:
                api_params["ResourceTags"] =  [
                    {"TagKey": tag['key'], "TagValue": [tag['value']]} for tag in tag_list
                ]

        # 实例节点数
        api_params["InstanceNodes"] = int(self.params["instance_nodes"])
        # 设置备库
        if api_params["InstanceNodes"] == 2:
            api_params["SlaveZone"] = self.params["backup_zone1"]
        if api_params["InstanceNodes"] == 3:
            api_params["SlaveZone"] = self.params["backup_zone1"]
            api_params["BackupZone"] = self.params["backup_zone2"]
        
        instance_name_prefix = self.params["instance_name"]
        if api_params["InstanceNodes"] > 1:
            # 数据复制方式
            api_params["ProtectMode"] = int(self.params["protect_mode"])
            # 如果多实例时并且可用区不一致，需要加上多可用区参数
            s = {
                self.params["zone"],
                self.params["backup_zone1"],
                self.params["backup_zone2"],
            }
            if len(s) > 1:
                api_params["DeployMode"] = 1

            # 只创建一台实例时不会增加数字后缀
            if instance_name_prefix[-1] not in ["_", "-"]:
                instance_name_prefix += "_"
        
        # 实例名称前缀
        api_params["InstanceName"] = instance_name_prefix

        if self.params["charge_type"] == "包年包月":
            # 购买时长
            api_params["Period"] = int(self.params["instance_charge_count"])
            # 自动续费标记
            api_params["AutoRenewFlag"] = int(self.params["auto_renew_flag"])

        req.from_json_string(json.dumps(api_params))
        return req
    

    def wait_for_cdb_running(self, instance_id, timeout=1800):
        """
        等待cdb变为运行状态

        等待变为运行状态时间较长, 超时时间设置为半小时
        """
        start_time = time.time()
        while True:
            cdb_info = self.lib_qcloud_cdb.DescribeDBInstances(instance_id)
            if cdb_info["Status"] == 1:
                return True
            elif time.time() - start_time > timeout:
                return False
            else:
                time.sleep(5)


    def open_wan_service(self, instance_id):
        if not self.wait_for_cdb_running(instance_id):
            raise RuntimeError(f"开通外网访问失败. instance_id: {instance_id}, 原因: 等待实例变为运行状态超时, 超时时间30分钟")

        cdb_info = self.lib_qcloud_cdb.DescribeDBInstances(instance_id)
        # 假如工单中途出错，可能部分实例已经成功开通了外网访问
        if cdb_info["WanStatus"] == 1:
            return 
        res = self.lib_qcloud_cdb.OpenWanService(instance_id)
        print(f"开通外网访问成功. instance_id: {instance_id}, 结果: {json.dumps(res, default=str)}")


    def create(self):
        req = self.get_request()
        print(f"创建cdb, 请求参数为: {req}")

        if subprocess.getoutput("c3mc-sys-ctl sys.bpm.fake.run") == "1":
            # bpm虚假运行
            print("创建cdb, 响应为: xxxxxx")
            print("LOG. instance_id:xxxxxx")
            print("VAR. instance_id:xxxxxx")
            print(f'VAR. extinstance_id:{self.params["account"]}.{self.params["region"]}.xxxxx')
            return 

        try:
            if self.params["charge_type"] == "按量计费":
                # 创建按量计费实例
                resp = self.client.CreateDBInstanceHour(req)
            else:
                # 创建包年包月实例
                resp = self.client.CreateDBInstance(req)

            print(f"创建cdb, 响应为: {resp.to_json_string()}")

            for instance_id in resp.InstanceIds:
                print(f"LOG. instance_id:{instance_id}")
                print(f"VAR. instance_id:{instance_id}")
                print(f'VAR. extinstance_id:{self.params["account"]}.{self.params["region"]}.{instance_id}')
                record_cdb_password(f'{instance_id}:{self.params["port"]}', self.params["password"])

                if self.params["if_need_open_wan"] == "是":
                    self.open_wan_service(instance_id)

        except Exception as e:
            print(f"创建腾讯云cdb出错, err: {e}", file=sys.stderr)
            exit(1)


def main(params):
    print(f"params = {json.dumps(params)}")

    account = params["account"]
    region = params["region"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info qcloud {account}")
    )
    Mysql(key_info["access_id"], key_info["access_key"], region, params).create()


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
