#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import re


def display_field_values(data_list, fields_desc):
    """
        展示字段值
    """
    result = []

    bracket_content = re.findall(r'\{(.*?)\}', fields_desc)
    if len(bracket_content) > 0:
        # 模板字符串的配置方式
        for data in data_list:
            value_list = {}
            for field_name in bracket_content:
                value_list[field_name] = data[field_name]
            result.append(fields_desc.format(**value_list))
    else:
        # 兼容旧的配置方式
        fields_list = fields_desc.split(",")
        for data in data_list:
            item_list = []
            for field in fields_list:
                if isinstance(data[field], list):
                    item_list.append("_".join(map(str, data[field])))
                else:
                    item_list.append(str(data[field]))
            if len(item_list) == 0:
                continue
            if len(item_list) == 1:
                result.append(item_list[0])
            else:
                result.append("{};({})".format(item_list[0], "-".join(item_list[1:])))
    return result


def main(data_list, target_fields):
    """
    target_fields 是要保留的字段, 多个字段用英文逗号分隔
    """
    data_list = display_field_values(data_list, target_fields)
    for item in data_list:
        print(item)


if __name__ == '__main__':
    data_list = []
    for line in sys.stdin:
        data_list.append(json.loads(line))

    main(data_list, sys.argv[1])
