#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json


def display_field_values(data_list, target_fields):
    """
        展示字段值
    """
    result = []
    fields_list = target_fields.split(",")
    for data in data_list:
        item_list = []
        for field in fields_list:
            if isinstance(data[field], list):
                item_list.append("_".join(map(str, data[field])))
            else:
                item_list.append(str(data[field]))
        if len(item_list) == 0:
            continue
        if len(item_list) == 1:
            result.append(item_list[0])
        else:
            result.append("{};({})".format(item_list[0], "-".join(item_list[1:])))
    return result


def main(data_list, target_fields):
    """
    target_fields 是要保留的字段, 多个字段用英文逗号分隔
    """
    data_list = display_field_values(data_list, target_fields)
    for item in data_list:
        print(item)


if __name__ == '__main__':
    data_list = []
    for line in sys.stdin:
        data_list.append(json.loads(line))

    main(data_list, sys.argv[1])
