#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json


def describe_account_info(cloud, account):
    """
        查询指定账号的信息
    """
    filepath = "/data/Software/mydan/AGENT/device/conf/account/" + cloud

    with open(filepath) as fp:
        for line in fp:
            parts = line.split()
            if len(parts) == 0:
                continue
            if parts[0].strip() == account:
                data = {
                    "access_id": parts[1].strip(),
                    "access_key": parts[2].strip()
                }
                if len(parts) >= 5 and cloud == "aws":
                    data["account_region"] = parts[4]
                return data

    raise Exception("未找到指定账号")


def main(cloud, account):
    data = describe_account_info(cloud, account)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
