#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json


def keep_fields(data_list, target_fields):
    """
        字段过滤
    """
    result = []
    fields_list = target_fields.split(",")
    m = {}
    for field in fields_list:
        m[field] = {}
    for data in data_list:
        for field in list(data):
            if field in m:
                continue
            data.pop(field, None)
        result.append(data)
    return result


def main(data_list, target_fields):
    """
    target_fields 是要保留的字段, 多个字段用英文逗号分隔
    """
    result = keep_fields(data_list, target_fields)
    for data in result:
        print(json.dumps(data, default=str))


if __name__ == '__main__':
    data_list = []
    for line in sys.stdin:
        data_list.append(json.loads(line))

    main(data_list, sys.argv[1])
