#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def c3mc_yes_and_no():
    """
        输出 是 和 否，作为选项数据
    """
    return [
        {
            "id": True,
            "name": "是",
        },
        {
            "id": False,
            "name": "否",
        },
    ]


def main():
    option_list = c3mc_yes_and_no()
    for option in option_list:
        print(json.dumps(option, default=str))


if __name__ == '__main__':
    main()
