#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import os


def search_files(rootdir, prefix, account):
    for subdir, dirs, files in os.walk(rootdir):
        for file in files:
            filepath = os.path.join(subdir, file)
            if filepath.startswith(prefix):
                with open(filepath) as f:
                    for line in f:
                        if line.startswith(account):
                            return line.strip()
    return None


def describe_account_info(cloud, account):
    """
        查询指定账号的信息
    """

    dir_path = ("/data/Software/mydan/AGENT/device/conf/account/")
    prefix = (f"/data/Software/mydan/AGENT/device/conf/account/{cloud}")

    account_line = search_files(dir_path, prefix, account)
    if account_line is None:
        raise type('DataNotFound', (Exception,), {})('无法找到账号信息')
    parts = account_line.split()
    if cloud == "google":
        return {
            "cred_path": parts[1]
        }
    else:
        return {
            "access_id": parts[1].strip(),
            "access_key": parts[2].strip(),
        }


def main(cloud, account):
    data = describe_account_info(cloud, account)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
