#Author: lijinfeng2011@gmail.com

FROM centos:7
MAINTAINER lijinfeng2011

ADD temp/cloudeye-exporter /
ADD temp/metric.yml        /
ADD temp/logs.yml         /
ADD entrypoint.sh          /
ENTRYPOINT [ "/entrypoint.sh" ]
