#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use Util;
use JSON;
use Encode;
use LWP::UserAgent;

$| ++;

=head1 SYNOPSIS

    id => 1,
    logs => 日志对象

=cut

return sub
{
    my ( %param, @list )= @_;
    my ( $db, $id ) = @param{qw( db id )};

    die "id not a number" unless $id =~ /^\d+$/;
 
    my @data;
    my $i = 1;
    my @x = `c3mc-base-fullnodeinfo --col id,name,type,inip,exip $id`;
    chomp @x;
    for( @x )
    {
        my @t = split /;/, $_;
        push @data, +{ id => $i++, name => Encode::decode( 'utf8', $t[1] ), type => $t[2], inip => $t[3], exip => $t[4] };
    }

    my $x = $db->query( "select ip,status,fail,reason,version,edit_time from openc3_agent_monitor where projectid=$id" );
    die "get data error from db" unless defined $x && ref $x eq 'ARRAY';

    my %ip;
    map{ $ip{$_->[0]} = +{ status => $_->[1], fail => $_->[2], reason => $_->[3], version => $_->[4], edit_time => $_->[5] } }@$x;

    push @list, map{ +{ %$_, inips => $ip{$_->{inip}} || +{}, exips => $ip{$_->{exip}} || +{} } }@data;

    return @list;
}
