---
option:
  - describe: 运维审批人
    name: opapprover
    type: input
    value: ""

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/域名解析/修改"
  content:  "申请人:${_user_} 域名: ${x.domain} BPM单号: ${_bpmuuid_}"
