#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

import boto3


def get(data, access_id, access_key, region):
    """
        输出 aws rds 的详情(json格式)
    """
    endpoint_url = "https://rds.{}.amazonaws.com".format(region)
    if region.startswith("cn"):
        endpoint_url = "https://rds.{}.amazonaws.com.cn".format(region)
    client = boto3.client(
        "rds",
        endpoint_url=endpoint_url,
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region,
    )

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field database aws-rds DBInstanceIdentifier")

    response = client.describe_db_instances(
        DBInstanceIdentifier=data[field_name],
    )

    for instance in response["DBInstances"]:
        if instance["DBInstanceIdentifier"] == data[field_name]:
            instance["RegionId"] = region
            return instance
    raise Exception(
        "根据 DBInstanceIdentifier {} 未找到 aws rds".format(data[field_name]))


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
