download:
  - template: sync-aliyun-ecs
  - template: sync-aliyun-ecs-volume
  - template: sync-aliyun-oss
  - template: sync-aliyun-rds
  - template: sync-aliyun-redis
  - template: sync-aliyun-slb
  - template: sync-aliyun-vpc

  - template: sync-aws-alb
  - template: sync-aws-nlb
  - template: sync-aws-dynamodb
  - template: sync-aws-ec2
  - template: sync-aws-ec2-event
  - template: sync-aws-ec2-volume
  - template: sync-aws-elb
  - template: sync-aws-memcached
  - template: sync-aws-rds
  - template: sync-aws-redis
  - template: sync-aws-s3
  - template: sync-aws-kafka
  - template: sync-aws-lightsail-database
  - template: sync-aws-lightsail-instance
  - template: sync-aws-lightsail-loadbalancer

  - template: sync-google-lb
  - template: sync-google-rds
  - template: sync-google-vm
  - template: sync-google-redis
  - template: sync-google-vm-volume

  - template: sync-huawei-ecs
  - template: sync-huawei-ecs-volume
  - template: sync-huawei-dds
  - template: sync-huawei-elb
  - template: sync-huawei-nosql
  - template: sync-huawei-rds
  - template: sync-huawei-redis
  - template: sync-huawei-obs
  - template: sync-huawei-kafka

  - template: sync-ibm-bare-metal-server
  - template: sync-ibm-virtual-server

  - template: sync-ksyun-epc
  - template: sync-ksyun-kec
  - template: sync-ksyun-kec-volume
  - template: sync-ksyun-krds
  - template: sync-ksyun-ks3
  - template: sync-ksyun-redis
  - template: sync-ksyun-slb

  - template: sync-qcloud-cdb
  - template: sync-qcloud-ckafka
  - template: sync-qcloud-clb
  - template: sync-qcloud-cos
  - template: sync-qcloud-cvm
  - template: sync-qcloud-cvm-volume
  - template: sync-qcloud-mongodb
  - template: sync-qcloud-redis
  - template: sync-qcloud-sqlserver
  - template: sync-qcloud-vpc
  - template: sync-qcloud-subnet
  - template: sync-qcloud-tdsql-c-mysql

  - template: xlsx-capital-online-server
