#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from huaweicloudsdkevs.v2 import *

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_huawei_evs import LibHuaweiEvs


def tag_add(data, access_id, access_key, project_id, region):
    lib_client = LibHuaweiEvs(access_id, access_key, project_id, region)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage huawei-ecs-volume id"
    )

    tag_list = []
    for item in data["_control_"]["tag-add"]["tags"].split(","):
        parts = item.split("=")
        if len(parts) != 2:
            continue
        tag_list.append(Tag(key=parts[0], value=parts[1]))
    
    lib_client.add_tags(data[field_name], tag_list)


def main(data, access_id, access_key, project_id, region):
    tag_add(data, access_id, access_key, project_id, region)


if __name__ == "__main__":
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise RuntimeError("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
