#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def describe_protocol_type_list():
    return [
        {
            "id": "http",
            "name": "http",
        },
        {
            "id": "https",
            "name": "https",
        },
        {
            "id": "tcp",
            "name": "tcp",
        },
        {
            "id": "udp",
            "name": "udp",
        },
    ]


def main():
    data_list = describe_protocol_type_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
