#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def describe_instance_type_list():
    return [
        {
            "id": "应用型",
            "name": "应用型",
        },
        {
            "id": "传统型",
            "name": "传统型",
        },
    ]


def main():
    data_list = describe_instance_type_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
