#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def describe_network_type_list():
    return [
        {
            "id": "公网",
            "name": "公网",
        },
        {
            "id": "内网",
            "name": "内网",
        },
    ]


def main():
    data_list = describe_network_type_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
