#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

use JSON;
use YAML::XS;

my ( $id, $ns, $name ) = @ARGV;
die "argv err" unless $id   && $id   =~ /^\d+$/;
die "argv err" unless $ns   && $ns   =~ /^[a-zA-Z][a-zA-Z0-9\-]*$/;
die "argv err" unless $name && $name =~ /^[a-zA-Z][a-zA-Z0-9\-]*$/;

my    $kubectl = `c3mc-k8s-kubectl-get -i $id`;
chomp $kubectl;

my $x = `$kubectl get deployment '$name' -n '$ns' -o json`;
my $data = eval{ JSON::decode_json( $x ); };
die "load data from json fail: $@" if $@;

exit unless $data->{spec};
exit unless $data->{spec}{template};
exit unless $data->{spec}{template}{spec};

unless( $data->{spec}{template}{spec}{affinity} )
{
    print "nofind:affinity\n";
    exit;
}
unless( $data->{spec}{template}{spec}{affinity}{nodeAffinity} )
{
    print "nofind:affinity.nodeAffinity\n";
    exit;
}
unless( $data->{spec}{template}{spec}{affinity}{nodeAffinity}{preferredDuringSchedulingIgnoredDuringExecution} )
{
    print "nofind:affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution\n";
    exit;
}

unless( @{ $data->{spec}{template}{spec}{affinity}{nodeAffinity}{preferredDuringSchedulingIgnoredDuringExecution} } )
{
    print "nofind:affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution == 0";
    exit;
}

my $curr = YAML::XS::Dump $data->{spec}{template}{spec}{affinity}{nodeAffinity}{preferredDuringSchedulingIgnoredDuringExecution};

unless( index( $curr, 'c3.spotx.node.role/small' ) > 0 && index( $curr, 'c3.spotx.node.role/large' ) > 0 )
{
    print "nofind:affinity=c3.spotx.node.role/small,c3.spotx.node.role/large\n";
    exit;
}

print "ok.\n";
