#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_qcloud_tag import QcloudTag


def tag_add(data, access_id, access_key, region, uin):
    lib_client = QcloudTag(access_id, access_key, region)

    field_name_list = subprocess.getoutput(
        "c3mc-cloud-get-real-field database qcloud-sqlserver Region InstanceId")

    rid = f"qcs::sqlserver:{data[field_name_list[0]]}:uin/{uin}:instance/{data[field_name_list[1]]}"

    tags_list = []
    for item in data["_control_"]["tags"].split(","):
        parts = item.split("=")
        if len(parts) != 2:
            continue
        tags_list.append({
            "key": parts[0],
            "value": parts[1]
        })

    lib_client.add_tag_by_replace(rid, tags_list)


def main(data, access_id, access_key, region, uin):
    tag_add(data, access_id, access_key, region, uin)


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise RuntimeError("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
