#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess
import time

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.clb.v20180317 import clb_client, models


class Clb:
    def __init__(self, access_id, access_key, region, params):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.params = params
        self.client = self.create_client()

    def create_client(self):
        cred = credential.Credential(
            self.access_id, self.access_key)
        httpProfile = HttpProfile()
        httpProfile.endpoint = "clb.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        return clb_client.ClbClient(cred, self.region, clientProfile)

    def get_request(self):
        req = models.CreateLoadBalancerRequest()

        cmd_parts = ["c3mc-cloud-qcloud-get-cvm", self.params["account"],
                     self.params["instance_ids"].split(",")[0], self.region]
        output = subprocess.run(cmd_parts, capture_output=True, text=True)
        if output.returncode != 0:
            print(output.stderr, file=sys.stderr)
            exit(1)
        cvmInfo = json.loads(output.stdout)

        network_type = "INTERNAL" if self.params["network_type"] == "内网" else "OPEN"
        api_params = {
            "LoadBalancerType": network_type,
            "Forward": 1,
            "ProjectId": int(self.params["project_id"]),
            "LoadBalancerName": self.params["clb_name"],
            "VpcId": cvmInfo["VirtualPrivateCloud"]["VpcId"],
            "Number": 1
        }
        if network_type == "INTERNAL":
            api_params["SubnetId"] = cvmInfo["VirtualPrivateCloud"]["SubnetId"]
        if "tag" in self.params:
            tag_list = json.loads(self.params["tag"])
            if len(tag_list) > 0:
                api_params["Tags"] = [
                    {"TagKey": tag['key'], "TagValue": tag['value']}
                    for tag in tag_list
                ]
        req.from_json_string(json.dumps(api_params))
        return req

    def create_clb(self, req):
        resp = self.client.CreateLoadBalancer(req)
        return json.loads(resp.to_json_string())


def main(params):
    account = params["account"]
    region = params["region"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info qcloud {account}")
    )

    clb = Clb(key_info["access_id"],
              key_info["access_key"], region, params)

    req = clb.get_request()
    print(f"创建clb, 请求参数为: {req}")

    if subprocess.getoutput("c3mc-sys-ctl sys.bpm.fake.run") == "1":
        # bpm虚假运行
        print("创建clb, 响应为: xxxxxx")
        print("LOG. clb_id:xxxxxx")
        print("VAR. clb_id:xxxxxx")
        print("VAR. extinstance_id:xx.cc.vv")
    else:
        try:
            resp = clb.create_clb(req)
            print("创建clb, 响应为: {}".format(json.dumps(resp)))

            clb_id = resp["LoadBalancerIds"][0]

            print("LOG. clb_id:{}".format(clb_id))
            print("VAR. clb_id:{}".format(clb_id))
            print("VAR. extinstance_id:{}.{}.{}".format(
                params["account"], params["region"], clb_id))
        except Exception as e:
            print(f"创建腾讯云clb出错, err: {e}", file=sys.stderr)
            exit(1)

        # 防止后续立即执行创建监听器时报错
        # 休眠一会儿等待clb状态正常
        time.sleep(25)


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]))
