#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import sys
import json

from kscore.session import get_session
sys.path.append("/data/Software/mydan/Connector/lib/pp")


class Kec:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.page_size = 25
        self.client = self.create_client()

    def create_client(self):
        s = get_session()
        client = s.create_client(
            "kec", ks_access_key_id=self.access_id, ks_secret_access_key=self.access_key, region_name=self.region)
        return client

    def get_instances_from_response(self, response_data):
        results = []
        for instance in response_data["InstancesSet"]:
            instance["RegionId"] = instance["AvailabilityZone"][:-1]
            results.append(instance)
        return results

    def list_instances(self):
        response = self.client.describe_instances(MaxResults=self.page_size)
        results = self.get_instances_from_response(response)
        while "Marker" in response:
            if response["Marker"] is None or response["Marker"] == 0:
                break
            response = self.client.describe_instances(
                MaxResults=self.page_size, Marker=response["Marker"])
            results.extend(self.get_instances_from_response(response))

        tag_dict = self.list_tag()
        for i, s in enumerate(results):
            if s["InstanceId"] in tag_dict:
                results[i]["Tag"] = tag_dict[s["InstanceId"]]
        return results

    def list_tag(self):
        from c3mc_cloud_ksyun_get_tag import GetTag
        return GetTag(self.access_id, self.access_key, self.region).get_tag_dict()

    def show(self):
        instance_list = self.list_instances()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    Kec(access_id, access_key, region).show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
