#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json

from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.auth.credentials import AccessKeyCredential
from aliyunsdkecs.request.v20140526.DescribeDisksRequest import DescribeDisksRequest


def get_volume(data_list):
    result = []
    m = {}
    for data in data_list:
        if "_aksk_" not in data:
            continue

        parts = data["_aksk_"].split()

        credentials = AccessKeyCredential(parts[1], parts[2])
        client = AcsClient(region_id=parts[3], credential=credentials)

        request = DescribeDisksRequest()
        request.set_accept_format('json')
        request.set_InstanceId(data["InstanceId"])
        response = client.do_action_with_exception(request)

        response_data = json.loads(response)
        for item in response_data["Disks"]["Disk"]:
            if item["DiskId"] in m:
                continue
            m[item["DiskId"]] = {}

            item["account"] = data["account"]
            item["accountuuid"] = data["accountuuid"]
            item["Tag"] = item["Tags"]["Tag"]
            item.pop("Tags", None)
            result.append(item)

    return result


def main(data_list):
    result = get_volume(data_list)
    for item in result:
        print(json.dumps(item, default=str))


if __name__ == '__main__':
    data_list = []
    for line in sys.stdin:
        data_list.append(json.loads(line))

    main(data_list)
