#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import sys
import json


def filter_fields(data_list, fields):
    result = []
    field_list = fields.split(";")

    for item in data_list:
        d = {}
        for field in field_list:
            if field in item:
                d[field] = item[field]
        if len(d) > 0:
            result.append(d)
    return result


def main(data_list, fields):
    result = filter_fields(data_list, fields)
    for item in result:
        print(json.dumps(item, default=str))


if __name__ == '__main__':
    data_list = []
    for line in sys.stdin:
        data_list.append(json.loads(line))

    main(data_list, sys.argv[1])
