#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json

from google.oauth2 import service_account
from google.cloud import compute_v1
from google.protobuf.json_format import MessageToJson


def get_volume(data_list):
    result = []
    m_zone = {}
    m_aksk = {}
    for data in data_list:
        if "_aksk_" not in data:
            continue

        m_aksk[data["_aksk_"]] = data["accountuuid"]
        m_zone[data["zone"].split("/")[-1]] = {}

    for aksk, accountuuid in m_aksk.items():
        for zone in list(m_zone.keys()):
            parts = aksk.split()

            credentials = service_account.Credentials.from_service_account_file(
                parts[1])
            disk_client = compute_v1.DisksClient(credentials=credentials)

            for disk in disk_client.list(project=credentials.project_id, zone=zone):
                item = json.loads(MessageToJson(disk._pb))
                item["typeCode"] = item["type"].split("/")[-1]
                item["zoneId"] = zone
                item["regionId"] = zone[:-2]

                item["account"] = parts[0]
                item["accountuuid"] = accountuuid

                if "labels" in item:
                    item["tags"] = []
                    for key, value in item["labels"].items():
                        item["tags"].append({
                            "key": key,
                            "value": value
                        })
                result.append(item)
    return result


def main(data_list):
    result = get_volume(data_list)
    for item in result:
        print(json.dumps(item, default=str))


if __name__ == '__main__':
    data_list = []
    for line in sys.stdin:
        data_list.append(json.loads(line))

    main(data_list)
