#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json

import boto3


class Volume:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()
        self.page_size = 50

    def create_client(self):
        client = boto3.client(
            "ec2",
            aws_access_key_id=self.access_id,
            aws_secret_access_key=self.access_key,
            region_name=self.region,
        )
        return client

    def get_instances_from_response(self, response_data):
        result = []
        for volume in response_data["Volumes"]:
            volume["RegionId"] = volume["AvailabilityZone"][:-1]
            result.append(volume)
        return result

    def get_response(self):
        response = self.client.describe_volumes(MaxResults=self.page_size)
        result = self.get_instances_from_response(response)
        while "NextToken" in response:
            response = self.client.describe_volumes(
                NextToken=response["NextToken"], MaxResults=self.page_size)
            result.extend(self.get_instances_from_response(response))
        return result

    def show(self):
        volume_list = self.get_response()
        for instance in volume_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    Volume(access_id, access_key, region).show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
