#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-


import sys
import json
import subprocess
import yaml


def get_department_info(user_email):
    try:
        output = subprocess.getoutput(f"c3mc-base-userinfo -u {user_email}")
        return yaml.safe_load(output)
    except Exception as e:
        print(f"无法获取账号 {user_email} 的部门信息", file=sys.stderr)
        return None


def run(data_list):
    m = {}
    for index, item in enumerate(data_list):
        if "_product_owner_" not in item:
            continue

        product_owner = item["_product_owner_"]

        if product_owner not in m:
            department_info = get_department_info(product_owner)
            if department_info:
                m[product_owner] = department_info

        if product_owner in m:
            if "oneDeptName" in m[product_owner]:
                data_list[index]["_oneDeptName_"] = m[product_owner]["oneDeptName"]

            if "sybDeptName" in m[product_owner]:
                data_list[index]["_sybDeptName_"] = m[product_owner]["sybDeptName"]

    return data_list

def display(data_list):
    data_list = run(data_list)
    for item in data_list:
        print(json.dumps(item, default=str))
    

def main(data_list):
    display(data_list)


if __name__ == '__main__':
    """往data_list中插入业务负责人的一级部门和二级部门信息

    注意: 查找业务负责人时依赖 _product_owner_ 字段。而 c3mc-cloud-tag-v2 脚本负责往数据中插入 _product_owner_ 字段
    所在在管道调用中, 该脚本应该放在 c3mc-cloud-tag-v2 的后面执行
    """
    data_list = [json.loads(line) for line in sys.stdin]
    main(data_list)
