#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json

import boto3


class Rds:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()
        self.page_size = 20

    def create_client(self):
        client = boto3.client(
            "rds",
            endpoint_url="https://rds.{}.amazonaws.com".format(self.region),
            aws_access_key_id=self.access_id,
            aws_secret_access_key=self.access_key,
            region_name=self.region,
        )
        return client

    def get_instances_from_response(self, response_data):
        results = []
        for instance in response_data["DBInstances"]:
            instance["RegionId"] = self.region
            results.append(instance)
        return results

    def get_response(self):
        response = self.client.describe_db_instances(MaxRecords=self.page_size)
        results = self.get_instances_from_response(response)
        while "Marker" in response:
            response = self.client.describe_db_instances(
                MaxRecords=self.page_size, Marker=response["Marker"])
            results.extend(self.get_instances_from_response(response))
        return results

    def show(self):
        instance_list = self.get_response()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    rds = Rds(access_id, access_key, region)
    rds.show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
