#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib -I/data/Software/mydan/Connector/private/lib
use strict;
use warnings;
use Logs;

$| ++;

=head1 SYNOPSIS

    id => 1,
    logs => 日志对象

=cut

my ( $nodeinfo, %env, $debug, $apicache );
BEGIN{
    use Configini;
    $nodeinfo = Configini::get( 'nodeinfo' );
    %env = Configini::env( 'nodeinfoenv' );

    $debug = Configini::get( 'debug' );
    $apicache = Configini::get( 'apicache' );
    $apicache = 0 unless $apicache && $apicache =~ /^\d+$/;
};

return sub
{
    my ( %param )= @_;
    my ( $id, $logs ) = @param{qw(id logs)};

    $logs = Logs->new( 'code.nodeinfo' ) unless $logs;

    $logs->die( "id not a number" ) unless $id =~ /^\d+$/;

    my $ua = LWP::UserAgent->new;
    $ua->default_header( %env ) if %env;
    $ua->timeout( 10 );

    my $file;
    if( $apicache )
    {
        $file = "/tmp/openc3-cache-api-nodeinfo-$id";

        $ua->timeout( 3 );

        if( -f $file )
        {
            my $mtime = ( stat $file )[9];
            if( $mtime  && ( $mtime + $apicache > time ) )
            {
                my $filecont = eval{ YAML::XS::LoadFile $file };
                if( $filecont && ref $filecont eq 'ARRAY' )
                {
                    $logs->say( "nodeinfo api usetime: cache" );
                    return @$filecont;
                }
            }
         }
    }

    my $t = time;
    my $res = $ua->get( "$nodeinfo$id" );

    $logs->say( YAML::XS::Dump $res ) if $debug;
    my $utime = time - $t;
    $logs->say( "nodeinfo api usetime: $utime" );

    if($res->is_success)
    {
        my $v = eval{decode_json $res->decoded_content};
        if( $v->{stat} && ref $v->{data} eq 'ARRAY' )
        {
            map{ $_->{name} = "unkown" if $_->{name} !~ /^[a-zA-Z0-9\.\-_]$/ }@{$v->{data}};
            eval{ YAML::XS::DumpFile $file, $v->{data} } if $apicache;
            return @{$v->{data}};
        }
    }
    elsif( $apicache )
    {
        if( -f $file )
        {
            my $mtime = ( stat $file )[9];
            if( $mtime  && ( $mtime + 86400 > time ) )
            {
                my $filecont = eval{ YAML::XS::LoadFile $file };
                if( $filecont && ref $filecont eq 'ARRAY' )
                {
                    $logs->err( "nodeinfo api usetime: cache" );
                    return @$filecont;
                }
            }
         }
    }
    #TODO die
    die "die";
}
