#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib -I/data/Software/mydan/Connector/private/lib
use strict;
use warnings;
use Logs;
use YAML::XS;
use LWP::UserAgent;
use Digest::MD5;
use JSON qw();

$| ++;

=head1 SYNOPSIS

    cookie => 'cookiestring',
    treeid =>
    point =>

    logs => 日志对象

=cut

my ( $pmspoint, @eid, %env, $ssousername, %ssousernameenv, $debug, $apicache );
BEGIN{
    use Configini;
    $pmspoint = Configini::get( 'pmspoint' );
    %env = Configini::env( 'pmspointenv' );

    my $eid = Configini::get( 'pmspointeid' );
    @eid = @$eid if $eid && ref $eid eq 'ARRAY' && @$eid == 3;

    $ssousername = Configini::get( 'ssousername' );
    %ssousernameenv = Configini::env( 'ssousernameenv' );
    die "ssousername undef on config.ini" unless $ssousername;

    $debug = Configini::get( 'debug' );
    $apicache = Configini::get( 'apicache' );
    $apicache = 0 unless $apicache && $apicache =~ /^\d+$/;
};

return sub
{
    my ( %param )= @_;
    my ( $cookie, $point, $treeid, $logs, $db ) = @param{qw(cookie point treeid logs db )};

    $treeid ||= 0;
    $logs = Logs->new( 'code.point' ) unless $logs;
#    $logs->die( "id not a number" ) unless $id =~ /^\d+$/;

    return 1 if $treeid && $treeid == 4000000000;
    if( $treeid && $treeid >= 4000000000 )
    {
        my $ua = LWP::UserAgent->new;
        $ua->default_header( %ssousernameenv ) if %ssousernameenv;
        my $res = $ua->get( "$ssousername$param{cookie}" );

        $logs->say( YAML::XS::Dump $res ) if $debug;

        if($res->is_success)
        {
            my $v = eval{JSON::decode_json $res->decoded_content};
            return undef unless $v->{stat};
            my $user = $v->{data}{user};
            $user =~ s/\./_/;
            my $match = eval{ $db->query( "select id from openc3_connector_private where id='$treeid' and user='$user'" )};
            return $match && @$match > 0 ? 1 : 0;
        }
        return 0;

    }
    my $ua = LWP::UserAgent->new;
    $ua->default_header( %env ) if %env;
    $ua->timeout( 10 );

    my $treestr = '';
    if( defined $treeid )
    {
        if( $treeid )
        {

            if( @eid )
            {
                $treeid = $eid[2] unless $eid[0] <= $treeid && $treeid <= $eid[1];
            }

            $treestr = "&treeid=$treeid";
        }
        else
        {
            if( $point =~ /_read$/ )
            {
                return 1;
            }
            else
            {
                $point =~ s/_write$/_root/;
                $point =~ s/_delete$/_root/;
            }
        }
    }

    my $file;
    if( $apicache )
    {
        my $md5 = Digest::MD5->new->add( "$pmspoint?point=$point$treestr&cookie=$cookie" )->hexdigest;
        $file = "/tmp/openc3-cache-api-point-$md5";
        $ua->timeout( 3 );

        if( -f $file )
        {
            my $apicachetimeout = -f '/var/openc3_connector_api_fail' ? 86400 : $apicache;

            my $mtime = ( stat $file )[9];
            if( $mtime  && ( $mtime + $apicachetimeout > time ) )
            {
                my $filecont = eval{ YAML::XS::LoadFile $file };
                if( $filecont && ! $@ )
                {
                    $logs->say( "point api usetime: cache" );
                    return $filecont;
                }
            }
        }
    }


    my $t = time;
    my $res = $ua->get( "$pmspoint?point=$point$treestr&cookie=$cookie" );

    $logs->say( YAML::XS::Dump $res ) if $debug;
    my $utime = time - $t;
    $logs->say( "point api usetime: $utime" );# if $debug;

    if($res->is_success)
    {
        my $v = eval{JSON::decode_json $res->decoded_content};
        eval{ YAML::XS::DumpFile $file, $v->{data} } if $apicache && $v->{stat};
        return $v->{data} if $v->{stat};
    }
    elsif( $apicache )
    {
        if( -f $file )
        {
            my $mtime = ( stat $file )[9];
            if( $mtime  && ( $mtime + 86400 > time ) )
            {
                my $filecont = eval{ YAML::XS::LoadFile $file };
                if( $filecont && ! $@ )
                {
                    $logs->err( "point api usetime: cache" );
                    return $filecont;
                }
            }
        }
    }
    die $res->content;
};
1
