#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib -I/data/Software/mydan/Connector/private/lib
use strict;
use warnings;
use Logs;
use LWP::UserAgent;
use JSON qw();

$| ++;

=head1 SYNOPSIS

    cookie => 'cookiestring',
    logs => 日志对象

=cut

my ( $treemap, $treemapgrep, %env, $debug, $apicache );
BEGIN{
    use Configini;
    $treemap = Configini::get( 'treemap' );
    %env = Configini::env( 'treemapenv' );

    $treemapgrep = Configini::get( 'treemapgrep' );
    $treemapgrep = undef unless $treemapgrep && ref $treemapgrep eq 'ARRAY';

    $debug = Configini::get( 'debug' );
    $apicache = Configini::get( 'apicache' );
    $apicache = 0 unless $apicache && $apicache =~ /^\d+$/;
};

return sub
{
    my ( %param )= @_;
    my ( $cookie, $logs ) = @param{qw(cookie logs)};

    $logs = Logs->new( 'code.treemap' ) unless $logs;
#    $logs->die( "id not a number" ) unless $id =~ /^\d+$/;

    my $ua = LWP::UserAgent->new;
    $ua->default_header( %env ) if %env;
    $ua->timeout( 10 );

    my $file;
    if( $apicache )
    {
        $file = "/tmp/openc3-cache-api-treemap";
        $ua->timeout( 3 );

        if( -f $file )
        {
            my $apicachetimeout = -f '/var/openc3_connector_api_fail' ? 86400 : $apicache;

            my $mtime = ( stat $file )[9];
            if( $mtime  && ( $mtime + $apicachetimeout > time ) )
            {
                my $filecont = eval{ YAML::XS::LoadFile $file };
                if( $filecont && ! $@ )
                {
                    $logs->say( "treemap api usetime: cache" );
                    return $treemapgrep ? TreeMap::mapgrep( $filecont, @$treemapgrep ) : $filecont;
                }
            }
        }
    }



    my $t = time;
    my $res = $ua->get( $treemap );

    $logs->say( YAML::XS::Dump $res ) if $debug;
    my $utime = time - $t;
    $logs->say( "treemap api usetime: $utime" );

    if($res->is_success)
    {
        my $v = eval{JSON::decode_json $res->decoded_content};
        eval{ YAML::XS::DumpFile $file, $v->{data} } if $apicache && $v->{stat};
        if( $v->{stat} )
        {
            return $treemapgrep ? TreeMap::mapgrep( $v->{data}, @$treemapgrep ) : $v->{data};
        }
    }
    elsif( $apicache )
    {
        if( -f $file )
        {
            my $mtime = ( stat $file )[9];
            if( $mtime  && ( $mtime + 86400 > time ) )
            {
                my $filecont = eval{ YAML::XS::LoadFile $file };
                if( $filecont && ! $@ )
                {
                    $logs->err( "treemap api usetime: cache" );
                    return $treemapgrep ? TreeMap::mapgrep( $filecont, @$treemapgrep ) : $filecont;
                }
            }
        }
    }
    #TODO die

    die "die";
}
