#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_qcloud_tag import QcloudTag


def tag_add(data, access_id, access_key, region, uin):
    lib_client = QcloudTag(access_id, access_key, region)

    field_name_list = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage qcloud-cos Location Name").split()
    
    name_parts = data[field_name_list[1]].split("-")
    
    rid = f"qcs::cos:{data[field_name_list[0]]}:uid/{name_parts[-1]}:prefix/{name_parts[-1]}/{'-'.join(name_parts[:-1])}/*"

    need_delete_key_set = set()
    for item in data["_control_"]["tag-delete"]["tags"].split(","):
        parts = item.split("=")
        if len(parts) != 2:
            continue
        need_delete_key_set.add(parts[0])

    lib_client.tag_delete(rid, list(need_delete_key_set))


def main(data, access_id, access_key, region, uin):
    tag_add(data, access_id, access_key, region, uin)


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise RuntimeError("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
