#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_s3 import AWS_S3


def tag_add(data, access_id, access_key, region):
    lib_client = AWS_S3(access_id, access_key, region)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage aws-s3 BucketName"
    )

    tag_list = lib_client.list_tag(data[field_name])

    for item in data["_control_"]["tag-add"]["tags"].split(","):
        parts = item.split("=")
        if len(parts) != 2:
            continue

        found = False
        for i in range(len(tag_list)):
            if tag_list[i]["Key"] == parts[0]:
                tag_list[i]["Value"] = parts[1]
                found = True
                break
        if not found:
            tag_list.append({
                "Key": parts[0],
                "Value": parts[1],
            })
    
    lib_client.update_tags(data[field_name], tag_list)


def main(data, access_id, access_key, region):
    tag_add(data, access_id, access_key, region)


if __name__ == "__main__":
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise RuntimeError("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
