#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use JSON;

$| ++;

=head1 SYNOPSIS

=cut

return sub
{
    die "get cookie key fail: $!" if system "c3mc-base-configx cookiekey > $RealBin/../conf/cookiekey";
}
