#!/usr/bin/env perl
use strict;
use warnings;

binmode STDIN,  ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

use YAML::XS;

my ( $id, $cont ) = @ARGV;
die "id err" unless $id && $id =~ /^\d+$/;
die "cont err" unless $cont;

my $tf = "/etc/c3bot.token";
my $token = `cat $tf`;
chomp $token;

my $x = `curl \\
  -X POST \\
  -H "Accept: application/vnd.github+json" \\
  -H "Authorization: Bearer $token"\\
  -H "X-GitHub-Api-Version: 2022-11-28" \\
  https://api.github.com/repos/open-c3/open-c3/issues/$id/comments \\
  -d '{"body":"$cont"}'
  2>/dev/null`;

die "curl err: $!" if $?;
