#!/usr/bin/env perl

use strict;
use warnings;

use YAML::XS;

die unless my $id = shift @ARGV;

my $x = `curl \\
  -H "Accept: application/vnd.github+json" \\
  https://api.github.com/repos/open-c3/open-c3/issues/$id/comments \\
  2>/dev/null`;

my $data = YAML::XS::Load $x;

for my $pr ( @$data )
{
    $pr->{body} =~ s/\n/ /g;
    printf "%s\n", join "\t",
        $pr->{ created_at },
        $pr->{ user       }{ login },
        $pr->{ body       };
}
