#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess

sys.path.append("/data/Software/mydan/Connector/lib/pp")


def get_data_list(access_id, access_key, region):
    from c3mc_cloud_qcloud_cdb import QcloudCdb

    res = QcloudCdb(access_id, access_key, region).DescribeCdbZoneConfig()

    result = [
        {
            "id": item["Region"],
            "name": item["RegionName"],
        }
        for item in res["DataResult"]["Regions"]
    ]
    return sorted(result, key=lambda x: x['id'], reverse=False)


def main(params):
    """针对mysql查询区域列表"""
    account = params["account"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info qcloud {account}")
    )
    data_list = get_data_list(
        key_info["access_id"], key_info["access_key"], "ap-beijing"
    )
    for item in data_list:
        print(json.dumps(item))


if __name__ == "__main__":
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type("WrongInputData", (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
