#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")


def get_data_list(access_id, access_key, region, project_id):
    from c3mc_cloud_qcloud_alarm import QcloudMonitor

    return QcloudMonitor(access_id, access_key, region).DescribeAlarmPolicies(project_id)


def main(params):
    """查询监控配置列表
    """
    account = params["account"]
    region = params["region"]
    project_id = params["project_id"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info qcloud {account}")
    )
    data_list = get_data_list(
        key_info["access_id"], key_info["access_key"], region, int(project_id))

    data_list = sorted(data_list, key=lambda x: (x['PolicyName'].lower()), reverse=False)
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
