#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess

sys.path.append("/data/Software/mydan/Connector/lib/pp")


def get_data_list(access_id, access_key, region):
    from c3mc_cloud_qcloud_cdb import QcloudCdb

    res = QcloudCdb(access_id, access_key, region).DescribeCdbZoneConfig()

    result = []
    for item in res["DataResult"]["Regions"]:
        if item["Region"] == region:
            for zone_item in item["RegionConfig"]:
                status_text = ""
                if zone_item["Status"] == 1:
                    status_text = "正常"
                elif zone_item["Status"] == 3:
                    status_text = "停售"
                else:
                    # "不显示" 状态的可用区不进行显示
                    continue
                result.append({
                    "zone": zone_item["Zone"],
                    "zone_name": zone_item["ZoneName"],
                    "status": status_text,
                })
    return sorted(result, key=lambda x: x['zone'].lower(), reverse=False)


def main(params):
    """查询可用区列表
    """
    account = params["account"]
    region = params["region"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info qcloud {account}")
    )
    data_list = get_data_list(
        key_info["access_id"], key_info["access_key"], region)
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
