#!/bin/bash
# 删除sudo权限

set -e

# 用户账户
username=$1
# 目标IP
ip=$2

# 删除sudo权限
command="sudo gpasswd -d $username wheel>/dev/null 2>&1;
         cat /etc/group | grep wheel | grep -w $username | wc -l"

ssh -t $ip "$command"
