#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_ec2 import LIB_EC2


def main(params):
    account = params["account"]
    region = params["region"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info aws {account}")
    )

    data_list = LIB_EC2(
        key_info["access_id"], key_info["access_key"], region).describe_all_instances_of_region()
    for item in data_list:
        print(json.dumps(item, default=str))


if __name__ == '__main__':
    line_list = list(sys.stdin)
    if not line_list or len(line_list) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(line_list[0]))
