#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import subprocess
import os


def main():
    action_path = "/data/Software/mydan/Connector/pp/crontask/action"
    if not os.path.exists(action_path):
        return []

    cmd_parts = ["ls", action_path]
    output = subprocess.run(cmd_parts, capture_output=True, text=True)
    if output.returncode != 0:
        print(output.stderr, file=sys.stderr)
        exit(1)
    output = output.stdout.strip().split("\n")

    for item in output:
        print(item)


if __name__ == '__main__':
    main()
