#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.ckafka.v20190819 import ckafka_client, models


def get(data, access_id, access_key, region):
    """
        输出 qcloud ckafka 的详情(json格式)
    """
    cred = credential.Credential(access_id, access_key)
    httpProfile = HttpProfile()
    httpProfile.endpoint = "ckafka.tencentcloudapi.com"

    clientProfile = ClientProfile()
    clientProfile.httpProfile = httpProfile
    client = ckafka_client.CkafkaClient(cred, region, clientProfile)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage qcloud-ckafka InstanceId")

    req = models.DescribeInstanceAttributesRequest()
    params = {
        "InstanceId": data[field_name]
    }
    req.from_json_string(json.dumps(params))

    resp = client.DescribeInstanceAttributes(req)

    data = json.loads(str(resp.Result))
    data["RegionId"] = region
    return data


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
