#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

import boto3


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_elasticache import Elasticache


def get(data, access_id, access_key, region):
    """
    输出 aws redis 的详情(json格式)
    """
    lib_client = Elasticache(access_id, access_key, region)

    client = boto3.client(
        "elasticache",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region,
    )

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field database aws-redis CacheClusterId"
    )

    response = client.describe_cache_clusters(
        CacheClusterId=data[field_name],
    )

    for cache_cluster in response["CacheClusters"]:
        if cache_cluster["CacheClusterId"] == data[field_name]:
            cache_cluster["Tag"] = lib_client.list_tag(cache_cluster["ARN"])
            return cache_cluster
    raise RuntimeError(f"根据 CacheClusterId {data[field_name]} 未找到 aws redis")


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == "__main__":
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise RuntimeError("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
