#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from huaweicloudsdkcore.auth.credentials import BasicCredentials
from huaweicloudsdkevs.v2.region.evs_region import EvsRegion
from huaweicloudsdkevs.v2 import *


def tag_delete(data, access_id, access_key, project_id, region):
    if project_id == "None":
        project_id = None
    credentials = BasicCredentials(access_id, access_key, project_id)

    client = EvsClient.new_builder() \
        .with_credentials(credentials) \
        .with_region(EvsRegion.value_of(region)) \
        .build()

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage huawei-ecs-volume id")

    request = BatchDeleteVolumeTagsRequest()
    request.volume_id = data[field_name]
    listTagsbody = [
        DeleteTagsOption(
            key=data["_control_"]["tag-delete"]["key"],
        )
    ]
    request.body = BatchDeleteVolumeTagsRequestBody(
        tags=listTagsbody,
        action="delete"
    )
    client.batch_delete_volume_tags(request)


def main(data, access_id, access_key, project_id, region):
    tag_delete(data, access_id, access_key, project_id, region)


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
