#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def get_data_list():
    """
        查询cvm实例的关闭模式
    """
    return [
        {
            "id": "HARD",
            "desc": "直接强制关闭"
        },
        {
            "id": "SOFT",
            "desc": "仅软关机"
        }
    ]


def main():
    data_list = get_data_list()
    for data in data_list:
        print(json.dumps(data))


if __name__ == '__main__':
    main()
