#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys


def ec2_describe_ebs_volume_max_iops(ebs_volume_type):
    """
        查询ebs指定volume类型支持的最大iops
    """

    if ebs_volume_type == "standard":
        return 100
    if ebs_volume_type == "io2": 
        return 64000
    elif ebs_volume_type == "io1": 
        return 64000
    elif ebs_volume_type == "gp3":
        return 16000
    elif ebs_volume_type == "gp2":
        return 16000
    elif ebs_volume_type == "st1":
        return 500
    elif ebs_volume_type == "sc1":
        return 250
    else:
        raise type('NotSupportedEbsVolumeType', (Exception,), {})(f"错误的 ebs_volume_type 类型: {ebs_volume_type}")


def main(params):
    data_volume_type = params["data_volume_type"]
    if data_volume_type is None:
        return

    data = ec2_describe_ebs_volume_max_iops(data_volume_type)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
