#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

import boto3


def describe_subnets(access_id, access_key, region, availability_zone, vpc_id):
    """
        查询子网列表
    """
    client = boto3.client(
        "ec2",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region
    )

    page_size = 100

    filter_list = [
        {
            "Name": "availability-zone",
            "Values": [availability_zone]
        },
        {
            "Name": "vpc-id",
            "Values": [vpc_id]
        }
    ]

    result = []
    response = client.describe_subnets(MaxResults=page_size, Filters=filter_list)
    result.extend(response["Subnets"])
    marker = response["NextToken"] if "NextToken" in response else ""
    while marker != "":
        response = client.describe_subnets(
            MaxResults=page_size, NextToken=marker, Filters=filter_list)
        result.extend(response["Subnets"])

        marker = response["NextToken"] if "NextToken" in response else ""
    for item in result:
        for tag in item["Tags"]:
            if tag["Key"] == "Name":
                item["Name"] = tag["Value"]
                break

    return result


def main(params):
    account = params["account"]
    region = params["region"]
    az = params["az"]
    vpc_id = params["vpc_id"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info aws {account}")
    )

    subnet_list = describe_subnets(
        key_info["access_id"], key_info["access_key"], region, az, vpc_id)
    for subnet in subnet_list:
        print(json.dumps(subnet, default=str))


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
