#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


def create_tt(params):
    content = params["content"]

    submit_user = params['submit_user'] if 'submit_user' in params else "sys@app"
    ext_tt = subprocess.getoutput("c3mc-sys-ctl sys.bpm.tt.type")

    resp = subprocess.run([
            "c3mc-create-ticket", 
            "--submit_user", submit_user, 
            "--title", params["title"], 
            "--ext_tt", ext_tt,
        ], 
        input=content.encode(), 
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if resp.returncode != 0:
        err = resp.stderr.decode('utf-8').rstrip()
        print(f"LOG. 创建tt出错: {err}", file=sys.stderr)
        exit(1)

    tt_number = resp.stdout.decode('utf-8').rstrip()

    print(f"LOG. tt单号: {tt_number}", flush=True)

    resp = subprocess.run([
        "c3mc-wait-ticket-status-change",
        "--number", tt_number,
        "--ext_tt", ext_tt,
        ], 
        input=content.encode(), 
        stdout=subprocess.PIPE,
    )
    if resp.returncode != 0:
        err = resp.stderr.decode('utf-8').rstrip()
        print(f"LOG. 等待tt结束出错: {err}")
        exit(1)

    tt_status_txt = resp.stdout.decode('utf-8').rstrip()
    print(f"LOG. tt结束, 单号: {tt_number}, 状态: {tt_status_txt}")


def main(params):
    create_tt(params)
    

if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')
    
    main(json.loads(l[0]))
