#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.auth.credentials import AccessKeyCredential
from aliyunsdkslb.request.v20140515.RemoveTagsRequest import RemoveTagsRequest


def tag_delete(data, access_id, access_key, region):
    credentials = AccessKeyCredential(
        access_id, access_key)
    client = AcsClient(region_id=region, credential=credentials)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field networking aliyun-slb LoadBalancerId")

    request = RemoveTagsRequest()
    request.set_accept_format('json')
    request.set_LoadBalancerId(data[field_name])
    request.set_Tags([
        {
            "TagKey": data["_control_"]["tag-delete"]["key"],
            "TagValue": data["_control_"]["tag-delete"]["value"]
        }
    ])
    client.do_action_with_exception(request)


def main(data, access_id, access_key, region):
    tag_delete(data, access_id, access_key, region)


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
