#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use POSIX;
use Logs;
use Time::Local;

$| ++;

=head1 SYNOPSIS

    'groupid' => '10',
    'path' => '/data/.gitreport.temp/10',
    'ticketid' => '',
    'id' => 7,
    'addr' => 'https://github.com/open-c3/test.git',
    'uuid' => 'e462f55943a0cd9afa7c71bc82cbc19b',
     date => '2021-04-04'

=cut

return sub
{
    my %param = @_;

    my ( $groupid, $path, $id, $addr, $uuid, $logs )
        = ( @param{qw( groupid path id addr uuid )}, Logs->new( 'gitreport.gitpull' ) );

    my $dir = "$path/data/$uuid";

    my @branch = `cd $dir && git branch`;
    chomp @branch;
    map{ $_ =~ s/^\**\s*// }@branch;

    if( $addr =~ /^git\@/ )
    {
        $addr =~ s/:/\//;
        $addr =~ s/^git\@/https:\/\//;
    }
    $addr =~ s/\.git$//;

    my ( $year, $month, $day ) = split /\-/, $param{date};
    
    my $time = timelocal(0,0,0,$day, $month-1, $year);
    my $since =  POSIX::strftime( "%Y-%m-%d", localtime($time - ( 86400 * 8 )) ) ;
    my $until =  POSIX::strftime( "%Y-%m-%d", localtime($time + ( 86400 * 2 )) ) ;

    my %date;
    map{
        my $t =  POSIX::strftime( "%Y-%m-%d", localtime($time - ( 86400 * $_ )) ) ;
        $date{$t} = 1;
    } 0 .. 6;

    my %data;
    for my $branch ( @branch )
    {
        my @x = `cd $dir && git checkout $branch && git log --pretty=format:"hash:%h user:%an time:%ad" --date=format:"%Y-%m-%d.%H%M%S" --since="$since" --until="$until" --shortstat`;
        chomp @x;

        my $lastuser = '';
        for my $info ( @x )
        {
            if( $info =~ /\d+\s+file[s]{0,1}\s+changed,/ )
            {
                my $uuid;
                if( $lastuser =~ /^hash:/ )
                {
                    my @m = $lastuser =~ /hash:(.+) user:(.+) time:(.+)/;
                    my @d = split /\./, $m[2];
                    next unless $date{$d[0]};
                    $uuid = $m[0];
                    $data{$uuid} = { user => $m[1], time => $m[2] };
                }

                $info =~ /\b(\d+)\s+insertion/;
                $data{$uuid}{add} = $info =~ /\b(\d+)\s+insertion/ ? $1 : 0;

                $data{$uuid}{del} = $info =~ /\b(\d+)\s+deletion/ ? $1 : 0;
                $data{$uuid}{path}{"$addr/commit/$uuid"} = 1;
            }
            else
            {
                $lastuser = $info;
            }
        }
    }
    return \%data;
}
