#!/bin/bash

set -o pipefail

accountfile=/data/Software/mydan/Connector/pp/cloud/extend-sync/vmware_esxi/account
test -f $accountfile || exit 0

cat $accountfile |xargs -i{} bash -c "c3mc-cloud-vmware-host {}"
