#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

use MYDan::Util::OptConf;

=head1 SYNOPSIS

 $0 --tree open-c3.ops --date 2024-05

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( tree=s date=s ) )->dump();

$option->assert() unless $o{tree};
$option->assert() unless $o{date} && $o{date} =~ /^\d+\-\d+$/;

my ( %uuid, %name );

sub getuuid
{
    my $type = shift @_;
    my @xx = `c3mc-device-data-get curr $type`;
    chomp @xx;
    for my $xx ( @xx )
    {
        my @x = split /\t/, $xx;
        my ( $uuid ,$tree,  $name) = @x;
        next unless $tree =~ /$o{tree}/;
        $name{$name} ++ if $name;
        $uuid{$uuid} ++ if $uuid;
    }
}

my @device = (
    'compute huawei-ecs uuid 服务树 名称',
    'storage huawei-ecs-volume uuid 服务树',
    'storage huawei-obs uuid 服务树 名称',
);

map{ getuuid($_) }@device;

my %data;
my $sum = 0;
for my $file ( glob "/data/open-c3-data/c3mc-device-fee/$o{date}/*.csv" )
{
    print "file: $file\n";

    my    @data  = `cat '$file'`;
    chomp @data;

    next unless @data > 1;

    my $title = shift @data;

    my @title = split /,/, $title;

    my @coluuid = ( "UUID", "资源ID" );
    my @colname = ( "NAME", "资源名称" );
    my @colcost = ( "Price", "Cost", "应付金额 (USD)" );

    my ( $coluuid ) = grep{ my $x = $_; grep{ $_ eq $x }@coluuid }@title;
    my ( $colname ) = grep{ my $x = $_; grep{ $_ eq $x }@colname }@title;
    my ( $colcost ) = grep{ my $x = $_; grep{ $_ eq $x }@colcost }@title;

    for my $data ( @data )
    {
         my @d = split /,/, $data;
         map{ $_ =~ s/^"// and $_ =~ s/"$// if $_ =~ /^"/ && $_ =~ /"$/ }@d;
         my %d = map{ $title[ $_ ] => $d[ $_ ] } 0 .. @title - 1;

        my @uuid = grep{ 0 == index( $d{$coluuid}, $_) }keys %uuid;
        my @name = grep{ 0 == index( $d{$colname}, $_) }keys %name;

        next unless @name || @uuid;

        printf "%s\n", join "\t", map{ $d{$_}//''}( $coluuid, $colname, $colcost );
        $sum += $d{$colcost};

    }
}

printf "sum: %0.2f\n", $sum;
