#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );
use Data::Dumper;

use Code;
use MYDan::Util::OptConf;

=head1 SYNOPSIS

 $0 [--envname foo] 

=cut
my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( envname=s ) )->dump();
$option->assert( 'envname' );

Code->new( 'Config' )->run( %o );
