#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.cvm.v20170312 import cvm_client, models


def get(account, instance_id, region):
    """
    直接从云端查询实例信息 
    """
    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info qcloud {account}")
    )

    cred = credential.Credential(key_info["access_id"], key_info["access_key"])
    httpProfile = HttpProfile()
    httpProfile.endpoint = "cvm.tencentcloudapi.com"

    clientProfile = ClientProfile()
    clientProfile.httpProfile = httpProfile
    client = cvm_client.CvmClient(cred, region, clientProfile)

    req = models.DescribeInstancesRequest()
    params = {
        "InstanceIds": [instance_id]
    }
    req.from_json_string(json.dumps(params))

    resp = client.DescribeInstances(req)
    return json.loads(resp.to_json_string())["InstanceSet"][0]


def main(account, instance_id, region):
    data = get(account, instance_id, region)
    print(json.dumps(data))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
