#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib
use strict;
use warnings;

$|++;

use MYDB;
use MYDan::Util::OptConf;

=head1 SYNOPSIS

 $0
 $0 --user user1 --code 123456

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get(   qw( user=s code=s ) )->dump();
        $option->assert(qw( user   code   ) );

my $db = MYDB->new( "/data/Software/mydan/Connector/conf/conn" );
my $x  = $db->query( "select type from openc3_connector_mfa where user='$o{user}'" );

unless( $x && @$x )
{
    print "nofind mfa config\n";
    exit;
}

my $type = $x->[0][0];
exec "c3mc-mfa-$type --user '$o{user}' --code '$o{code}'";
