#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use MYDB;
use FindBin qw( $RealBin );
use MYDan::Util::OptConf;
use YAML::XS;
use Encode;

=head1 SYNOPSIS

 echo 'project yaml' | $0

=cut

local $/ = undef;
my %project = %{ YAML::XS::Load( Encode::encode('utf8', <STDIN> ) ) };
local $/ = "\n";

my $ssh_key;

my ( $id, $ticketid, $addr ) = @project{qw( id ticketid addr )};
if( $ticketid )
{
    my $db = MYDB->new( "$RealBin/../conf/conn" );
    my $x = eval{ $db->query( "select ticket from openc3_ci_ticket where id='$ticketid' and type='SSHKey'" )};  
    die "get data from ticket fail:$@"  if $@;
    $ssh_key = $x->[0][0] if @$x;
}

my $ctrl = $ssh_key ? "$RealBin/../bin/git -i " . Temp->new( chmod => 0600 )->dump( $ssh_key ) : 'git';

my @list; eval{ alarm 10; @list = `$ctrl ls-remote --tags $addr`; alarm 0; };
chomp @list;
map{ print "$id $1\n" if $_ =~ /\w+\s+refs\/tags\/(.+)/ }grep{ $_ !~ /\^\{\}$/ }@list;
