#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use MYDB;
use FindBin qw( $RealBin );
use MYDan::Util::OptConf;
use YAML::XS;
use Encode;

=head1 SYNOPSIS

 $0 id1 id2 ... idn --set 'foo=123'

=cut

my $db = MYDB->new( "$RealBin/../conf/conn" );
my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( set=s ) )->dump();
$option->assert('set');

sub setProject
{
    my $id = shift;
    die "id err" unless $id =~ /^\d+$/;

    eval{ $db->execute( "update openc3_ci_project set $o{set} where id=$id" );};
    die "update database fail: $@" if $@;
    print "$id\n";
}

if( @ARGV )
{
    map{ setProject($_) }@ARGV;
}
else
{
    while(<STDIN>){ chomp; setProject($_); }
}
