#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use MYDB;
use FindBin qw( $RealBin );
use MYDan::Util::OptConf;
use YAML::XS;
use Encode;

=head1 SYNOPSIS

 echo 'project yaml' | $0

=cut

local $/ = undef;
my %project = %{ YAML::XS::Load( Encode::encode('utf8', <STDIN> ) ) };
local $/ = "\n";

my ( $username, $pass );

my ( $id, $ticketid, $addr ) = @project{qw( id ticketid addr )};
if( $ticketid )
{
    my $db = MYDB->new( "$RealBin/../conf/conn" );
    my $x = eval{ $db->query( "select ticket from openc3_ci_ticket where id='$ticketid' and type='UsernamePassword'" )};  
    die "get data from ticket fail:$@" if $@;
    ( $username, $pass ) = split /_:separator:_/, $x->[0][0] if @$x;
}

my $ctrl = $pass ? "svn --username '$username'  --password '" . $pass . "'" : 'svn';

my @list; eval{ alarm 10; @list = `$ctrl list $addr/tags/`; alarm 0; };
chomp @list;

my @tags;
map{ $_ =~ s/\/$//; push @tags, $_ if $_ =~ /^release/ }@list;
map{ print "$id $_\n" }grep{ $_ !~ /\^\{\}$/ }@tags;
