#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess
import time

from tencentcloud.cvm.v20170312 import models


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_qcloud_cvm import QcloudCvm
from c3mc_utils import bpm_merge_user_input_tags


class Cvm:
    def __init__(self, access_id, access_key, region, params):
        self.params = params
        self.lib_client = QcloudCvm(access_id, access_key, region)

    def get_bool_value(self, text_bool):
        return text_bool == "是"

    def get_request(self):
        req = models.RunInstancesRequest()

        hostname = f"{self.params['name_prefix']}{{R:{self.params['name_suffix_start_number']}}}"

        api_params = {
            "InstanceChargeType": self.params["instance_charge_type"],
            "Placement": {
                "Zone": self.params["zone"],
                "ProjectId": int(self.params["project_id"])
            },
            "InstanceType": self.params["instance_config"],
            "ImageId": self.params["image_id"],
            "SystemDisk": {
                "DiskType": self.params["system_disk_type"],
                "DiskSize": int(self.params["system_disk_size"])
            },
            "VirtualPrivateCloud": {
                "VpcId": self.params["vpc_id"],
                "SubnetId": self.params["subnet_id"]
            },
            "InternetAccessible": {
                "InternetChargeType": self.params["internet_charge_type"],
                "PublicIpAssigned": self.get_bool_value(self.params["if_need_public_ip"])
            },
            "InstanceCount": int(self.params["count"]),
            "InstanceName": hostname,
            "SecurityGroupIds": self.params["security_group_ids"].split(","),
            "EnhancedService": {
                "MonitorService": {
                    "Enabled": self.get_bool_value(self.params["enable_monitor"])
                }
            },
            "HostName": hostname,
            "DisableApiTermination": self.get_bool_value(self.params["disable_api_termination"]),
        }

        if "internet_max_bandwidth_out" in self.params:
            api_params["InternetAccessible"]["InternetMaxBandwidthOut"] = int(self.params["internet_max_bandwidth_out"])

        # 包年包月时，需要配置购买时长和自动续费方式
        if api_params["InstanceChargeType"] == "PREPAID":
            api_params["InstanceChargePrepaid"] = {
                "Period": int(self.params["instance_charge_count"]),
                "RenewFlag": self.params["renew_flag"]
            }

        cvm_tags = []
        if "tag" in self.params:
            tag_list = json.loads(self.params["tag"])
            if len(tag_list) > 0:
                api_params["TagSpecification"] = [
                    {
                        "ResourceType": "instance",
                        "Tags": []
                    }
                ]
                cvm_tags.extend(
                    {"Key": tag['key'], "Value": tag['value']} for tag in tag_list
                )
                api_params["TagSpecification"][0]["Tags"] = cvm_tags

        if self.params["if_need_data_volume"] == "是":
            api_params["DataDisks"] = [
                {
                    "DiskType": self.params["data_disk_type"],
                    "DiskSize": int(self.params["data_disk_size"]),
                    "Tag": cvm_tags
                }
            ]

        req.from_json_string(json.dumps(api_params))
        return req

    def wait_for_get_instance_info(self, instance_id, timeout=600):
        """
        获取实例uuid、内网ip、公网ip, 超时时间默认为10分钟
        """
        start_time = time.time()
        while True:
            instance_info = self.lib_client.show_cvm(instance_id)
            if instance_info['Uuid'] != "":
                private_ip = ""
                public_ip = ""

                if (
                    instance_info["PrivateIpAddresses"] is not None
                    and len(instance_info["PrivateIpAddresses"]) > 0
                ):
                    private_ip = instance_info["PrivateIpAddresses"][0]
                if (
                    instance_info["PublicIpAddresses"] is not None
                    and len(instance_info["PublicIpAddresses"]) > 0
                ):
                    public_ip = instance_info["PublicIpAddresses"][0]

                return instance_info['Uuid'], private_ip, public_ip
            if time.time() - start_time > timeout:
                return ""
            else:
                time.sleep(5)

    def create_cvm(self):

        self.params = bpm_merge_user_input_tags(
            instance_params=self.params,
            product_owner_key_name="product_owner_tag",
            owners_key_name="owners_tag",
            ops_owner_key_name="ops_owner_tag",
            department_key_name="department_tag",
            product_key_name="product_tag",
            tree_key_name="tree_tag",
        )

        req = self.get_request()
        print(f"创建cvm, 请求参数为: {req}")

        if subprocess.getoutput("c3mc-sys-ctl sys.bpm.fake.run") == "1":
            # bpm虚假运行
            print("创建cvm, 响应为: xxxxxx")
            print("LOG. instance_id:xxxxxx")
            print("VAR. instance_id:xxxxxx")
            print(f'VAR. extinstance_id:{self.params["account"]}.{self.params["region"]}.xxxxx')
        else:
            try:
                resp = self.lib_client.run_instances(req)

                # 添加换行符，防止创建多个实例时，不好区分日志 
                print(f"创建cvm, 响应为: {resp.to_json_string()}\n\n")

                for instance_id in resp.InstanceIdSet:
                    instance_uuid, private_ip, public_ip = self.wait_for_get_instance_info(instance_id)
                    if instance_uuid == "":
                        print(f"无法在10分钟内获取实例的uuid字段的有效值, instance_id: {instance_id}")

                    print(f"LOG. 腾讯云实例UUID: {instance_uuid}")
                    print(f"LOG. 腾讯云实例ID: {instance_id}")
                    print(f"LOG. 内网ip:    {private_ip}")
                    print(f"LOG. 公网ip:    {public_ip}")
                    print(f"VAR. instance_id:{instance_uuid}")
                    print(f'VAR. extinstance_id:{self.params["account"]}.{self.params["region"]}.{instance_uuid}')
            except Exception as e:
                print(f"创建腾讯云cvm出错, err: {e}", file=sys.stderr)
                exit(1)


def main(params):
    print(f"params = {json.dumps(params)}")

    account = params["account"]
    region = params["region"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info qcloud {account}")
    )
    Cvm(key_info["access_id"], key_info["access_key"], region, params).create_cvm()


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
