#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.cvm.v20170312 import cvm_client, models


class Images:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()
        self.page_number = 1
        self.page_size = 100

    def create_client(self):
        cred = credential.Credential(self.access_id, self.access_key)
        httpProfile = HttpProfile()
        httpProfile.endpoint = "cvm.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        return cvm_client.CvmClient(cred, self.region, clientProfile)
    
    def describe_images(self):
        req = models.DescribeImagesRequest()
        params = {
            "Filters": [
                {
                    "Name": "image-type",
                    "Values": [ "PRIVATE_IMAGE", "SHARED_IMAGE" ]
                }
            ],
            "Limit": self.page_size,
            "Offset": (self.page_number - 1) * self.page_size
        }
        req.from_json_string(json.dumps(params))
        return self.client.DescribeImages(req)
    
    def get_total_count(self):
        response_data = self.describe_images()
        return response_data.TotalCount

    def show(self):
        response_data = self.describe_images()
        data_list = response_data.ImageSet
        for item in data_list:
            print(item.to_json_string())

    def page(self):
        count = self.get_total_count()
        mod = count % self.page_size
        if mod:
            total_page_number = int(count / self.page_size) + 1
        else:
            total_page_number = int(count / self.page_size)

        for cur_page_number in range(1, total_page_number + 1):
            self.page_number = cur_page_number
            self.show()
    

def main(params):
    account = params["account"]
    region = params["region"]

    key_info = json.loads(subprocess.getoutput(
        "c3mc-get-account-info qcloud {}".format(account)))
    Images(key_info["access_id"], key_info["access_key"], region).page()


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]))

