#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def describe_internet_charge_type_list():
    """
        查询 网络计费类型 列表
    """
    return [
        {
            "id": "BANDWIDTH_PREPAID",
            "name": "预付费按带宽结算",
        },
        {
            "id": "TRAFFIC_POSTPAID_BY_HOUR",
            "name": "流量按小时后付费",
        },
        {
            "id": "BANDWIDTH_POSTPAID_BY_HOUR",
            "name": "带宽按小时后付费",
        },
        {
            "id": "BANDWIDTH_PACKAGE",
            "name": "带宽包用户",
        },
    ]


def main():
    data_list = describe_internet_charge_type_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
