#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def describe_instance_charge_type_list():
    """
        实例付费方式列表
    """
    return [
        {
            "id": "PREPAID",
            "name": "预付费",
        },
        {
            "id": "POSTPAID_BY_HOUR",
            "name": "按小时后付费",
        },
    ]


def main():
    data_list = describe_instance_charge_type_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
