#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def describe_renew_flag_list():
    return [
        {
            "id": "NOTIFY_AND_AUTO_RENEW",
            "name": "通知过期且自动续费"
        },
        {
            "id": "NOTIFY_AND_MANUAL_RENEW",
            "name": "通知过期不自动续费"
        },
        {
            "id": "DISABLE_NOTIFY_AND_MANUAL_RENEW",
            "name": "不通知过期不自动续费"
        },
    ]


def main():
    data_list = describe_renew_flag_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
