#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess
import operator

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.cvm.v20170312 import cvm_client, models


class Images:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()
        self.page_number = 1
        self.page_size = 100

    def create_client(self):
        cred = credential.Credential(self.access_id, self.access_key)
        httpProfile = HttpProfile()
        httpProfile.endpoint = "cvm.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        return cvm_client.CvmClient(cred, self.region, clientProfile)

    def describe_images(self):
        req = models.DescribeImagesRequest()
        params = {
            "Limit": self.page_size,
            "Offset": (self.page_number - 1) * self.page_size
        }
        req.from_json_string(json.dumps(params))
        return self.client.DescribeImages(req)

    def get_data(self):
        result = []
        while True:
            response_data = self.describe_images()
            data_list = response_data.ImageSet
            if len(data_list) == 0:
                break
            result.extend(data_list)
            self.page_number += 1
        result = [json.loads(item.to_json_string()) for item in result]
        result.sort(key=operator.itemgetter('ImageType')) 
        return result

    def show(self):
        data_list = self.get_data()
        for item in data_list:
            print(json.dumps(item, default=str))


def main(params):
    account = params["account"]
    region = params["region"]

    key_info = json.loads(subprocess.getoutput(
        "c3mc-get-account-info qcloud {}".format(account)))
    Images(key_info["access_id"], key_info["access_key"], region).show()


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]))
