#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_elasticache import Elasticache


def tag_delete(data, access_id, access_key, region):
    lib_client = Elasticache(access_id, access_key, region)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field database aws-redis ARN"
    )

    need_delete_key_set = set()
    for item in data["_control_"]["tag-delete"]["tags"].split(","):
        parts = item.split("=")
        if len(parts) != 2:
            continue
        need_delete_key_set.add(parts[0])

    lib_client.remove_tags(data[field_name], list(need_delete_key_set))


def main(data, access_id, access_key, region):
    tag_delete(data, access_id, access_key, region)


if __name__ == "__main__":
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise RuntimeError("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
