#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use POSIX;
use Logs;
use FindBin qw( $RealBin );
use Temp;
use MIME::Base64;
use Code;

$| ++;

=head1 SYNOPSIS

    db => $mysql,
    logs => 日志对象

    # projectid addr ticketid rely name(版本信息可能为空) temp(logs目录下的临时目录名) uuid

=cut

return sub
{
    my %param = @_;

    my ( $db, $logs, $projectid, $addr, $ticketid, $rely, $name, $temp, $uuid )
        = @param{qw(db logs projectid addr ticketid rely name temp uuid )};

    $logs = Logs->new( 'code.build.dump.pull.rsync' ) unless $logs;

    my $temppath = "$RealBin/../logs/$temp/$uuid";
    if( -d $temppath )
    {
        my $user = `id -un`;chop $user;
        my $sudo = $user eq 'root' ? '' : 'sudo ';
        $logs->die( "clean old temppath fail:$!" ) if system "${sudo}rm -rf '$temppath'";
    }

    $logs->die( "mkdir temppath fail:$!" ) if system "mkdir -p '$temppath'";

    $logs->die( "name format error" ) unless $name =~ /^[a-zA-Z0-9\.\-_]+$/;
    my $version  = $name;

    $logs->die( "addr format error" ) unless $addr =~ /^rsync:(\d+)$/;
    my $fromrsyncid = $1;

    my $file = "/data/open-c3-data/pkgrsync/repo/$fromrsyncid\@$name";
    die "nofind repo/$fromrsyncid\@$name" unless -f $file;

    my $tagger = `cat '/data/open-c3-data/pkgrsync/mail/$fromrsyncid\@$name'`;
    my $tag_info = '';
        
    unless( defined $tagger && $tagger =~ /^[a-zA-Z0-9\.\@\-_]+$/ )
    {
        my $cidefaulttagger = `c3mc-sys-ctl cidefaulttagger`;
        chomp $cidefaulttagger;
        print "get tagger fail,Switch to default: $cidefaulttagger\n";
        $tagger = $cidefaulttagger;
    }

    $logs->die( "get data error:$!" ) if system "cd '$temppath' && rm -rf data info && mkdir -p info data && tar -zxvf '$file' -C data && echo '$version' > info/version";
    $logs->die( "write tagger info fail:$!" )if system "echo '$tagger' > '$temppath/info/tagger'";
    $logs->die( "write tag_info info fail:$!" )if system "echo '$tag_info' > '$temppath/info/taginfo'";

    eval{ $db->execute( "update openc3_ci_version set tagger='$tagger',taginfo='$tag_info' where projectid='$projectid' and name='$name'" ) };
    print "WARN: error recording tagger $@\n" if $@;
}
