#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;
use JSON;

$|++;

=head1 SYNOPSIS

 $0

=cut

my @x = `c3mc-device-data-get curr others k8s-service spec.type spec.loadBalancerIP spec.ports.0.port 集群名称 命名空间 名称 spec.ports.0.targetPort _pods_`;
chomp @x;

for( @x )
{
    my ( $type, $ip, $lport, $clustername, $namespace, $name, $port, $pods ) = split /\t/, $_;
    if( $pods && $type eq 'LoadBalancer' )
    {
        map{ printf "%s\n", join ' ', "$ip\{Port:$lport\}", $clustername,$namespace, $name,':::', $port, $pods, $_ }
            map{ my @x = split /:/, $_; $x[0] }split /,/, $pods;
    }
}
