#!/data/mydan/perl/bin/perl
use strict;
use warnings;
use YAML::XS;
use Digest::MD5;
use MYDan::Util::File;

local $/ = undef;
my %param = %{ YAML::XS::Load( <STDIN> ) };
local $/ = "\n";

my ( $md5, $serverip ) = @{$param{argv}};
my $idie = sub{ print shift;exit 1; };

my $datapath = "/data/mydan/var/run/filecache";

&$idie( "no data path: $datapath" ) unless -d $datapath;

chdir $datapath or &$idie( "chdir to data path fail" );

if( -f $md5 )
{
    print "tsunamiudp cached";
    exit;
}

#timeout
system "/data/tsunami-udp/client/tsunami connect $serverip get x.$md5 quit";

open my $fh, "<x.$md5" or die "open file fail: $!";
my $tempmd5 = Digest::MD5->new()->addfile( $fh )->hexdigest;
close $fh;

&$idie( "data md5 not match" ) unless $md5 eq $tempmd5;

system "mv x.$md5 $md5";
if( -f $md5 )
{
    print "tsunamiudp cached";
    exit 0;
}

exit 1;
