#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOBX/lib -I/data/Software/mydan/JOBX/private/lib
use strict;
use warnings;
use POSIX;

$|++;

my $myname = `cat /etc/jobx.myip`;
chomp $myname if $myname;
 
die "get slave name fail" unless $myname && $myname =~ /^[a-zA-Z0-9\.\-]+$/;
print $myname;
