#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.mongodb.v20190725 import mongodb_client, models


def get(data, access_id, access_key, region):
    """
        输出 qcloud mongodb 的详情(json格式)
    """
    cred = credential.Credential(access_id, access_key)
    httpProfile = HttpProfile()
    httpProfile.endpoint = "mongodb.tencentcloudapi.com"

    clientProfile = ClientProfile()
    clientProfile.httpProfile = httpProfile
    client = mongodb_client.MongodbClient(cred, region, clientProfile)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field database qcloud-mongodb InstanceId")

    req = models.DescribeDBInstancesRequest()
    params = {
        "InstanceIds": [data[field_name]]
    }
    req.from_json_string(json.dumps(params))

    resp = client.DescribeDBInstances(req)
    for instance in resp.InstanceDetails:
        if instance.InstanceId == data[field_name]:
            item = json.loads(str(instance))
            item["IP"] = item["Vip"].split(";")[0]
            return item
    raise Exception(
        "根据 InstanceId {} 未找到 qcloud mongodb".format(data[field_name]))


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
