#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.mongodb.v20190725 import mongodb_client, models


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_qcloud_mongodb import MongodbInfo


def describe_db_instance_node_property(access_id, access_key, region, instance_id):
    return MongodbInfo(
        access_id, access_key, region
    ).describe_db_instance_node_property(instance_id)


def get(data, access_id, access_key, region):
    """
    输出 qcloud mongodb 的详情(json格式)
    """
    cred = credential.Credential(access_id, access_key)
    httpProfile = HttpProfile()
    httpProfile.endpoint = "mongodb.tencentcloudapi.com"

    clientProfile = ClientProfile()
    clientProfile.httpProfile = httpProfile
    client = mongodb_client.MongodbClient(cred, region, clientProfile)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field database qcloud-mongodb InstanceId"
    )

    req = models.DescribeDBInstancesRequest()
    params = {"InstanceIds": [data[field_name]]}
    req.from_json_string(json.dumps(params))

    resp = client.DescribeDBInstances(req)
    for instance in resp.InstanceDetails:
        if instance.InstanceId == data[field_name]:
            item = json.loads(str(instance))
            item["IP"] = item["Vip"].split(";")[0]

            node_property_info = describe_db_instance_node_property(
                access_id, access_key, region, item["InstanceId"]
            )
            item["NodeNum"] = len(
                json.loads(node_property_info.to_json_string())["ReplicateSets"][0][
                    "Nodes"
                ]
            )

            return item
    raise RuntimeError(f"根据 InstanceId {data[field_name]} 未找到 qcloud mongodb")


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == "__main__":
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise RuntimeError("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
