#!# perl: code/ssoconfig
use strict;
use warnings;
use YAML::XS;

my $config;
BEGIN{
    use Config;
    $config = Config::config();
    map{ die "$_ undefind on config.inix" unless $config->{$_} }qw( ssocallback cookiekey );
};

return sub
{
    return $config;
};

