#!# perl: code/ssoconfig
use strict;
use warnings;
use YAML::XS;

my $config;
BEGIN{
    $config = eval{ YAML::XS::LoadFile '/data/Software/mydan/Connector/config.inix' };
    die "load config.ini fail: $@" if $@;
    map{ die "$_ undefind on config.inix" unless $config->{$_} }qw( ssocallback cookiekey );
};


return sub
{
    return $config;
};

