#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;
use JSON;
use Encode;
use YAML::XS;

binmode STDIN,  ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use MYDan::Util::OptConf;

=head1 SYNOPSIS

 echo data| $0 --file /debug/control/file.yml

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get(    qw( file=s ) )->dump();
        $option->assert( qw( file   ) );

die "nofile: $o{file}" unless -f $o{file};

my $control = eval{ YAML::XS::LoadFile $o{file}; };
die "load control file fail: $@" if $@;

for my $x ( <STDIN> )
{
    my $d = eval{ JSON::decode_json Encode::encode( 'utf8', $x ) };
    die "decode json fail: $@" if $@;
    $d->{_control_} = $control;
    my $v = eval{ Encode::decode( 'utf8', JSON::encode_json $d ) };
    die "encode json fail:$@" if $@;
    printf "$v\n";
}
