#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json


def delete_field(data_list, target_field):
    """
        删除json中的target_field字段
    """
    result = []
    for data in data_list:
        data.pop(target_field, None)
        result.append(data)
    return result


def main(data_list, target_field):
    result = delete_field(data_list, target_field)
    for data in result:
        print(json.dumps(data, default=str))


if __name__ == '__main__':
    data_list = []
    for line in sys.stdin:
        data_list.append(json.loads(line))
    main(data_list, sys.argv[1])
