#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json


def convert_obj_to_array(data_list, target_field):
    """
        把json中 target_field(哈希类型) 字段转换为数组类型, 
        如果不存在 target_field 字段则不做任何处理并返回原数据。

        比如:
        {
            ...
            "flavor": {
                "id": "s6.xlarge.2",
                "name": "s6.xlarge.2",
            }
            ...
        }
        将被转换为:
        {
            ...
            "flavor": [
                {
                    "key": "id",
                    "value": "s6.xlarge.2"
                },
                {
                    "key": "name",
                    "value": "s6.xlarge.2"
                }
            ]
            ...
        }
    """
    result = []
    for data in data_list:
        if target_field not in data:
            result.append(data)
            continue
        if type(data[target_field]) is not dict:
            result.append(data)
            continue

        d = data[target_field]
        data[target_field] = []
        for key, value in d.items():
            data[target_field].append({
                "key": key,
                "value": value
            })
        result.append(data)
    return result


def main(data_list, target_field):
    result = convert_obj_to_array(data_list, target_field)
    for data in result:
        print(json.dumps(data, default=str))


if __name__ == '__main__':
    data_list = []
    for line in sys.stdin:
        data_list.append(json.loads(line))
    main(data_list, sys.argv[1])
