#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import yaml
import sys
from pathlib import Path


def get_uuid_field_name(resource_type, resource_sub_type):
    """
        查询uuid字段的列名称

        resource_type, 比如 networking
        resource_sub_type, 比如 aws-alb
    """
    colmap_path = "/data/open-c3-data/device/curr/{}/{}/colmap.yml".format(
        resource_type, resource_sub_type)
    conf = yaml.safe_load(Path(colmap_path).read_text())
    return conf["uuid"]


def main(resource_type, resource_sub_type):
    data = get_uuid_field_name(resource_type, resource_sub_type)
    print(data)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
