#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from huaweicloudsdkcore.auth.credentials import BasicCredentials
from huaweicloudsdkdds.v3.region.dds_region import DdsRegion
from huaweicloudsdkdds.v3 import *


def tag_delete(data, access_id, access_key, project_id, region):
    if project_id == "None":
        project_id = None
    credentials = BasicCredentials(access_id, access_key, project_id)

    client = DdsClient.new_builder() \
        .with_credentials(credentials) \
        .with_region(DdsRegion.value_of(region)) \
        .build()

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field database huawei-dds id")

    request = BatchTagActionRequest()
    request.instance_id = data[field_name]
    listTagsbody = [
        TagItem(
            key=data["_control_"]["tag-delete"]["key"],
            value=data["_control_"]["tag-delete"]["value"]
        )
    ]
    request.body = BatchOperateInstanceTagRequestBody(
        tags=listTagsbody,
        action="delete"
    )
    client.batch_tag_action(request)


def main(data, access_id, access_key, project_id, region):
    tag_delete(data, access_id, access_key, project_id, region)


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
