#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib
use strict;
use warnings;

$|++;

use MYDB;
use MYDan::Util::OptConf;
use YAML::XS;

=head1 SYNOPSIS

 $0 --write user1 user2 .. usern
 $0 --write user1 user2 .. usern --caseuuid xxx.xxx.xxx
 $0 --clean user1 user2 .. usern
 $0 --cleancase xxx.xxx.xxx1 xxx.xxx.xxx2 .. xxx.xxx.xxxn

=cut

my $option = MYDan::Util::OptConf->load();
my %o      = $option->set( caseuuid => 'x' )->get( qw( write clean caseuuid=s cleancase ) )->dump();

my @argv = @ARGV;
$option->assert() unless ( $o{write} || $o{clean} || $o{cleancase} ) && @argv;

my $db = MYDB->new( "/data/Software/mydan/AGENT/conf/conn" );

if( $o{write} )
{
    my $time = time;
    map{
        eval{$db->execute( "insert into openc3_monitor_serialcall_data(`user`,`time`,`caseuuid`) value('$_','$time','$o{caseuuid}')" ); };
    }@argv;
}

if( $o{clean} )
{
    my $time = time;
    map{
        eval{$db->execute( "delete from openc3_monitor_serialcall_data where user='$_'" ); };
    }@argv;
}

if( $o{cleancase} )
{
    my $time = time;
    map{
        eval{$db->execute( "delete from openc3_monitor_serialcall_data where caseuuid='$_'" ); };
    }@argv;
}
