#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use YAML::XS;
use uuid;

=head1 SYNOPSIS

 $0

=cut

print "reload connector\n";
my $base = $RealBin;
$base =~ s#/[^/]+$##;

die if system "$RealBin/../pp/c3mc-install";

my $Config = eval{ YAML::XS::LoadFile "$RealBin/../config/Config";};
die "load Config fail: $!" unless $Config;

my $envname = `cat $RealBin/../conf/envname`;
chomp $envname;

die "envname undef"                    unless $envname;
die "envname $envname undef in Config" unless $Config = $Config->{$envname};
die "port undef"                       unless my $port = $Config->{port};

my $tokenfile = "/etc/openc3.reload.token";
unless( -f $tokenfile )
{
    my $uuid = uuid->new()->create_str;
    system "echo $uuid > $tokenfile";
}

my $token = `cat $tokenfile 2>/dev/null`; chomp $token;

for my $type ( qw( api ) )
{
    for my $port ( $port->{$type}{from} .. $port->{$type}{to} )
    {
        system "c3mc-nginx-reload --off $port --reload --after";
        my $oldpid = `/usr/sbin/lsof -i:$port|tail -n 1|awk '{print \$2}'`;
        chomp $oldpid;

        system "curl -H 'token:$token' localhost:$port/reload 2>/dev/null";

        my $newpid;
        for my $index ( 1 .. 30 )
        {
            system "$base/tools/restart $port" if $index == 20;
            print "check api ...\n";
            $newpid = `/usr/sbin/lsof -i:$port|tail -n 1|awk '{print \$2}'`;
            if( $newpid )
            {
                chomp $newpid;
                last;
            }
            else
            {
                die "reload port $port fail.\n" if $index == 30;
                sleep 1;
            }
        }

        print "reload $type port: $port old pid: $oldpid new pid: $newpid\n";
        die "same pid.\n" if $oldpid && $newpid && $oldpid eq $newpid;

        system "c3mc-nginx-reload --on $port --reload";
    }
}

sub get_gunicorn_pid
{
    my $port = shift @_;
    my @x = `ps -ef|grep gunicorn|grep -v grep|grep :$port |awk '{print \$2, \$3}'`;
    chomp @x;
    my %pid;
    for( @x )
    {
        my ( $pid, $ppid ) = split /\s+/, $_;
        $pid{$pid} = $ppid;
    }

    my %tmp = map{ $_=> 1 }keys %pid;
    map{ $tmp{$_} ++ if $tmp{$_} }values %pid;

    my ( $masterpid ) = grep{ $tmp{$_} > 1 }keys %tmp;
    my @workerpid = grep{  $_ ne $masterpid }keys %pid;

    return $masterpid, \@workerpid;
}

for my $type ( qw( api ) )
{
    for my $port ( 7998 .. 7999 )
    {
        system "c3mc-nginx-reload --off $port --reload --after";

        my ( $masterpid, $workerpid ) = get_gunicorn_pid( $port );

        unless( $masterpid )
        {
            warn "nofind master pid, restart api\n";
            system "$base/tools/restart $port";
            sleep 5;
            ( $masterpid, $workerpid ) = get_gunicorn_pid( $port );
        }

        unless( $masterpid )
        {
             warn "nofind master pid\n";
             next;
        }


        if ( kill( 'HUP', $masterpid ) )
        {
            print "sent HUP to master pid $masterpid\n";
        } else {
            die "sent HUP fail: $!\n";
        }

        my $newworkerpid;

        for my $index ( 1 .. 30 )
        {
            system "$base/tools/restart $port" if $index == 20;
            print "check api ...\n";
            ( undef, $newworkerpid ) = get_gunicorn_pid( $port );
            my @x = ( @$workerpid, @$newworkerpid );
            my %x; map{ $x{$_}++ }@x;
            if( scalar( @x ) == scalar( grep{ $x{$_} eq 1 }keys %x) )
            {
                last;
            }
            else
            {
                die "reload port $port fail.\n" if $index == 30;
                sleep 1;
            }
        }

        printf "old worker pid: %s\n", join ',', @$workerpid;
        printf "new worker pid: %s\n", join ',', @$newworkerpid;

        my @x = ( @$workerpid, @$newworkerpid );
        my %x;
        map{ $x{$_}++ }@x;
        die "find same worker pid" if grep{ $x{$_} > 1 }keys %x;

        system "c3mc-nginx-reload --on $port --reload";
    }
}

system "c3mc-nginx-reload --reset --reload";

my $mymarkfile = '/etc/connector.mark';
my $user = `id -un`;chop $user;
my $sudo = $user eq 'root' ? '' : 'sudo ';

die "set connector.mark fail:$!" if system( "${sudo}sh -c 'date > $mymarkfile'" );

system "$base/tools/restart trouble-ticketing";
