#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

import boto3


def get(data, access_id, access_key, region):
    """
        输出 aws ec2 volume 的详情(json格式)
    """
    client = boto3.client(
        "ec2",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region,
    )

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage aws-ec2-volume VolumeId")

    response = client.describe_volumes(
        VolumeIds=[data[field_name]],
    )

    for volume in response["Volumes"]:
        if volume["VolumeId"] == data[field_name]:
            return volume
    raise Exception(
        "根据 VolumeId {} 未找到 aws ec2 volume".format(data[field_name]))


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
