#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;

use YAML::XS;
use POSIX;
use Encode;
use JSON;
use utf8;

$| ++;

local $/ = undef;
my $data = JSON::from_json( Encode::encode('utf8', <STDIN> ) );
local $/ = "\n";

die "node data" unless $data;
map { $data->{$_} = Encode::decode( 'utf8', $data->{$_} ) }keys %$data;
my ( $cluster ) = @$data{qw( cluster )};

die "nofind cluster" unless $cluster && $cluster =~ /^\d+$/;

my $kubectl = `c3mc-k8s-kubectl-get -i $cluster`;
die "get kubectl fail: $!" if $?;
chomp $kubectl;

system "$kubectl get ns|awk '{print \$1}'|sed 1d";
