#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$| ++;

my @x = `cd /data/Software/mydan/Connector/pp/bpm/action/kubernetes-apply/template && ls`;
chomp @x;
map{ print "$_\n"; }sort @x;
