#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import subprocess
import json
import requests
from urllib.parse import urljoin
import sys


def main(username, email):
    proxy_addr_list = subprocess.getoutput("c3mc-sys-ctl sys.bl.sync.qizhi.proxy_addr_list").strip().split(",")
    app_name = subprocess.getoutput("c3mc-sys-ctl sys.bl.sync.app_name").strip()
    app_key = subprocess.getoutput("c3mc-sys-ctl sys.bl.sync.app_key").strip()

    request_data = {
        "command": "add-qizhi-bastion-user",
        "arguments": json.dumps(
            {
                "username": username,
                "email": email,
            }
        ),
    }

    api_addr = urljoin(proxy_addr_list[0], "/run")

    headers = {
        'Content-Type': 'application/json'
    }
    if app_name != "":
        headers["app_name"] = app_name
    if app_key != "":
        headers["app_key"] = app_key

    response = requests.request("POST", api_addr, headers=headers, data=json.dumps(request_data), timeout=1800)
    print(json.dumps(response.json()))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
