#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import os
import json
import subprocess


def main():
    bl_mode = subprocess.getoutput("c3mc-sys-ctl sys.bl.mode").strip()
    if bl_mode == '':
        return

    sys_args = json.loads(subprocess.getoutput("c3mc-sys-ctl | yaml2json"))

    args = "".join(
        f'-{name.split(".")[-1]} {sys_args[name]} '
        for name in sys_args
        if name.startswith(f"sys.bl.sync.{bl_mode}")
    )
    app_key = os.getenv("OPEN_C3_RANDOM")

    command = f"/data/Software/mydan/Connector/bl/sync/{bl_mode}/{bl_mode}"

    os.system(f"{command} {args} -appname job -appkey {app_key}")
    

if __name__ == '__main__':
    main()
