#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOBX/lib -I/data/Software/mydan/JOBX/private/lib
use strict;
use warnings;

$| ++;

=head1 SYNOPSIS

    id => 1,

=cut

return sub
{
    my ( %param, @list )= @_;

    die "id not a number" unless $param{id} =~ /^\d+$/;

    my $i = 1;
    my @x = `c3mc-base-fullnodeinfo --col id,name,type,inip,exip $param{id}`;
    chomp @x;
    for( @x )
    {
        my @t = split /;/, $_;
        push @list, +{ id => $i++, name => $t[1], type => $t[2], inip => $t[3], exip => $t[4] };
    }

    return @list;
}
