#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use Code;

=head1 SYNOPSIS

 $0 

=cut

my $db = MYDB->new( "$RealBin/../conf/conn" );

$0 = 'job_server_clean';
Code->new( 'server/clean' )->run( db => $db );
