#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib

=head1 SYNOPSIS

 $0 [--port num]

=cut
use strict;
use warnings;

use Gateway;
use MYDan::Util::OptConf;

$| ++;

my $option = MYDan::Util::OptConf->load();
my %o = $option->set( port => 9999 )->get( qw( port=i ) )->dump();

my %server = (
    "localhost:8031" => 1,
    "localhost:8032" => 1,
    "localhost:8033" => 1,
    "localhost:8034" => 1,

    "localhost:8035" => 0,
    "localhost:8036" => 0,
    "localhost:8037" => 0,
    "localhost:8038" => 0,
    "localhost:8039" => 0,
    "localhost:8040" => 0,
    "localhost:8041" => 0,
    "localhost:8042" => 0,
    "localhost:8043" => 0,
    "localhost:8044" => 0,
    "localhost:8045" => 0,


    "localhost:8011" => 2,
    "localhost:8012" => 2,
    "localhost:8013" => 2,
    "localhost:8014" => 2,
    "localhost:8015" => 2,
    "localhost:8016" => 2,
    "localhost:8017" => 2,
    "localhost:8018" => 2,
);

Gateway->new( %o, server => \%server )->run();
