#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib

=head1 SYNOPSIS

 $0 [--port num]

=cut
use strict;
use warnings;

use Gateway;
use MYDan::Util::OptConf;

$| ++;

my $option = MYDan::Util::OptConf->load();
my %o = $option->set( port => 9999 )->get( qw( port=i ) )->dump();

my %server; 

for my $t ( qw( Connector JOB JOBX CI AGENT ) )
{
    my $c = YAML::XS::LoadFile "/data/Software/mydan/$t/config/Config";
    my $api = $c->{test}{port}{api};
    map{ $server{"localhost:$_"} = $t }$api->{from} .. $api->{to};

    if( $t eq 'Connector' )
    {
        my $i = 0;
        for ( sort $api->{from} .. $api->{to} )
        {
            last if $i ++ >= 4;
            $server{"localhost:$_"} = "$t.internal"
        }
    }
}

Gateway->new( %o, server => \%server )->run();
