#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.cbs.v20170312 import cbs_client, models


def get(data, access_id, access_key, region):
    """
        输出 qcloud cbs 的详情(json格式)
    """
    cred = credential.Credential(access_id, access_key)
    httpProfile = HttpProfile()
    httpProfile.endpoint = "cbs.tencentcloudapi.com"

    clientProfile = ClientProfile()
    clientProfile.httpProfile = httpProfile
    client = cbs_client.CbsClient(cred, region, clientProfile)

    id_field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage qcloud-cvm-volume DiskId")
    zone_id_field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage qcloud-cvm-volume ZoneId")
    account_field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage qcloud-cvm-volume account")
    accountuuid_field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage qcloud-cvm-volume accountuuid")

    req = models.DescribeDisksRequest()
    params = {
        "DiskIds": [data[id_field_name]]
    }
    req.from_json_string(json.dumps(params))

    resp = client.DescribeDisks(req)
    for disk in resp.DiskSet:
        if disk.DiskId == data[id_field_name]:
            item = json.loads(str(disk))
            item["RegionId"] = region
            item["ZoneId"] = data[zone_id_field_name]
            item["account"] = data[account_field_name]
            item["accountuuid"] = data[accountuuid_field_name]
            item["_vmuuid_"] = data["_vmuuid_"]
            return item
    raise Exception(
        "根据 DiskId {} 未找到 qcloud cbs".format(data[id_field_name]))


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
