#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use Code;

=head1 SYNOPSIS

 $0 [--name name]  # user name
    [--ip ip] 


=cut
my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( name=s ip=s ) )->dump();
$option->assert( qw( name ip ));

my $db = MYDB->new( "$RealBin/../conf/conn" );
my $node = Code->new( 'checkcreateip' )->run( db => $db, %o );
if ($node) {
	print "11\n";
} else {
	print "22\n";
}
