#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );
use Data::Dumper;

use MYDan::Util::OptConf;
use Code;

=head1 SYNOPSIS

 $0 [--code test/abc]

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( code=s ) )->dump();
$option->assert( qw( code ) );

Code->new( $o{code} );
