#!/usr/bin/env perl
use strict;
use warnings;

binmode STDIN,  ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

die "no cmd" unless my $cmd = join " ", @ARGV;
my $file = ( split /\s/, $cmd )[0];

my $uuid = time;
my $path = "/data/open-c3-data/devel/pd/$uuid";
system "mkdir -p $path";

print "path: $path\n";

system "docker exec openc3-server bash -c \"export NYTPROF=addpid=1:file=$path/nytprof.out && cd $path && PERL5OPT=-d:NYTProf $cmd\"";

my    @file = `cd $path && ls nytprof.out.*`;
chomp @file;
my $opt = join " ",  @file;

system "docker exec openc3-server bash -c \"cd $path && /data/Software/mydan/perl/bin/nytprofmerge $opt -o nytprof.out\"";
system "docker exec openc3-server bash -c \"cd $path && /data/Software/mydan/perl/bin/nytprofhtml -f nytprof.out\"";

chdir "$path/nytprof" or die "chdir fail";
system "python -m SimpleHTTPServer";
