#!/usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import sys
import datetime
import hashlib
import requests
import random
import string
import json
import hmac
import os
reload(sys)
sys.setdefaultencoding('utf-8')

def dnionPush():
    push_states = {}
    parser = argparse.ArgumentParser()
    parser.add_argument("file", help="文件名")
    parser.add_argument("domain", help="域名")
    parser.add_argument('-f', '--file', help="文件", action="store_true")
    parser.add_argument('-d', '--domain', help="域名", action="store_true")
    args = parser.parse_args()
    
    with open(args.file) as f:
        for i in f:
            push_data = i.strip().split(':')
            if push_data[0] in push_states:
                url = 'http://' + args.domain + '/' + push_data[1]
                push_states[push_data[0]].append(url)
            else:
                push_states[push_data[0]] = []
                url = 'http://' + args.domain + '/' + push_data[1]
                push_states[push_data[0]].append(url)
    print push_states
    for k, v in push_states.items():
        a = duion(k, v)
        if a != 0:
            return 1
    return 0

def duion(push_type, push_uri):
    limit = 100
    url = []
    for u in push_uri:
        url.append(u)
        if limit == len(url):
            a = _cdn(push_type, url)
            if a != 0:
                return 1
            url = []
    if len(url):
        a = _cdn(push_type, url)
        if a != 0:
            return 1
    return 0

def _cdn(push_type, push_uri):
    if push_type == 'f':
        a = __cdn( push_uri, [] )
        return a
    if push_type == 'd':
        a = __cdn( [], push_uri )
        return a
    return 1

def __cdn(url,dir):
    """ 帝联 """
    flashApi = "http://push.dnion.com/cdnUrlPush.do"
    params = {}
    params["username"] = os.getenv('openc3_cdnrefresh_dnion_username')
    params["password"] = os.getenv('openc3_cdnrefresh_dnion_password')
    try:
        if len(url) > 0:
                params["type"] = 1
                params["url"] = ",".join(url)
                resp = requests.get(flashApi, params=params)
                # logging.debug("帝联CDN刷新url结束,状态码:%s, 返回体:%s", resp.status_code,resp.content)
                if resp.status_code==200:
                    print 'ok'
                else:
                    return 1

        if len(dir) > 0:
                params["type"] = 0
                params["url"] = ",".join(dir)
                resp = requests.get(flashApi, params=params)
                # logging.debug("帝联CDN刷新目录结束,状态码:%s, 返回体:%s", resp.status_code,resp.content)
                if resp.status_code==200:
                    print 'ok'
                else:
                    return 1
                    
    except Exception,e:
        print e
        return 1
    return 0

if __name__ == '__main__':
    try:
        if dnionPush() == 0:
            sys.exit(0)
        else:
            sys.exit(1)
    except Exception as e:
        sys.exit(1)
