// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/person/create": {
            "post": {
                "description": "创建运维人员预配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "运维预配置"
                ],
                "summary": "创建运维人员预配置",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreatePersonParamsArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/person/create/by_copy": {
            "post": {
                "description": "通过复制账号创建运维人员预配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "运维预配置"
                ],
                "summary": "通过复制账号创建运维人员预配置",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreatePersonParamsByCopyArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/person/delete/:id": {
            "delete": {
                "description": "根据TargetUser的id删除指定的账号",
                "tags": [
                    "运维预配置"
                ],
                "summary": "根据TargetUser的id删除指定的账号",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/person/list": {
            "get": {
                "description": "获取所有运维人员预配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "运维预配置"
                ],
                "summary": "获取所有运维人员预配置",
                "responses": {}
            }
        },
        "/person/update": {
            "post": {
                "description": "更新运维预配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "运维预配置"
                ],
                "summary": "更新运维预配置",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PersonPreConfigParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/statistics/get_todo_tts": {
            "get": {
                "description": "获取待办tt列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tt统计"
                ],
                "summary": "获取待办tt列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "起始时间戳. 秒数",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "结束时间戳. 秒数",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "是否获取所有待办. 1: 获取所有待办;  0: 获取个人待办",
                        "name": "all",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Ticket"
                            }
                        }
                    }
                }
            }
        },
        "/statistics/get_tts": {
            "get": {
                "description": "获取tt列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tt统计"
                ],
                "summary": "获取tt列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "起始时间戳. 秒数",
                        "name": "start",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "结束时间戳. 秒数",
                        "name": "end",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Ticket"
                            }
                        }
                    }
                }
            }
        },
        "/statistics/get_user_accounts": {
            "get": {
                "description": "获取所有运维人员预配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tt统计"
                ],
                "summary": "获取所有运维人员预配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "起始时间戳. 秒数",
                        "name": "start",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "结束时间戳. 秒数",
                        "name": "end",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/statistics/work_order_summary": {
            "get": {
                "description": "获取工单按类别统计",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tt统计"
                ],
                "summary": "获取工单按类别统计",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "起始时间戳. 秒数",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "结束时间戳. 秒数",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/statistics/work_order_summary/by_apply_user": {
            "get": {
                "description": "获取工单按申请人统计(只返回前10)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tt统计"
                ],
                "summary": "获取工单按申请人统计(只返回前10)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "起始时间戳. 秒数",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "结束时间戳. 秒数",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/statistics/work_order_summary/by_status": {
            "get": {
                "description": "获取工单按 待办/完成 统计(只返回前10)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tt统计"
                ],
                "summary": "获取工单按 待办/完成 统计(只返回前10)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "起始时间戳. 秒数",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "结束时间戳. 秒数",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "是否结束。1: 完成的工单; 0: 未完成工单",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "handler.CreatePersonParamsArgs": {
            "type": "object",
            "required": [
                "category",
                "group_user",
                "impact",
                "item",
                "type",
                "work_group"
            ],
            "properties": {
                "category": {
                    "description": "总类",
                    "type": "integer"
                },
                "group_user": {
                    "description": "组员",
                    "type": "integer"
                },
                "impact": {
                    "description": "影响级别",
                    "type": "integer"
                },
                "item": {
                    "description": "名目",
                    "type": "integer"
                },
                "target_user": {
                    "description": "目标用户。可以为空。如果为空，在前端为\"默认系统配置\"",
                    "type": "string"
                },
                "type": {
                    "description": "子类",
                    "type": "integer"
                },
                "work_group": {
                    "description": "工作组",
                    "type": "integer"
                }
            }
        },
        "handler.CreatePersonParamsByCopyArgs": {
            "type": "object",
            "required": [
                "target_user",
                "template_user"
            ],
            "properties": {
                "target_user": {
                    "type": "string"
                },
                "template_user": {
                    "type": "string"
                }
            }
        },
        "model.PersonPreConfigParams": {
            "type": "object",
            "required": [
                "category",
                "group_user",
                "impact",
                "item",
                "type",
                "work_group"
            ],
            "properties": {
                "category": {
                    "description": "总类",
                    "type": "integer"
                },
                "edit_user": {
                    "type": "string"
                },
                "group_user": {
                    "description": "组员",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "impact": {
                    "description": "影响级别",
                    "type": "integer"
                },
                "item": {
                    "description": "名目",
                    "type": "integer"
                },
                "target_user": {
                    "description": "目标用户。可以为空。如果为空，在前端为\"默认系统配置\"",
                    "type": "string"
                },
                "type": {
                    "description": "子类",
                    "type": "integer"
                },
                "work_group": {
                    "description": "工作组",
                    "type": "integer"
                }
            }
        },
        "model.Ticket": {
            "type": "object",
            "properties": {
                "apply_user": {
                    "type": "string"
                },
                "category": {
                    "type": "integer"
                },
                "closed_time": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email_list": {
                    "type": "string"
                },
                "group_user": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "impact": {
                    "type": "integer"
                },
                "item": {
                    "type": "integer"
                },
                "no": {
                    "type": "string"
                },
                "one_time_resolve_rate": {
                    "type": "integer"
                },
                "resolve_cost": {
                    "type": "integer"
                },
                "resolve_time": {
                    "type": "string"
                },
                "resolve_timeout_sent": {
                    "type": "integer"
                },
                "response_cost": {
                    "type": "integer"
                },
                "response_time": {
                    "type": "string"
                },
                "response_timeout_sent": {
                    "type": "integer"
                },
                "root_cause": {
                    "type": "string"
                },
                "solution": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "submit_user": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "workgroup": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
