#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import subprocess


def get_ec2_price():
    account_file_path = "/data/Software/mydan/AGENT/device/conf/account/aws"
    lines = subprocess.getoutput(
        "c3mc-device-data-get curr compute aws-ec2 区域 实例类型").split("\n")
    data = {}
    for line in lines:
        parts = line.split()
        region = parts[0]
        instance_type = parts[1]

        if region not in data:
            data[region] = {}
        if instance_type not in data[region]:
            data[region][instance_type] = {}

    result = []
    account_m = {}
    with open(account_file_path) as file:
        for account_line in [line.rstrip() for line in file]:
            parts = account_line.split()
            account_m[parts[4]] = {
                "ak": parts[1],
                "sk": parts[2],
            }
    for region in data:
        for instance_type in data[region]:
            ac = "aws"
            if region.startswith("cn-"):
                ac = "aws-cn"
            if ac not in account_m:
                # 出现这种情况可能是
                # 1. 以前同步过中国区账号的资源, 后来账号被删掉了, 但是资源还在数据库
                # 2. 账号文件中没有配置aws-cn或者aws项
                sys.path.append("/data/Software/mydan/Connector/lib/pp")
                from c3mc_utils import print_c3debug1_log
                print_c3debug1_log(
                    "DEBUG1: {}. aws账号文件未配置账号类型".format(sys.argv[0]))
                break
            price = subprocess.getoutput(
                "c3mc-query-aws-ec2-price {} {} {} {}".format(
                    account_m[ac]["ak"],
                    account_m[ac]["sk"],
                    region,
                    instance_type,
                ))
            result.append("{};{}  {}".format(region, instance_type, price))
    return result


def get_rds_price():
    account_file_path = "/data/Software/mydan/AGENT/device/conf/account/aws"
    lines = subprocess.getoutput(
        "c3mc-device-data-get curr database aws-rds 区域 实例类型").split("\n")
    data = {}
    for line in lines:
        parts = line.split()
        region = parts[0]
        instance_type = parts[1]

        if region not in data:
            data[region] = {}
        if instance_type not in data[region]:
            data[region][instance_type] = {}

    result = []
    account_m = {}
    with open(account_file_path) as file:
        for account_line in [line.rstrip() for line in file]:
            parts = account_line.split()
            account_m[parts[4]] = {
                "ak": parts[1],
                "sk": parts[2],
            }
    for region in data:
        for instance_type in data[region]:
            ac = ""
            if region.startswith("cn-"):
                if "aws-cn" not in account_m:
                    # 出现这种情况可能是
                    # 1. 以前同步过中国区账号的资源, 后来账号被删掉了, 但是资源还在数据库
                    # 2. 账号文件中没有配置aws-cn项
                    sys.path.append("/data/Software/mydan/Connector/lib/pp")
                    from c3mc_utils import print_c3debug1_log
                    print_c3debug1_log(
                        "DEBUG1: {}. 获取实例类型的价格时无法找到对应区域的账号文件".format(sys.argv[0]))
                    break
                ac = "aws-cn"
            else:
                ac = "aws"
            price = subprocess.getoutput(
                "c3mc-query-aws-rds-price {} {} {} {}".format(
                    account_m[ac]["ak"],
                    account_m[ac]["sk"],
                    region,
                    instance_type,
                ))
            result.append("{};{}  {}".format(region, instance_type))
    return result


def get_all_resource_price():
    result = []
    price_list = get_ec2_price()
    result.extend(price_list)

    return result


def main():
    price_list = get_all_resource_price()
    for price in price_list:
        print(price)
    

if __name__ == '__main__':
    main()
