#!/bin/bash

BEGIN=$( date --date=' - 120 sec ' "+%s" )
END=$(   date --date=' + 120 sec ' "+%s" )

c3-table |grep keepalive \
| xargs -i{} bash -c "c3-db-get slave time -t {}|xargs -i[] echo \"{};[]\"" \
| awk -F';' "{if($BEGIN<\$3 && \$3< $END){printf \"on;\"}else{ printf \"OFF;\";} print \$0}" \
| sed 's/;/\t/g'
