#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

use YAML::XS;

=head1 SYNOPSIS

 $0

=cut

local $/ = undef;
my $input = <>;
my $info = YAML::XS::Load( $input );
local $/ = "\n";

my @alerts;
for my $a ( @{$info->{alerts}} )
{

    #数据扁平化 labels = +{ a => 1 } 变成 labels.a = 1
    for my $t ( qw( labels annotations ))
    {
        my $data = delete $a->{$t};
        map{ $a->{"$t.$_"} = $data->{$_} } keys %$data if $data && ref $data eq 'HASH';
    }

    $a->{time} = $info->{time};
    unless( $a->{"labels.fromtreeid"} && $a->{"labels.fromtreeid"} =~ /^\d+$/ )
    {
        warn "not labels.fromtreeid";
    }
    else
    {
        push @alerts, $a;
    }
}

print YAML::XS::Dump @alerts;

