#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_qcloud_postgres import LibQcloudPostgres


class PostGres:
    def __init__(self, access_id, access_key, region):
        self.region = region
        self.lib_client = LibQcloudPostgres(access_id, access_key, region)

    def list_instances(self):
        return self.lib_client.describe_db_instances()

    def show(self):
        instance_list = self.list_instances()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    try:
        PostGres(access_id, access_key, region).show()
    except Exception as e:
        print(f"同步腾讯云 postgres 资源出错. access_id: {access_id}, region: {region}", file=sys.stderr)
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
