#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json


class LB:
    def __init__(self, cred_json_path, region):
        self.cred_json_path = cred_json_path
        self.region = region
        self.lib_client = self.create_lib_client()

    def create_lib_client(self):
        sys.path.append("/data/Software/mydan/Connector/lib/pp")
        from c3mc_cloud_google_compute import GoogleCompute
        return GoogleCompute(self.cred_json_path)

    def list_instances(self):
        project_id = self.lib_client.get_project_id()
        # C3TODO 230421 谷歌云lb同步可能需要扩展这里查询到的信息
        # 谷歌云LB没有一个可以一次性查到lb所有信息的接口，目前看urlMap的
        # list方法获取的结果里包含了lb名称，其他接口查到的都是lb的其他相关信息
        # 但是这个方法查询到的信息较少，可能需要扩展
        data = self.lib_client.list_url_maps() if self.region == "global" else self.lib_client.list_region_url_maps(self.region)
        for i in range(len(data)):
            data[i]["customInstanceId"] = f"{project_id}-{self.region}-{data[i]['name']}"
            data[i]["region"] = self.region
            data[i]["project_id"] = project_id
        return data

    def show(self):
        instance_list = self.list_instances()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(cred_json_path, region):
    LB(cred_json_path, region).show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
