#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

from huaweicloudsdkcore.auth.credentials import BasicCredentials
from huaweicloudsdkkafka.v2.region.kafka_region import KafkaRegion
from huaweicloudsdkkafka.v2 import *


class Kafka:
    def __init__(self, access_id, access_key, project_id, region):
        self.access_id = access_id
        self.access_key = access_key
        self.project_id = None if project_id == "None" else project_id.strip()
        self.region = region

        self.client = self.create_client()

    def create_client(self):
        credentials = BasicCredentials(
            self.access_id, self.access_key, self.project_id)
        return (
            KafkaClient.new_builder()
            .with_credentials(credentials)
            .with_region(KafkaRegion.value_of(self.region))
            .build()
        )

    def list_instances(self):
        request = ListInstancesRequest()
        response = self.client.list_instances(request)
        data = json.loads(str(response))["instances"]
        for i in range(len(data)):
            data[i]["region"] = self.region
        return data

    def show(self):
        data_list = self.list_instances()
        for item in data_list:
            print(json.dumps(item, default=str))


# project_id 可以命令行传 None
def main(access_id, access_key, project_id, region):
    """同步华为云kafka资源

    Args:
        access_id (str): ak
        access_key (str): sk
        project_id (str): 项目id
        region (str): 区域
    """
    Kafka(access_id, access_key, project_id, region).show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
