#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.sqlserver.v20180328 import sqlserver_client, models


# DescribeDBInstances() 的接口请求频率限制
max_times_describe_db_instances = 20

class Sqlserver:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.page_number = 1
        self.page_size = 25
        self.client = self.create_client()
        self.status_code_m = {
            1: "申请中",
            2: "运行中",
            3: "受限运行中(主备切换中)",
            4: "已隔离",
            5: "回收中",
            6: "已回收",
            7: "任务执行中(实例做备份、回档等操作)",
            8: "已下线",
            9: "实例扩容中",
            10: "实例迁移中",
            11: "只读",
            12: "重启中",
            13: "实例修改中且待切换",
            14: "订阅发布创建中",
            15: "订阅发布修改中",
            16: "实例修改中且切换中",
            17: "创建RO副本中",
        }

    def create_client(self):
        cred = credential.Credential(
            self.access_id, self.access_key)
        httpProfile = HttpProfile()
        httpProfile.endpoint = "sqlserver.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        client = sqlserver_client.SqlserverClient(
            cred, self.region, clientProfile)
        return client

    def set_request(self):
        req = models.DescribeDBInstancesRequest()
        req.Limit = self.page_size
        req.Offset = (self.page_number - 1) * self.page_size
        return req

    def get_response(self):
        request = self.set_request()
        response_data = self.client.DescribeDBInstances(request)
        return response_data

    def get_server_count(self):
        response_data = self.get_response()
        return response_data.TotalCount

    def list_instance(self):
        response_data = self.get_response()
        response_data = json.loads(response_data.to_json_string())

        result = []
        for instance in response_data["DBInstances"]:
            if "Status" in instance and isinstance(instance["Status"], int):
                instance["StatusZhDesc"] = self.status_code_m[instance["Status"]]

            result.append(instance)
        return result

    def show(self):
        instance_list = self.list_instance()
        for instance in instance_list:
            print(json.dumps(instance, default=str))

    def sleep(self):
        sys.path.append("/data/Software/mydan/Connector/lib/pp")
        from c3mc_utils import sleep_time_for_limiting
        sleep_time_for_limiting(max_times_describe_db_instances)

    def page(self):
        count = self.get_server_count()
        mod = count % self.page_size
        if mod:
            total_page_number = int(count / self.page_size) + 1
        else:
            total_page_number = int(count / self.page_size)

        for cur_page_number in range(1, total_page_number + 1):
            self.page_number = cur_page_number
            self.sleep()
            self.show()


def main(access_id, access_key, region):
    Sqlserver(access_id, access_key, region).page()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
