#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import sys
import json

from ks3.connection import Connection


class Ks3:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()

    def create_client(self):
        region_name = self.region
        if region_name[-1].isdigit():
            region_name = region_name[:-2]

        return Connection(
            self.access_id,
            self.access_key,
            "ks3-{}.ksyuncs.com".format(region_name),
        )

    def list_instances(self):
        results = []
        buckets = self.client.get_all_buckets()
        for ksyun_bucket in buckets:
            results.append({
                "name": ksyun_bucket.name,
                "creation_date": ksyun_bucket.creation_date
            })
        return results

    def show(self):
        instance_list = self.list_instances()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    Ks3(access_id, access_key, region).show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
