#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_huawei_obs import HuaweiObs


class Obs:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.lib_client = self.create_lib_client()

    def create_lib_client(self):
        return HuaweiObs(self.access_id, self.access_key, self.region)

    def list_buckets(self):
        return self.lib_client.list_buckets()

    def show(self):
        bucket_list = self.list_buckets()
        for bucket in bucket_list:
            print(json.dumps(bucket))


def main(access_id, access_key, region):
    try:
        Obs(access_id, access_key, region).show()
    except Exception as e:
        print(f"同步华为云obs资源出错. access_id: {access_id}, region: {region}", file=sys.stderr)
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[4])
