#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_rds import LibRds


"""同步rds集群列表
"""


def display(access_id, access_key, region):
    def get_rds_cluster_list():
        return LibRds(access_id, access_key, region).describe_db_clusters_v2()
    
    rds_cluster_list = get_rds_cluster_list()

    for rds_cluster in rds_cluster_list:
        print(json.dumps(rds_cluster, default=str))


def main(access_id, access_key, region):
    try:
        display(access_id, access_key, region)
    except Exception as e:
        print(f"同步aws rds cluster资源出错. access_id: {access_id}, region: {region}", file=sys.stderr) 
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
