#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.redis.v20180412 import redis_client, models

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_utils import sleep_time_for_limiting


# DescribeInstances() 的接口请求频率限制
max_times_describe_instances = 50


class Redis:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.page_number = 1
        self.page_size = 25
        self.client = self.create_client()

    def create_client(self):
        cred = credential.Credential(self.access_id, self.access_key)
        httpProfile = HttpProfile()
        httpProfile.endpoint = "redis.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        return redis_client.RedisClient(cred, self.region, clientProfile)

    def set_request(self):
        req = models.DescribeInstancesRequest()
        req.Limit = self.page_size
        req.Offset = (self.page_number - 1) * self.page_size
        return req

    def get_response(self):
        request = self.set_request()
        return self.client.DescribeInstances(request)

    def get_server_count(self):
        response_data = self.get_response()
        return response_data.TotalCount

    def show(self):
        response_data = self.get_response()
        redis_list = response_data.InstanceSet
        for redis in redis_list:
            print(redis.to_json_string())

    def sleep(self):
        sleep_time_for_limiting(max_times_describe_instances)

    def page(self):
        try:
            count = self.get_server_count()
            if count % self.page_size:
                total_page_number = int(count / self.page_size) + 1
            else:
                total_page_number = int(count / self.page_size)

            for cur_page_number in range(1, total_page_number + 1):
                self.page_number = cur_page_number
                self.sleep()
                self.show()
        except Exception as e:
            if "该接口不支持此地域访问" in str(e):
                return []
            else:
                raise e


def main(access_id, access_key, region):
    try:
        Redis(access_id, access_key, region).page()
    except Exception as e:
        print(f"同步腾讯云redis资源出错. access_id: {access_id}, region: {region}", file=sys.stderr) 
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
