#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

from kscore.session import get_session
sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_ksyun_vpc import Vpc

class Epc:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.page_size = 25
        self.client = self.create_client()

    def create_client(self):
        s = get_session()
        client = s.create_client(
            "epc", ks_access_key_id=self.access_id, ks_secret_access_key=self.access_key, region_name=self.region)
        return client

    def get_instances_from_response(self, response_data):
        results = []
        for instance in response_data["HostSet"]:
            instance["RegionId"] = instance["AvailabilityZone"][:-1]
            results.append(instance)
        return response_data["HostSet"]

    def show(self):
        vpc_client = Vpc(self.access_id, self.access_key, self.region)

        response = self.client.describe_epcs(MaxResults=self.page_size)
        results = self.get_instances_from_response(response)
        while "NextToken" in response:
            if response["NextToken"] is None:
                break
            response = self.client.describe_epcs(
                MaxResults=self.page_size, NextToken=response["NextToken"])
            results.extend(self.get_instances_from_response(response))

        tag_dict = self.list_tag()
        for instance in results:
            if len(instance["NetworkInterfaceAttributeSet"]) > 0:
                instance["VpcId"] = instance["NetworkInterfaceAttributeSet"][0]["VpcId"]
                instance["VpcName"] = vpc_client.show_vpc(instance["VpcId"])["VpcName"]

            if instance["HostId"] in tag_dict:
                instance["Tag"] = tag_dict[instance["HostId"]]

            print(json.dumps(instance, default=str))

    def list_tag(self):
        from c3mc_cloud_ksyun_get_tag import GetTag
        return GetTag(self.access_id, self.access_key, self.region).get_tag_dict()


def main(access_id, access_key, region):
    Epc(access_id, access_key, region).show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
