#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

import boto3


class Rds:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()
        self.page_size = 20

    def create_client(self):
        endpoint_url = "https://rds.{}.amazonaws.com".format(self.region)
        if self.region.startswith("cn"):
            endpoint_url = "https://rds.{}.amazonaws.com.cn".format(
                self.region)

        client = boto3.client(
            "rds",
            endpoint_url=endpoint_url,
            aws_access_key_id=self.access_id,
            aws_secret_access_key=self.access_key,
            region_name=self.region,
        )
        return client

    def get_instances_from_response(self, response_data):
        results = []
        for instance in response_data["DBInstances"]:
            instance["RegionId"] = self.region
            results.append(instance)
        return results

    def get_cpu_and_memory(self, instance_type):
        return subprocess.getoutput("c3mc-query-aws-rds-instance-type-info {} {} {} {}".format(
            self.access_id, self.access_key, self.region, instance_type))

    def list_instance(self):
        response = self.client.describe_db_instances(MaxRecords=self.page_size)
        results = self.get_instances_from_response(response)
        while "Marker" in response:
            response = self.client.describe_db_instances(
                MaxRecords=self.page_size, Marker=response["Marker"])
            results.extend(self.get_instances_from_response(response))

        aws_instance_info_m = {}
        instance_type_m = {}

        for i in range(len(results)):
            instance_type = results[i]["DBInstanceClass"]
            if instance_type not in instance_type_m:
                if self.region.startswith("cn-"):
                    if len(aws_instance_info_m) == 0:
                        sys.path.append("/data/Software/mydan/Connector/lib/pp")
                        from c3mc_cloud_aws_china_get_price_data import get_rds_instance_type_info_m
                        aws_instance_info_m = get_rds_instance_type_info_m(self.region)

                    deploy_mode = ""
                    if results[i]["MultiAZ"]:
                        deploy_mode = "Multi-AZ"
                    else:
                        deploy_mode = "Single-AZ"
                    
                    attr = aws_instance_info_m[self.region][instance_type][deploy_mode]
                    attr["memory"] = attr["memory"][:-len(" GiB")]
                    instance_type_m[instance_type] = attr
                else:
                    res = self.get_cpu_and_memory(instance_type)
                    instance_type_m[instance_type] = json.loads(res)

            results[i]["_cpu_"] = instance_type_m[instance_type]["vcpu"]
            results[i]["_memory_"] = instance_type_m[instance_type]["memory"]
        return results

    def show(self):
        instance_list = self.list_instance()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    rds = Rds(access_id, access_key, region)
    rds.show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
