#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

import boto3

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_dynamodb import LibAwsDynamodb


class Dynamodb:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.bucket_list = []
        self.client = self.create_client()
        self.lib_client = LibAwsDynamodb(access_id, access_key, region)

    def create_client(self):
        client = boto3.client(
            "dynamodb",
            aws_access_key_id=self.access_id,
            aws_secret_access_key=self.access_key,
            region_name=self.region,
        )
        return client

    def list_instance(self):
        instance_list = []
        response = self.client.list_tables()
        for table_name in response["TableNames"]:
            table_info = self.client.describe_table(TableName=table_name)
            table_arn = table_info["Table"]["TableArn"]

            item = dict(table_info["Table"].items())
            item["RegionId"] = self.region
            item["Tag"] = self.lib_client.list_tag(table_arn)
            instance_list.append(item)
        return instance_list

    def show(self):
        instance_list = self.list_instance()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    try:
        Dynamodb(access_id, access_key, region).show()
    except Exception as e:
        print(f"同步aws dynamodb资源出错. access_id: {access_id}, region: {region}", file=sys.stderr)
        raise e


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
