#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

from google.oauth2 import service_account
from googleapiclient import discovery


class Mysql:
    def __init__(self, cred_json_path):
        self.cred_json_path = cred_json_path
        self.credentials = self.create_credentials()
        self.page_size = 500

    def create_credentials(self):
        return service_account.Credentials.from_service_account_file(self.cred_json_path)

    def list_instance(self):
        results = []
        service = discovery.build(
            'sqladmin', 'v1', credentials=self.credentials)

        request = service.instances().list(project=self.credentials.project_id)
        while request is not None:
            response = request.execute()

            for instance in response['items']:
                instance.pop("serverCaCert", None)
                if "ipAddresses" in instance:
                    for item in instance["ipAddresses"]:
                        if item["type"] == "PRIVATE":
                            instance["private_ip"] = item["ipAddress"]
                            break
                instance["tags_list"] = []
                if "userLabels" in instance["settings"]:
                    for key, value in instance["settings"]["userLabels"].items():
                        instance["tags_list"].append({
                            "Key": key,
                            "Value": value
                        })
                instance["id"] = "{}-{}-{}".format(instance["project"], instance["region"], instance["name"])
                results.append(instance)

            request = service.instances().list_next(
                previous_request=request, previous_response=response)
        return results

    def show(self):
        instance_list = self.list_instance()
        for instance in instance_list:
            print(json.dumps(instance))


def main(cred_json_path):
    mysql = Mysql(cred_json_path)
    mysql.show()


if __name__ == '__main__':
    main(sys.argv[1])
