#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import random
import time

from aliyunsdkcore.client import AcsClient
from aliyunsdkslb.request.v20140515.DescribeLoadBalancersRequest import (
    DescribeLoadBalancersRequest,
)


def exponential_backoff(attempt, max_delay):
    delay = min(max_delay, (2**attempt) + random.uniform(0, 1))
    time.sleep(delay)


class Slb:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()
        self.page_number = 1
        self.page_size = 25

    def create_client(self):
        return AcsClient(self.access_id, self.access_key, self.region)

    def set_request(self):
        request = DescribeLoadBalancersRequest()
        request.set_accept_format("json")
        request.set_PageNumber(self.page_number)
        request.set_PageSize(self.page_size)
        return request

    def get_response(self):
        request = self.set_request()

        # 最多尝试5次
        attempt = 0
        while attempt < 5:
            try:
                response = self.client.do_action_with_exception(request)
                return json.loads(response)
            except Exception as e:
                if "Failed to establish a new connection" not in str(e):
                    raise e
                print("请求获取数据出现网络错误, 等待重试...", file=sys.stderr)
                exponential_backoff(attempt, 10)
                attempt += 1
                

    def get_server_count(self):
        try:
            response_data = self.get_response()
        except Exception as e:
            if "The specified RegionId does not exist" in str(e):
                return 0
            raise RuntimeError("获取阿里云slb资源出错") from e
        return response_data["TotalCount"]

    def show(self):
        response_data = self.get_response()
        instances = response_data["LoadBalancers"]["LoadBalancer"]
        for instance in instances:
            if "Tags" in instance and "Tag" in instance["Tags"]:
                instance["Tag"] = instance["Tags"]["Tag"]
                instance.pop("Tags", None)
            print(json.dumps(instance))

    def page(self):
        count = self.get_server_count()
        if count % self.page_size:
            total_page_number = int(count / self.page_size) + 1
        else:
            total_page_number = int(count / self.page_size)

        for cur_page_number in range(1, total_page_number + 1):
            self.page_number = cur_page_number
            self.show()


def main(access_id, access_key, region):
    try:
        Slb(access_id, access_key, region).page()
    except Exception as e:
        print(f"同步阿里云slb资源出错. access_id: {access_id}, region: {region}", file=sys.stderr)
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
