#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aliyun_fs import LibAliyunFS


class AliyunFS:
    def __init__(self, access_id, access_key, region):
        self.lib_client = LibAliyunFS(access_id, access_key, region)

    def describe_file_systems(self):
        return self.lib_client.describe_file_systems()

    def show(self):
        data_list = self.describe_file_systems()
        for item in data_list:
            print(json.dumps(item, default=str))


def main(access_id, access_key, region):
    try:
        AliyunFS(access_id, access_key, region).show()
    except Exception as e:
        print(f"同步阿里云fs资源出错. access_id: {access_id}, region: {region}", file=sys.stderr)
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
