#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

from huaweicloudsdkcore.auth.credentials import BasicCredentials
from huaweicloudsdkelb.v3.region.elb_region import ElbRegion
from huaweicloudsdkelb.v3 import *


class Elb:
    def __init__(self, access_id, access_key, project_id, region):
        self.access_id = access_id
        self.access_key = access_key
        self.project_id = None if project_id == "None" else project_id.strip()
        self.region = region
        self.client = self.create_client()

    def create_client(self):
        credentials = BasicCredentials(self.access_id, self.access_key, self.project_id)
        return (
            ElbClient.new_builder()
            .with_credentials(credentials)
            .with_region(ElbRegion.value_of(self.region))
            .build()
        )

    def set_request(self, marker):
        return ListLoadBalancersRequest()

    def get_instances_from_response(self, response):
        result = []
        for instance in json.loads(str(response.loadbalancers)):
            instance["region"] = self.region
            result.append(instance)
        return result

    def list_instance(self):
        response = self.client.list_load_balancers(self.set_request(None))
        return self.get_instances_from_response(response)

    def show(self):
        instance_list = self.list_instance()
        for instance in instance_list:
            print(json.dumps(instance))


# project_id 可以命令行传 None
def main(access_id, access_key, project_id, region):
    try:
        Elb(access_id, access_key, project_id, region).show()
    except Exception as e:
        print(f"同步华为云elb资源出错. access_id: {access_id}, region: {region}", file=sys.stderr)
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
