#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_huawei_dns import HuaweiCloudDNS


class SubDomains:
    def __init__(self, access_id, access_key, project_id, region):
        self.lib_client = HuaweiCloudDNS(access_id, access_key, project_id, region)

    def display(self):
        data_list = self.lib_client.get_subdomains()
        for item in data_list:
            print(json.dumps(item, default=str))
        

def main(access_id, access_key, project_id, region):
    try:
        SubDomains(access_id, access_key, project_id, region).display()
    except Exception as e:
        print(f"同步华为子域名列表出错. error: {str(e)}", file=sys.stderr)
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
