#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.cvm.v20170312 import cvm_client, models

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_qcloud_vpc import Vpc
from c3mc_cloud_qcloud_project import Project


# DescribeInstances() 的接口请求频率限制
max_times_describe_instances = 40

class Cvm:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.page_number = 1
        self.page_size = 25
        self.client = self.create_client()

    def create_client(self):
        cred = credential.Credential(
            self.access_id, self.access_key)
        httpProfile = HttpProfile()
        httpProfile.endpoint = "cvm.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        client = cvm_client.CvmClient(cred, self.region, clientProfile)
        return client

    def set_request(self):
        req = models.DescribeInstancesRequest()
        req.Limit = self.page_size
        req.Offset = (self.page_number - 1) * self.page_size
        return req

    def get_response(self):
        request = self.set_request()
        response_data = self.client.DescribeInstances(request)
        return response_data

    def get_server_count(self):
        response_data = self.get_response()
        return response_data.TotalCount

    def show(self):
        vpc_client = Vpc(self.access_id, self.access_key, self.region)

        response_data = self.get_response()

        result = []
        vpc_ids = []
        for server in response_data.InstanceSet:
            item = json.loads(server.to_json_string())
            item["RegionId"] = self.region

            if item["PrivateIpAddresses"] is not None and len(item["PrivateIpAddresses"]) > 0:
                item["PrivateIP"] = item["PrivateIpAddresses"][0]
            if item["PublicIpAddresses"] is not None and len(item["PublicIpAddresses"]) > 0:
                item["PublicIP"] = item["PublicIpAddresses"][0]
            item["ProjectName"] = self.project_m[item["Placement"]["ProjectId"]]["Name"]
            
            if 'OsName' in item:
                item["os"] = "Windows" if item["OsName"].lower().find("window") != -1 else "Linux"
            else:
                item["os"] = "Other"

            result.append(item)
            
            if item["VirtualPrivateCloud"]["VpcId"] is not None:
                vpc_ids.append(item["VirtualPrivateCloud"]["VpcId"])

        
        vpc_info_d = vpc_client.show_vpcs_dict(vpc_ids)
        for item in result:
            if item["VirtualPrivateCloud"]["VpcId"] is not None:
                item["VpcId"] = item["VirtualPrivateCloud"]["VpcId"]
                item["VpcName"] = vpc_info_d[item["VpcId"]]["VpcName"]

            print(json.dumps(item, default=str))

    def sleep(self, seconds):
        from c3mc_utils import sleep_time_for_limiting
        sleep_time_for_limiting(seconds)

    def page(self):
        try:
            project_list = Project(self.access_id, self.access_key, self.region).show_projects()
            project_m = {}
            for project in project_list:
                project_m[project["ProjectId"]] = project
            self.project_m = project_m

            count = self.get_server_count()
            mod = count % self.page_size
            if mod:
                total_page_number = int(count / self.page_size) + 1
            else:
                total_page_number = int(count / self.page_size)

            for cur_page_number in range(1, total_page_number + 1):
                self.page_number = cur_page_number
                self.sleep(max_times_describe_instances)
                self.show()
        except Exception as e:
            if "该接口不支持此地域访问" in str(e):
                return []
            else: 
                raise Exception(e)


def main(access_id, access_key, region):
    cvm = Cvm(access_id, access_key, region)
    cvm.page()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
