#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

from aliyunsdkcore.client import AcsClient
from aliyunsdkslb.request.v20140515.DescribeLoadBalancersRequest import DescribeLoadBalancersRequest


class Slb:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()
        self.page_number = 1
        self.page_size = 25

    def create_client(self):
        client = AcsClient(self.access_id, self.access_key, self.region)
        return client

    def set_request(self):
        request = DescribeLoadBalancersRequest()
        request.set_accept_format('json')
        request.set_PageNumber(self.page_number)
        request.set_PageSize(self.page_size)
        return request

    def get_response(self):
        request = self.set_request()
        response = self.client.do_action_with_exception(request)
        response_data = json.loads(response)
        return response_data

    def get_server_count(self):
        try:
            response_data = self.get_response()
        except Exception as e:
            if "The specified RegionId does not exist" in str(e):
                return 0
            raise RuntimeError("获取阿里云slb资源出错") from e
        return response_data['TotalCount']

    def show(self):
        response_data = self.get_response()
        instances = response_data['LoadBalancers']['LoadBalancer']
        for instance in instances:
            if "Tags" in instance and "Tag" in instance["Tags"]:
                instance["Tag"] = instance["Tags"]["Tag"]
                instance.pop("Tags", None)
            print(json.dumps(instance))

    def page(self):
        count = self.get_server_count()
        mod = count % self.page_size
        if mod:
            total_page_number = int(count / self.page_size) + 1
        else:
            total_page_number = int(count / self.page_size)

        for cur_page_number in range(1, total_page_number + 1):
            self.page_number = cur_page_number
            self.show()


def main(access_id, access_key, region):
    Slb(access_id, access_key, region).page()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
