#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_memorydb import LibMemoryDB


def main(access_id, access_key, region):
    try:
        shard_list = LibMemoryDB(access_id, access_key, region).list_cluster_node()
        for shard in shard_list:
            print(json.dumps(shard, default=str))
    except Exception as e:
        if "Could not connect to the endpoint URL" in str(e):
            return
        print(f"同步aws memorydb node资源出错. access_id: {access_id}, region: {region}", file=sys.stderr) 
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
