#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_rds import LibRds


class RdsSnapshot:
    def __init__(self, access_id, access_key, region):
        self.lib_client = LibRds(access_id, access_key, region)

    def list_db_snapshot(self):
        return self.lib_client.list_db_snapshot()

    def show(self):
        instance_list = self.list_db_snapshot()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    try:
        RdsSnapshot(access_id, access_key, region).show()
    except Exception as e:
        print(f"同步aws rds snapshot资源出错. access_id: {access_id}, region: {region}", file=sys.stderr) 
        raise e


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
