#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_globalaccelerator import GlobalAccelerator 

def main(account, access_id, access_key, region):
    try:
        if account != "aws-cn":
            instance_list = GlobalAccelerator(access_id, access_key, region).get_accelerators_list()

            for instance in instance_list:
                print(json.dumps(instance, default=str))
    except Exception as e:
        print(f"同步aws GA资源出错. access_id: {access_id}, region: {region}", file=sys.stderr)
        raise e

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
