#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_elbv2 import ELBV2


def list_alb(access_id, access_key, region):
    instance_list = ELBV2(access_id, access_key, region, "network").get_instance_list()
    for instance in instance_list:
        print(json.dumps(instance, default=str))

def main(access_id, access_key, region):
    list_alb(access_id, access_key, region)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
