#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

use File::Basename;

$|++;

=head1 SYNOPSIS

 生成c3mc工具的帮助文档，处理单个文件

 $0 /dir/c3mc-xxx

=cut

my $file = shift @ARGV;
die "nofile" unless $file && -f $file;

my    @x = `cat '$file'`;
chomp @x;

sub perlh
{
    my ( $match, @c, @r ) = ( 0, @_ );
    for my $x ( @c )
    {
        $x =~ s/\s*$//;

        last if $x eq '=cut';
        push @r, $x if $match;
        $match = 1 if $x eq '=head1 SYNOPSIS';
    }
    return @r;
}

sub perl
{
    my ( $name, @c ) = @_;
    print "## $name\n";
    if( my @xx = perlh(@c) )
    {
        print "```\n";
        map{ print "$_\n"; }@xx;
        print "```\n";
    }
    else { warn "[Warn] $name nofind\n"; }
}

sub bashh
{
    my ( @c, @r ) = @_;
    map{push @r, $1 if $_ =~ /^### (.+)/;}@c;
    return @r;
}

sub bash
{
    my ( $name, @c ) = @_;
    print "## $name\n";
    if( my @xx = bashh(@c) )
    {
        print "```\n";
        map{ print "$_\n"; }@xx;
        print "```\n";
    }
    else { warn "[Warn] $name nofind\n"; }
}

my $name = basename $file;

my $m = 0;
$m = 1 && perl( "$name/perl", @x ) if $x[0] && index( $x[0],  "#!/data/Software/mydan/perl/bin/perl" ) == 0;
$m = 1 && bash( "$name/bash", @x ) if $x[0] && index( $x[0],  "#!/bin/bash" ) == 0;

exit 1 if $m;

warn "[Warn] $name/unkown nofind\n";
