#Author: lijinfeng2011@gmail.com

FROM openc3/basev2:t2206131
MAINTAINER lijinfeng2011

COPY grafana-9.0.1/usr_share_grafana /usr/share/grafana
COPY grafana-9.0.1/etc_grafana /etc/grafana
COPY grafana-9.0.1/var_lib_grafana_plugins /var/lib/grafana/plugins

COPY grafana.ini /etc/grafana/grafana.ini

ENTRYPOINT [ "/entrypoint.sh" ]
