#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def ec2_describe_ebs_volume_types():
    """
        查询ebs volume类型列表
    """
    return [
        {
            "id": "standard",
            "desc": "standard",
        },
        {
            "id": "io2",
            "desc": "EBS Provisioned IOPS SSD (io2)",
        },
        {
            "id": "io2 Block Express",
            "desc": "EBS Provisioned IOPS SSD (io2 Block Express)",
        },
        {
            "id": "io1",
            "desc": "EBS Provisioned IOPS SSD (io1)",
        },
        {
            "id": "gp3",
            "desc": "EBS General Purpose SSD (gp3)",
        },
        {
            "id": "gp2",
            "desc": "EBS General Purpose SSD (gp2)",
        },
        {
            "id": "st1",
            "desc": "Throughput Optimized HDD (st1)",
        },
        {
            "id": "sc1",
            "desc": "Cold HDD (sc1)",
        },
    ]


def main(params):
    if_need_data_volume = params["if_need_data_volume"]
    if not if_need_data_volume:
        return

    volume_type_list = ec2_describe_ebs_volume_types()
    for volume_type in volume_type_list:
        print(json.dumps(volume_type, default=str))


if __name__ == '__main__':
    main()
