#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

import boto3


def describe_availability_zones(access_id, access_key, region):
    """
        查询aws指定区域的可用区列表
    """
    client = boto3.client(
        "ec2",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region
    )

    response = client.describe_availability_zones(
        Filters=[
            {
                'Name': 'region-name',
                'Values': [
                    region
                ]
            },
        ],
        AllAvailabilityZones=False
    )
    return response["AvailabilityZones"]


def main(params):
    account = params["account"]
    region = params["region"]

    key_info = json.loads(subprocess.getoutput(
        "c3mc-get-account-info aws {}".format(account)))

    az_list = describe_availability_zones(
        key_info["access_id"], key_info["access_key"], region)
    for az in az_list:
        print(json.dumps(az, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]))
