#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

import boto3


def describe_vpcs(access_id, access_key, region):
    """
        查询vpc列表
    """
    client = boto3.client(
        "ec2",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region
    )

    page_size = 100

    result = []
    response = client.describe_vpcs(MaxResults=page_size)
    result.extend(response["Vpcs"])
    marker = ""
    if "NextToken" in response:
        marker = response["NextToken"]

    while marker != "":
        response = client.describe_vpcs(MaxResults=page_size, NextToken=marker)
        result.extend(response["Vpcs"])

        marker = ""
        if "NextToken" in response:
            marker = response["NextToken"]
    for i in range(len(result)):
        for tag in result[i]["Tags"]:
            if tag["Key"] == "Name":
                result[i]["Name"] = tag["Value"]
                break

    return result


def main(params):
    account = params["account"]
    region = params["region"]

    key_info = json.loads(subprocess.getoutput(
        "c3mc-get-account-info aws {}".format(account)))

    vpc_list = describe_vpcs(
        key_info["access_id"], key_info["access_key"], region)
    for vpc in vpc_list:
        print(json.dumps(vpc, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]))
