#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json

import boto3


def get_role(access_id, access_key, region, role_name):
    """
        查询角色

        如果不存在, 返回空字典
    """
    client = boto3.client(
        "iam",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region
    )

    try:
        response = client.get_role(RoleName=role_name)
        return response["Role"]
    except client.exceptions.NoSuchEntityException:
        return {}


def main(access_id, access_key, region, role_name):
    data = get_role(access_id, access_key, region, role_name)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
