#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys

import boto3


def create_role(access_id, access_key, region, role_name):
    """
        创建iam role
    """
    client = boto3.client(
        "iam",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region
    )

    client.create_role(
        RoleName=role_name,
        AssumeRolePolicyDocument="""{                                                                                                                                                                                    
            "Statement": [  
                {   
                    "Principal": {
                        "Service": ["ec2.amazonaws.com"]
                    },  
                    "Effect": "Allow",
                    "Action": ["sts:AssumeRole"]
                }   
            ]   
        } 
        """
    )


def main(access_id, access_key, region, role_name):
    create_role(access_id, access_key, region, role_name)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
