#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_ec2 import LIB_EC2


def get_intance_types(account, region, az, architecture):
    cmd_dict = {
        "account": account,
        "region": region,
        "az": az,
        "architecture": architecture,
    }
    cmd_str = json.dumps(cmd_dict)
    resp = subprocess.run(
        ["c3mc-ec2create-describe-instance-type-offerings"],
        input=cmd_str.encode(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if resp.returncode != 0:
        raise RuntimeError(f"获取实例类型失败: {resp.stderr.decode('utf-8').rstrip()}")
    
    return resp.stdout.decode("utf-8").strip()


def main(params):
    """查询aws区域下的ec2列表"""
    account = params["account"]
    region = params["region"]
    instance_id = params["instance_id"]

    key_info = json.loads(subprocess.getoutput(f"c3mc-get-account-info aws {account}"))

    instance_info = LIB_EC2(
        key_info["access_id"], key_info["access_key"], region
    ).describe_instance_with_tries(instance_id)

    az = instance_info["Placement"]["AvailabilityZone"]
    arch = instance_info["Architecture"]

    output = get_intance_types(account, region, az, arch)

    for item in output.split("\n"):
        print(item)


if __name__ == "__main__":
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type("WrongInputData", (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
