#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import subprocess


def display_target_list():
    """
        查询使用目标列表
    """
    data = [
        {
            "id": "AWS",
            "desc": "AWS"
        },
        {
            "id": "腾讯云",
            "desc": "腾讯云"
        },
        {
            "id": "金山云",
            "desc": "金山云"
        },
        {
            "id": "阿里云",
            "desc": "阿里云"
        },
        {
            "id": "华为云",
            "desc": "华为云"
        },
    ]
    additional_target_list = json.loads(
        subprocess.getoutput("c3mc-bpm-read-config-file " + "certificate_target_list")
    )
    for item in additional_target_list:
        data.append({
            "id" : item,
            "desc" : item,
        })


def main():
    data_list = display_target_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
