#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use JSON;
use Logs;
use FindBin qw( $RealBin );
use File::Basename;
use Encode;
use Util;
use MYDB;

$| ++;

=head1 SYNOPSIS

    db => $mysql,
    id => id,

    logs => 日志对象

    addr => ''
    ticketid => ''
    treeid => ''

=cut

return sub
{
    my %param = @_;

    my ( $db, $id, $logs, $addr, $ticketid, $treeid )
        = @param{qw( db id logs addr ticketid treeid )};

    $logs = Logs->new( 'code.findtags.openc3fileserver' ) unless $logs;
    $logs->die( "id format error" ) unless $id =~ /^\d+$/;

    my $dbJobExt = MYDB->new( "$RealBin/../../JOB/conf/conn" );

    my $tag = eval{ $dbJobExt->query( "select name from openc3_job_fileserver where projectid='$treeid' and status='available'" ) };
    return map{@$_}@$tag;
}
