#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


def domain(params):
    data = """"""

    if params["ApplyType"] == "域名解析新申请":
        data = """
        域名: {},
        解析目的(IP/线路/域名): {},
        业务名称: {}
        """.format(
            params["DomainName"], 
            params["ResolveTarget"], 
            params["BusinessNode"])
    if params["ApplyType"] == "域名解析修改":
        data = """
        域名: {},
        原解析: {},
        解析目的(IP/线路/域名): {}
        """.format(
            params["DomainName"], 
            params["OldResolveTarget"], 
            params["ResolveTarget"])
    if params["ApplyType"] == "域名解析删除":
        data = """
        域名: {},
        原解析: {}
        """.format(
            params["DomainName"], 
            params["OldResolveTarget"])
    if params["ApplyType"] == "域名注册":
        data = """
        域名: {},
        是否被注册: {},
        备案主体: {},
        所属业务: {}
        """.format(
            params["DomainName"], 
            params["IfDomainHasRegistered"],
            params["WebsiteBelonger"],
            params["BusinessNode"],
        )

    newline = "<br/>"
    data = data.replace("\n", newline)[len(newline):]

    tt_number = subprocess.run([
            "c3mc-create-ticket", 
            "--submit_user", "sys@app", 
            "--title", params["Title"], 
            "--ext_tt", params["IfExt"],
        ], 
        input=data.encode(), 
        stdout=subprocess.PIPE,
    ).stdout.decode('utf-8')
    return tt_number


def main(params):
    data = domain(params)
    print(data.rstrip())
    

if __name__ == '__main__':
    arg = sys.argv[1]
    if arg[-2:] == "\\n":
        # arg参数末尾可能带着\n后缀,测试发现无法通过rstrip()去除
        arg = arg[:-2]
    main(json.loads(arg))
