#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib -I/data/Software/mydan/Connector/private/lib
use strict;
use warnings;
use YAML::XS;
use Logs;
use LWP::UserAgent;

$| ++;

=head1 SYNOPSIS

    to => [ 'foo@open-c3.org', '123@open-c3.org' ],
    title => '',
    content => '',

=cut

my ( $usermail, %env );
BEGIN{
    use Configini;
    $usermail = Configini::get( 'usermail' );
    %env = Configini::env( 'usermailenv' );
};

return sub
{
    my %param = @_;

    my $ua = LWP::UserAgent->new;
    $ua->default_header( %env ) if %env;

    for my $to ( @{$param{to}} )
    {

        my $res = $ua->post(
            $usermail,
            Content => JSON::to_json( +{ user => $to, title => $param{title}, content => $param{content} } ), 
            'Content-Type' => 'application/json' 
        );

        if($res->is_success)
        {
            my $v = eval{decode_json $res->decoded_content};
            next if $v->{stat};
        }
        #TODO
        die "die" . YAML::XS::Dump $usermail;

    }

    return 1;
}
