#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

use LWP::UserAgent;
use JSON;
use URI::Escape;

=head1 SYNOPSIS

 $0

=cut

my $ua = LWP::UserAgent->new;
$ua->timeout( 30 );

my $url = sprintf "http://openc3-prometheus:9090/api/v1/query?query=%s", URI::Escape::uri_escape( 'max by(instance,mountpoint) (node_filesystem_size_bytes{mountpoint!~"/var.*",mountpoint!~"/mnt.*",mountpoint!~"/data/docker/containers.*",mountpoint!~"/run/containerd/.*",mountpoint!~"/run.*",mountpoint!~"/data/var/lib.*",mountpoint!~"/data/datas/docker.*"})/1024/1024/1024' );

my $res = $ua->get( $url );

die sprintf( "http code %s", $res->code ) unless $res->is_success;

my $v = eval{ JSON::decode_json $res->decoded_content };
die "data no JSON: $@"  if $@;
die "status no success" unless $v->{status} && $v->{status} eq 'success';

for my $x ( @{$v->{data}{result} })
{
    printf "$x->{metric}{instance}\t$x->{metric}{mountpoint}\t%0.2f\n", $x->{value}[1];
}
