#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

use LWP::UserAgent;
use JSON;

=head1 SYNOPSIS

 $0

=cut

my $ua = LWP::UserAgent->new;
$ua->timeout( 15 );

#100 - max(avg_over_time(aws_rds_free_storage_space_maximum[1w]) )by(instance) / max(avg_over_time(aws_rds_storage_space_allocated [1w])* 1024 * 1024 * 1024)by(instance) * 100
my $url = 'http://openc3-prometheus:9090/api/v1/query?query=100+-+max%28avg_over_time%28aws_rds_free_storage_space_maximum%5B1w%5D%29+%29by%28instance%29+%2F+max%28avg_over_time%28aws_rds_storage_space_allocated+%5B1w%5D%29*+1024+*+1024+*+1024%29by%28instance%29+*+100';

my $res = $ua->get( $url );

die sprintf( "http code %s", $res->code ) unless $res->is_success;

my $v = eval{ JSON::decode_json $res->decoded_content };
die "data no JSON: $@"  if $@;
die "status no success" unless $v->{status} && $v->{status} eq 'success';

for my $x ( @{$v->{data}{result} })
{
    printf "$x->{metric}{instance}\t%0.2f\n", $x->{value}[1];
}
