#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

use LWP::UserAgent;
use JSON;
use URI::Escape;

=head1 SYNOPSIS

 $0

=cut

my $ua = LWP::UserAgent->new;
$ua->timeout( 30 );

#my $url = sprintf "http://openc3-prometheus:9090/api/v1/query?query=%s", URI::Escape::uri_escape( 'avg by(instance)(avg_over_time(node_mem_memused_percent[1w]))' );
#my $url = sprintf "http://openc3-prometheus:9090/api/v1/query?query=%s", URI::Escape::uri_escape( 'round(sum((node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100) by (instance)) ' );
my $url = sprintf "http://openc3-prometheus:9090/api/v1/query?query=%s", URI::Escape::uri_escape( 'round(sum((avg_over_time(node_memory_MemTotal_bytes[1h]) - (avg_over_time(node_memory_MemFree_bytes[1h]) + avg_over_time(node_memory_Buffers_bytes[1h]) + avg_over_time(node_memory_Cached_bytes[1h]))) / avg_over_time(node_memory_MemTotal_bytes[1h]) * 100) by (instance))' );

my $res = $ua->get( $url );

die sprintf( "http code %s", $res->code ) unless $res->is_success;

my $v = eval{ JSON::decode_json $res->decoded_content };
die "data no JSON: $@"  if $@;
die "status no success" unless $v->{status} && $v->{status} eq 'success';

for my $x ( @{$v->{data}{result} })
{
    printf "$x->{metric}{instance}\t%0.2f\n", $x->{value}[1];
}
