#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

=head1 SYNOPSIS

 $0

=cut

my @col = qw( LoadBalancerArn 服务树 实例ID 业务负责人 );
my $col = join " ", @col;
my @x = `c3mc-device-data-get curr networking aws-alb $col`;
die "get data fail" if $?;
chomp @x;

my @mon = qw( last-hostcount avg-active );

my %mon;
for my $mon ( @mon )
{
    my @xx = `c3mc-mon-aws-alb-${mon}-dump`;
    die "get aws-alb $mon fail" if $?;
    chomp @xx;
    for ( @xx )
    {
        my ( $instance, $val ) = split /\t/, $_;
        $mon{$mon}{$instance} = $val;
    }
}

printf "%s\n", join "\t", @col, @mon;
for my $x ( @x )
{
    my ( $instance, @tmp ) = split /\t/, $x;
    $instance =~ s/^.+:loadbalancer\///g;
    printf "%s\n", join "\t", $instance, @tmp, map{ $mon{$_} && defined $mon{$_}{$instance} ? $mon{$_}{$instance} : 'unkown' }@mon;
}
