#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.clb.v20180317 import clb_client, models


def get(data, access_id, access_key, region):
    """
        输出 qcloud clb 的详情(json格式)
    """
    cred = credential.Credential(access_id, access_key)
    httpProfile = HttpProfile()
    httpProfile.endpoint = "clb.tencentcloudapi.com"

    clientProfile = ClientProfile()
    clientProfile.httpProfile = httpProfile
    client = clb_client.ClbClient(cred, region, clientProfile)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field networking qcloud-clb LoadBalancerId")

    status_code_m = {
        0: "创建中",
        1: "正常运行",
    }

    req = models.DescribeLoadBalancersRequest()
    params = {
        "LoadBalancerIds": [data[field_name]]
    }
    req.from_json_string(json.dumps(params))

    resp = client.DescribeLoadBalancers(req)
    for instance in resp.LoadBalancerSet:
        if instance.LoadBalancerId == data[field_name]:
            data = json.loads(str(instance))
            data["RegionId"] = region
            # 注意：此字段可能返回 null，表示取不到有效值。(摘自腾讯云文档)
            if "Status" in data and isinstance(data["Status"], int):
                data["StatusZhDesc"] = status_code_m[data["Status"]]
            return data
    raise Exception(
        "根据 LoadBalancerId {} 未找到 qcloud clb".format(data[field_name]))


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
