#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;
use Logs;
use Util;
use JSON;
use LWP::UserAgent;

$| ++;

=head1 SYNOPSIS

    id => 1,
    logs => 日志对象

=cut

return sub
{
    my ( %param, @list )= @_;
    my ( $db, $id, $logs ) = @param{qw( db id logs)};

    $logs = Logs->new( 'code.nodeinfo' ) unless $logs;

    $logs->die( "id not a number" ) unless $id =~ /^\d+$/;

    my @x = `c3mc-base-nodeinfo --col id,name,type,inip,exip $id`;
    chomp @x;
    for( @x )
    {
        my @t = split /;/, $_;
        push @list, +{ id => $t[0], name => $t[1], type => $t[2], inip => $t[3], exip => $t[4] };
    }
    my $i = @list;

    my $x = $db->query( "select name,inip,exip from openc3_job_nodelist where projectid in ( '$id', '0' ) and status='available'" );
    $logs->die( "get data error from db" ) unless defined $x && ref $x eq 'ARRAY';
    map{ push @list, +{ id => $i++, name => $_->[0], inip => $_->[1], exip => $_->[2], type => 'extend' }; }@$x;

    return @list;

}
