#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;
use Logs;
use Util;
use JSON;
use Encode;
use LWP::UserAgent;

$| ++;

=head1 SYNOPSIS

    id => 1,
    logs => 日志对象

=cut

return sub
{
    my ( %param, @list )= @_;
    my ( $db, $id, $logs ) = @param{qw( db id logs)};

    $logs = Logs->new( 'code.nodeinfo' ) unless $logs;

    $logs->die( "id not a number" ) unless $id =~ /^\d+$/;

    my $i = 1;
    my @x = `c3mc-base-fullnodeinfo --col id,name,type,inip,exip $id`;
    chomp @x;
    for( @x )
    {
        my @t = split /;/, $_;
        push @list, +{ id => $i++, name => Encode::decode( 'utf8', $t[1] ), type => $t[2], inip => $t[3], exip => $t[4] };
    }
    return @list;

}
