#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess
import re


sys.path.append("/data/Software/mydan/Connector/lib/pp")


def list_machine_types(cred_json_path, zone):
    from c3mc_cloud_google_compute import GoogleCompute
    return GoogleCompute(cred_json_path).list_machine_types(zone)


def my_sort(item):
    instance_type_parts = item["name"].split("-")
    name = "-".join(instance_type_parts[:-1])
    num = instance_type_parts[-1]
    if num.isdigit():
        num = int(num)
    else:
        parts = re.findall(r"\d+", num)
        num = None if len(parts) == 0 else int(parts[0])
    return (name, num, item["guestCpus"], item["memoryMb"])


def main(params):
    """查询谷歌云区域的机器类型列表
    """
    account = params["account"]
    zone = params["zone"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info google {account}")
    )

    data_list = list_machine_types(key_info["cred_path"], zone)

    data_list = sorted(data_list, key=my_sort)

    for item in data_list:
        item["memoryGB"] = item["memoryMb"] / 1024
        print(json.dumps(item, default=str))


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
