#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


def apply_cloud_certificate(params):
    data = """
        申请类型:   {},
        证书类型:   {},
        使用范围:   {},
        购买年限:   {},
        产品名称:   {},
        公司主体:   {},
        业务名称:   {},
        域名:       {},
        业务负责人:  {},
        运维负责人:  {},
        申请理由:    {}
    """.format(
        params["ApplyType"],
        params["CertificateType"],
        params["Target"],
        params["BuyYears"],
        params["ProductName"],
        params["Company"],
        params["BusinessNode"],
        params["DomainName"],
        params["YewuOwner"],
        params["OpsOwner"],
        params["ApplyNote"],
    )

    newline = "<br/>"
    data = data.replace("\n", newline)[len(newline):]

    tt_number = subprocess.run([
        "c3mc-create-ticket", 
        "--submit_user", "sys@app", 
        "--title", params["Title"], 
        "--ext_tt", params["IfExt"],
    ], 
    input=data.encode(), 
    stdout=subprocess.PIPE,
    ).stdout.decode('utf-8')
    return tt_number


def main(params):
    data = apply_cloud_certificate(params)
    print(data.rstrip())
    

if __name__ == '__main__':
    arg = sys.argv[1]
    if arg[-2:] == "\\n":
        # arg参数末尾可能带着\n后缀,测试发现无法通过rstrip()去除
        arg = arg[:-2]
    main(json.loads(arg))
