#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from huaweicloudsdkcore.auth.credentials import BasicCredentials
from huaweicloudsdkdds.v3.region.dds_region import DdsRegion
from huaweicloudsdkdds.v3 import *


def get(data, access_id, access_key, project_id, region):
    """
        输出huawei dds的详情(json格式)
    """
    if project_id == "None":
        project_id = None
    credentials = BasicCredentials(access_id, access_key, project_id) \

    client = DdsClient.new_builder() \
        .with_credentials(credentials) \
        .with_region(DdsRegion.value_of(region)) \
        .build()

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field database huawei-dds id")

    request = ListInstancesRequest()
    request.id = data[field_name]
    response = client.list_instances(request)
    for instance in response.instances:
        if instance.id == data[field_name]:
            return instance
    raise Exception("根据 instance_name {} 未找到dds".format(data[field_name]))


def main(data, access_id, access_key, project_id, region):
    data = get(data, access_id, access_key, project_id, region)
    print(str(data))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
