#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

=head1 SYNOPSIS

 $0 id;tagname id2;tagname2 .. idn;tagnamen

=cut

my %regex;
sub getregex
{
    my $id = shift @_;
    return $regex{$id} if defined $regex{$id};
    my $regex = `c3mc-base-db-get -t openc3_ci_project tag_regex -f 'id=$id'`;
    chomp $regex;

    return $regex{$id} = $regex;
}

my %follow;
sub follow
{
    my $id = shift @_;
    return $follow{$id} if defined $follow{$id};
    my @f = `c3mc-base-db-get -t openc3_ci_version name -f 'projectid=$id and status="success"'`;
    chomp @f;
    return $follow{$id} = +{ map{ $_ => 1 }@f };
}

sub igrep
{
    my $str = shift @_;
    my ( $id, $tag ) = split /;/, $str, 2;
    die "id err" unless $id =~ /^\d+$/;
    return unless my $regex = getregex( $id );
    if( $regex && $regex =~ /^ci:(\d+)$/ )
    {
        my $f = follow( $1 );
        print "$str\n" if $f->{$tag};
        return;
    }
    print "$str\n" if $regex eq '_NULL_' || $tag =~ /$regex/;
}

if( @ARGV ) { map{ igrep($_) }@ARGV; } else { while(<STDIN>){ chomp; igrep($_); } }
