#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

from huaweicloudsdkcore.auth.credentials import BasicCredentials
from huaweicloudsdkecs.v2.region.ecs_region import EcsRegion
from huaweicloudsdkecs.v2 import *


def get_ecs_by_name(access_id, access_key, region, instance_name):
    """
        输出huawei ecs的详情(json格式)
    """
    credentials = BasicCredentials(access_id, access_key) \

    client = EcsClient.new_builder() \
        .with_credentials(credentials) \
        .with_region(EcsRegion.value_of(region)) \
        .build()

    request = ListServersDetailsRequest()
    request.name = instance_name
    response = client.list_servers_details(request)
    for instance in response.servers:
        if instance.name == instance_name:
            return instance
    raise Exception("根据instance_name {} 未找到ecs".format(instance_name))


def main(access_id, access_key, region, instance_name):
    data = get_ecs_by_name(access_id, access_key, region, instance_name)
    print(str(data))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
