#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.auth.credentials import AccessKeyCredential
from aliyunsdkr_kvstore.request.v20150101.DescribeInstanceAttributeRequest import DescribeInstanceAttributeRequest


def get(data, access_id, access_key, region):
    """
        输出 aliyun redis 的详情(json格式)
    """
    credentials = AccessKeyCredential(
        access_id, access_key)
    client = AcsClient(region_id=region, credential=credentials)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field database aliyun-redis InstanceId")

    request = DescribeInstanceAttributeRequest()
    request.set_accept_format('json')
    request.set_InstanceId(data[field_name])

    response = client.do_action_with_exception(request)
    for instance in json.loads(response)["Instances"]["DBInstanceAttribute"]:
        if instance["InstanceId"] == data[field_name]:
            instance["Tag"] = instance["Tags"]["Tag"]
            instance.pop("Tags", None)
            return instance
    raise Exception(
        "根据 DBInstanceId {} 未找到 aliyun redis".format(data[field_name]))


def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
