#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_google_compute import GoogleCompute


def main(params):
    print("params = ", json.dumps(params), file=sys.stderr)

    if subprocess.getoutput("c3mc-sys-ctl sys.bpm.fake.run") == "1":
        # bpm虚假运行
        print("成功修改google vm实例类型, 响应为: xxxxxx")
        print("LOG. instance_id:xxxxxx")
        print("VAR. instance_id:xxxxxx")
    else:
        account = params["account"]
        instance_name = params["instance_id"].split("/")[0]
        zone = params["instance_id"].split("/")[1]
        instance_type = params["instance_type"]

        key_info = json.loads(subprocess.getoutput(
            f"c3mc-get-account-info google {account}"))

        client = GoogleCompute(key_info["cred_path"])
        client.set_machine_type(instance_name, zone, instance_type)

        print(f"VAR. 成功修改google vm实例类型")


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
