#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_qcloud_vpc import QcloudVpc


class Subnets:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.lib_client = self.create_lib_client()

    def create_lib_client(self):
        return QcloudVpc(self.access_id, self.access_key, self.region)
    
    def show(self, vpcId, zone):
        data_list = self.lib_client.list_subnets_of_vpc(vpcId, zone)
        data_list = sorted(data_list, key=lambda x: (x['SubnetName'].lower()), reverse=False)
        for item in data_list:
            print(json.dumps(item))


def main(params):
    account = params["account"]
    region = params["region"]
    zone = params["zone"] if "zone" in params else None
    vpcId = params["vpc_id"]

    keyInfo = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info qcloud {account}")
    )
    Subnets(keyInfo["access_id"], keyInfo["access_key"], region).show(vpcId, zone)


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
