#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def get_health_check_http_code_list():
    return [
        {
            "name": "1xx",
            "value": 1
        },
        {
            "name": "2xx",
            "value": 2
        },
        {
            "name": "3xx",
            "value": 4
        },
        {
            "name": "4xx",
            "value": 8
        },
        {
            "name": "5xx",
            "value": 16
        },
    ]


def main():
    data_list = get_health_check_http_code_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
