#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

import boto3


def describe_regions(access_id, access_key):
    """
        查询aws区域列表
    """
    for region in ["us-east-1", "cn-north-1"]:
        try:
            client = boto3.client(
                "ec2",
                aws_access_key_id=access_id,
                aws_secret_access_key=access_key,
                region_name=region
            )

            response = client.describe_regions(AllRegions=True)
            return response["Regions"]
        except Exception:
            continue
    raise Exception("未查询到区域列表")


def main(params):
    account = params["account"]

    key_info = json.loads(subprocess.getoutput(
        "c3mc-get-account-info aws {}".format(account)))

    region_list = describe_regions(
        key_info["access_id"], key_info["access_key"])
    for region in region_list:
        print(json.dumps(region, default=str))


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]))
