#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_aws_s3 import AWS_S3

def display(access_id, access_key):
    for region in ["us-east-1", "cn-north-1"]:
        try:
            names = AWS_S3(access_id, access_key, region).list_bucket_names()
            for name in sorted(names):
                print(name)
            break
        except Exception as e:
            continue 

def main(params):
    account = params["account"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info aws {account}")
    )
    display(key_info["access_id"], key_info["access_key"])


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
