#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json


def database_auth_list():
    return [
        {
            "value": "增加"
        },
        {
            "value": "删除"
        },
        {
            "value": "修改"
        },
        {
            "value": "查看"
        },
    ]


def main():
    data_list = database_auth_list()
    for item in data_list:
        print(json.dumps(item))


if __name__ == '__main__':
    main()
