#!/bin/bash

#domain=$(c3mc-sys-ctl sys.cluster.domain)
addr=$(cat .addr)

if [ "X" == "X$addr" ];then
    echo nofind .addr
    exit 1
fi
c3mc-mon-agent-install-errnode \
|sort -R    \
|head -n 10 \
|xargs -i{} /data/Software/mydan/dan/tools/rcall -r {} --timeout 300 exec "curl -L $addr/api/scripts/installAgentMon.sh |sudo OPEN_C3_ADDR=$addr bash"
