#!/bin/bash

#domain=$(c3mc-sys-ctl sys.cluster.domain)

addr=$(cat .addr)

if [ "X" == "X$addr" ];then
    echo nofind .addr
    exit 1
fi

export MYDan_Agent_Proxy_Addr=$addr/api/agent/proxy/0
export MYDan_Agent_Proxy_Header="appname:job,appkey:${OPEN_C3_RANDOM}"

c3mc-mon-agent-install-errver \
| c3mc-mon-ip2uexip \
| sort  -R    \
| head  -n 10 \
| xargs -P 2 -i{} bash -c "/data/Software/mydan/dan/tools/rcall -r {} --verbose  dump /data/Software/mydan/AGENT/scripts/agent.mon.tar.gz  --path /opt/mydan/dan/agent.mon.tar.gz|grep :ok && /data/Software/mydan/dan/tools/rcall -r {} --timeout 300 --env OPEN_C3_ADDR=local scripts /data/Software/mydan/AGENT/scripts/installAgentMon.sh"
