#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOBX/lib -I/data/Software/mydan/JOBX/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );
use Data::Dumper;

use Code;
use MYDan::Util::OptConf;

=head1 SYNOPSIS

 $0 [--uuid uuid] 

=cut
my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( uuid=s ) )->dump();
$option->assert( 'uuid' );

my $db = MYDB->new( "$RealBin/../conf/conn" );

Code->new( 'subtask' )->run( db => $db, %o );
