#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from qcloud_cos import CosConfig
from qcloud_cos import CosS3Client


def tag_add(data, access_id, access_key, region):
    service_domain = f'cos.{region}.myqcloud.com'
    config = CosConfig(Region=region, SecretId=access_id,
                       SecretKey=access_key, ServiceDomain=service_domain)  # 获取配置对象
    client = CosS3Client(config)

    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field storage qcloud-cos Name")

    tag_list = []
    try:
        response = client.get_bucket_tagging(Bucket=data[field_name])
        if "TagSet" in response and "Tag" in response["TagSet"]:
            tag_list = response["TagSet"]["Tag"]
    except Exception as e:
        if "NoSuchTagSet" not in str(e):
            raise e

    need_add_key = data["_control_"]["tag-add"]["key"]
    need_add_value = data["_control_"]["tag-add"]["value"]

    found = False
    for i in range(len(tag_list)):
        if tag_list[i]['Key'] == need_add_key:
            tag_list[i]['Value'] = need_add_value
            found = True
            break
    if not found:
        tag_list.append({
            'Key': data["_control_"]["tag-add"]["key"],
            'Value': data["_control_"]["tag-add"]["value"]
        })
    
    client.put_bucket_tagging(
        Bucket=data[field_name],
        Tagging={
            'TagSet': {
                'Tag': tag_list
            }
        }
    )


def main(data, access_id, access_key, region):
    tag_add(data, access_id, access_key, region)


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])
