#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use LWP::UserAgent;
use Util;
use JSON;
use Encode;
use IPC::Open3;

$| ++;

=head1 SYNOPSIS
    to => [ 'foo@job.com', '123@job.com' ],

    title => 'projectid: ${projectid} job ${status}',
    content => 'task ${uuid} :${status}',
    mesg => 'projectid=${projectid} taskuuid=${uuid}: ${status}',


=cut

return sub
{
    my %param = @_;
    printf "sendemail to: %s", join ',', @{$param{to}};

    return 1 unless @{$param{to}};

    my $pipe = sprintf "c3_connector_pp_sendmail %s --subject '%s'", join( ' ', @{$param{to}} ), $param{title};

    my $chld_in;
    my $pid = IPC::Open3::open3( $chld_in, '>&STDOUT', '>&STDERR', $pipe);

    my $content = $param{content};
    Encode::_utf8_off($content);
    print $chld_in $content;
    $chld_in = undef;
    waitpid( $pid, 0 );
    return $? ? 0 : 1;
}
