#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use LWP::UserAgent;
use Util;
use JSON;
use Encode;
use IPC::Open3;

$| ++;

=head1 SYNOPSIS

    to => [ 'foo@job.com', '123@job.com' ],

    mesg => 'projectid=${projectid} taskuuid=${uuid}: ${status}',


=cut

return sub
{
    my %param = @_;

    return 1 unless  @{$param{to}};

    my $pipe = sprintf "c3_connector_pp_sendmesg %s", join ' ', @{$param{to}};

    my $chld_in;
    my $pid = IPC::Open3::open3( $chld_in, '>&STDOUT', '>&STDERR', $pipe);

    my $content = $param{mesg};
    Encode::_utf8_off($content);
    print $chld_in $content;
    $chld_in = undef;
    waitpid( $pid, 0 );
    return $? ? 0 : 1;
}
