#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use Util;
use JSON;
use IPC::Open3;

$| ++;

=head1 SYNOPSIS

    to => [ 'foo@job.com', '123@job.com' ],

    title => 'projectid: ${projectid} job ${status}',
    content => 'task ${uuid} :${status}',
    mesg => 'projectid=${projectid} taskuuid=${uuid}: ${status}',


=cut

return sub
{
    my %param = @_;

    return 1 unless  @{$param{to}};

    my $pipe = "c3mc-base-send";
    my $pid = IPC::Open3::open3( my $chld_in, '>&STDOUT', '>&STDERR', $pipe);
    print $chld_in YAML::XS::Dump +{ mesg => $param{mesg}, to => $param{to} };
    $chld_in = undef;
    waitpid( $pid, 0 );
    warn "send mesg fail."  if $?;

    return 1;
}
