#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

import boto3


def create_instance_profile(access_id, access_key, region, instance_profile_name):
    """
        创建实例配置文件
    """
    client = boto3.client(
        "iam",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name=region
    )

    client.create_instance_profile(
        InstanceProfileName=instance_profile_name,
    )


def main(access_id, access_key, region, instance_profile_name):
    create_instance_profile(access_id, access_key,
                            region, instance_profile_name)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
