#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json


from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.auth.credentials import AccessKeyCredential
from aliyunsdkecs.request.v20140526.DescribeInstancesRequest import DescribeInstancesRequest


def get_ecs_by_id(access_id, access_key, region, instance_id):
    """
        输出aliyun ecs的详情(json格式)
    """
    credentials = AccessKeyCredential(access_id, access_key)
    client = AcsClient(region_id=region, credential=credentials)

    request = DescribeInstancesRequest()
    request.set_accept_format('json')
    request.set_InstanceIds([instance_id])

    response = client.do_action_with_exception(request)
    data = json.loads(response)
    if len(data["Instances"]["Instance"]) == 0:
        raise Exception("根据instance_id {} 未找到ecs".format(instance_id))
    return data["Instances"]["Instance"][0]


def main(access_id, access_key, region, instance_id):
    data = get_ecs_by_id(access_id, access_key, region, instance_id)
    print(json.dumps(data, default=str))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
