#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import os
import shutil
import subprocess
import sys
import hashlib


# 这种情况直接把 line 和 regin 拼接在一起
#
# 适用于 aliyun aws ksyun gcp
def create_ak_line_v1(line, region_list):
    parts = line.split()
    parts = [word.strip() for word in parts]

    if parts[-1] != "*":
        # 如果最后一位不是星号忽略该配置
        return []

    prefix = " ".join(parts[:-1])

    return [f"{prefix} {region}" for region in region_list]

# 这种情况是 line 最后有账号配置，而 region 应该配置在账号前面
#
# 适用于 qcloud huawei
def create_ak_line_v2(line, region_list):
    parts = line.split()
    ext_info = parts[-1]
    l = create_ak_line_v1(" ".join(parts[:-1]), region_list)
    return [f"{item} {ext_info}" for item in l]

def get_file_lines(file_path):
    if not os.path.exists(file_path):
        return []
    result = []
    with open(file_path, "r") as file:
        result.extend(line.rstrip('\n') for line in file)
    return result

def append_to_account_file(file_path, strings_list):
    if not os.path.exists(file_path):
        open(file_path, "w").close()

    with open(file_path, 'a') as file:
        for line in strings_list:
            file.write(line + '\n')

def save_account_file_with_md5(dir_path, strings_list):
    for element in strings_list:
        md5 = hashlib.md5(element.encode('utf-8')).hexdigest()
        
        file_path = os.path.join(dir_path, md5)
        if os.path.exists(file_path):
            continue
        
        os.makedirs(file_path)
        with open(os.path.join(file_path, 'data'), 'w') as f:
            f.write(element)


def get_ak_line_list(ext_account_path, cloud):
    result = {}
    ext_account_line_list = get_file_lines(ext_account_path)
    resource_codes = subprocess.getoutput(
        f"c3mc-cloud-get-resource-type-list {cloud}"
    ).split("\n")
    for resource_code in resource_codes:
        for ext_account_line in ext_account_line_list:
            region_list = []
            cmd_parts = [f"c3mc-cloud-{cloud}-region-list"]
            cmd_parts.extend(ext_account_line.split()[1:])
            cmd_parts.append(resource_code)

            output = subprocess.run(cmd_parts, capture_output=True, text=True)
            if output.returncode != 0:
                print(output.stderr, file=sys.stderr)
                exit(1)
            
            region_list = output.stdout.split("\n")
            region_list = list(filter(lambda x: x != "", region_list))

            ak_list = []
            if cloud in ["qcloud", "huawei"]:
                ak_list = create_ak_line_v2(ext_account_line, region_list)
            else:
                ak_list = create_ak_line_v1(ext_account_line, region_list)
            if len(ak_list) > 0:
                if resource_code not in result:
                    result[resource_code] = []
                result[resource_code].extend(ak_list)
    return result 

def create_cloud_ak_lines():
    dir_path = "/data/Software/mydan/AGENT/device/conf/account"
    ext_dir_path = "/data/Software/mydan/AGENT/device/conf/accountx"
    tmp_dir_path = "/data/Software/mydan/AGENT/device/conf/account/.tmp"

    account_uuid_dir_path = "/data/Software/mydan/AGENT/device/conf/accountuuid"

    if os.path.exists(tmp_dir_path):
        shutil.rmtree(tmp_dir_path)
    os.mkdir(tmp_dir_path)

    if not os.path.exists(account_uuid_dir_path):
        os.mkdir(account_uuid_dir_path)

    try:
        for cloud in ["aliyun", "aws", "google", "huawei", "ksyun", "qcloud"]:
            ext_account_path = os.path.join(ext_dir_path, f"{cloud}x")
            if not os.path.exists(ext_account_path):
                continue

            data = get_ak_line_list(ext_account_path, cloud)
            for resource_code in data:
                lines_list = data[resource_code]
                append_to_account_file(
                    os.path.join(tmp_dir_path, f"{cloud}.{resource_code}"),
                    lines_list,
                )
                # 以md5为名称保存ak账号信息
                save_account_file_with_md5(account_uuid_dir_path, lines_list)

        for filename in os.listdir(tmp_dir_path):
            src_file = os.path.join(tmp_dir_path, filename)
            dst_file = os.path.join(dir_path, filename)
            shutil.move(src_file, dst_file)
    except Exception as e:
        raise RuntimeError(f"同步云账号出错, err: {e}") from e
    finally:
        shutil.rmtree(tmp_dir_path)
    

def main():
    create_cloud_ak_lines()


if __name__ == '__main__':
    main()
