#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import os

from kscore.session import get_session


class Ksyun:
    def __init__(self, access_id, access_key, resource_type):
        self.access_id = access_id
        self.access_key = access_key
        self.resource_type = resource_type

    def list_kec_regions(self):
        s = get_session()
        client = s.create_client(
            "kec", ks_access_key_id=self.access_id, ks_secret_access_key=self.access_key, region_name="cn-beijing-6")

        try:
            response = client.describe_regions()
        except Exception as e:
            raise RuntimeError(
                f"拉取区域列表出错, ak: {self.access_id}, resource_type: {self.resource_type}"
            ) from e

        result = [item["Region"] for item in response["RegionSet"]]
        return sorted(result)

    def display(self):
        # 目前没有遇到不同资源区域不一致的问题
        regions = self.list_kec_regions()
        for region in regions:
            print(region)


def main(access_id, access_key, resource_type):
    Ksyun(access_id, access_key, resource_type).display()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
