#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json

from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.auth.credentials import AccessKeyCredential
from aliyunsdkecs.request.v20140526.DescribeRegionsRequest import DescribeRegionsRequest


class Aliyun:
    def __init__(self, access_id, access_key, resource_type):
        self.access_id = access_id
        self.access_key = access_key
        self.resource_type = resource_type

    def list_ecs_regions(self):
        credentials = AccessKeyCredential(self.access_id, self.access_key)
        client = AcsClient(region_id='cn-hangzhou', credential=credentials)

        request = DescribeRegionsRequest()
        request.set_accept_format('json')

        try:
            response = client.do_action_with_exception(request)
        except Exception as e:
            raise RuntimeError("拉取区域列表出错, ak: {}, resource_type: {}".format(self.access_id, self.resource_type)) from e

        result = []
        for item in json.loads(str(response, encoding='utf-8'))["Regions"]["Region"]:
            result.append(item["RegionId"])
        return sorted(result)

    def display(self):
        # 目前没有遇到不同资源区域不一致的问题
        regions = self.list_ecs_regions()
        for region in regions:
            print(region)


def main(access_id, access_key, resource_type):
    Aliyun(access_id, access_key, resource_type).display()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
