#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import requests
from bs4 import BeautifulSoup

sys.path.append("/data/Software/mydan/Connector/lib/pp")


class Huawei:
    def __init__(self, access_id, access_key, iam_user_id, resource_type):
        self.access_id = access_id
        self.access_key = access_key
        self.iam_user_id = iam_user_id
        self.resource_type = resource_type
        self.huawei_webpage = self.get_huawei_webpage()
        self.project_region_list = self.get_project_region_list()
    

    def get_huawei_webpage(self):
        # 华为云目前没有可以直接查询区域列表的接口, 这里使用爬虫从华为云官网文档获取区域
        url = 'https://developer.huaweicloud.com/endpoint?all'
        response = requests.get(url)
        return response.text


    def get_project_region_list(self):
        from c3mc_cloud_huawei_iam import HuaweiIam

        project_region_list = []
        official_ecs_region_list = self.list_webpage_regions("弹性云服务 ECS")
        for region in official_ecs_region_list:
            try:
                project_list = HuaweiIam(
                    self.access_id, self.access_key, region).list_projects()
                project_region_list.extend(
                    project.name for project in project_list if project.name not in ["cn-north-1", "cn-east-2"])
                return project_region_list
            except Exception as e:
                continue
        return project_region_list

    def list_webpage_regions(self, title):
        soup = BeautifulSoup(self.huawei_webpage, 'html.parser')
        target_div = soup.find('div', string=title)
        parent = target_div.find_parent()
        target_table = parent.find('table')

        result = []
        for row in target_table.find_all('tr'):
            i = 0
            for cell in row.find_all('td'):
                if i == 1:
                    result.append(cell.text)
                    break
                i += 1
        return sorted(result)

    def list_regions(self, title):
        webpage_region_list = self.list_webpage_regions(title)
        intersection = set(self.project_region_list) & set(webpage_region_list)
        return sorted(list(intersection))

    def display(self):
        regions = []

        if self.resource_type == "dds":
            regions = self.list_regions("文档数据库服务 DDS")
        elif self.resource_type == "ecs":
            regions = self.list_regions("弹性云服务 ECS")
        elif self.resource_type == "ecs-volume":
            regions = self.list_regions("云硬盘 EVS")
        elif self.resource_type == "elb":
            regions = self.list_regions("弹性负载均衡 ELB")
        elif self.resource_type == "nosql":
            regions = self.list_regions("云数据库 GaussDB NoSQL")
        elif self.resource_type == "obs":
            # obs属于全局资源，通过每个区域都可以拉取到所有其他区域的obs资源
            # 为了避免重复拉取资源，下面regions数组只保留一个元素
            # regions = self.list_regions("对象存储服务 OBS")
            regions = ["cn-north-4"]
        elif self.resource_type == "rds":
            regions = self.list_regions("云数据库 RDS")
        elif self.resource_type == "redis":
            regions = self.list_regions("分布式缓存服务 Redis")
        elif self.resource_type == "kafka":
            regions = self.list_regions("分布式消息服务 DMS")
        else:
            raise RuntimeError("不支持的资源类型")
        
        for region in regions:
            print(region)


def main(access_id, access_key, iam_user_id, resource_type):
    Huawei(access_id, access_key, iam_user_id, resource_type).display()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[5], sys.argv[6])
