#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")


def list_global_elastic_ips(cred_json_path):
    from c3mc_cloud_google_compute import GoogleCompute
    ip_info_list = GoogleCompute(cred_json_path).list_global_elastic_ips()
    return [item for item in ip_info_list if item["status"] == "RESERVED"]


def main(params):
    """查询谷歌云可用的启动磁盘列表
    """
    
    account = params["account"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info google {account}")
    )

    ip_info_list = list_global_elastic_ips(key_info["cred_path"])
    ip_info_list = sorted(ip_info_list, key=lambda x: (x['name'].lower()), reverse=False)

    for ip_info in ip_info_list:
        print(json.dumps(ip_info))


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
