#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")


def list_ssl_certificates(cred_json_path):
    from c3mc_cloud_google_compute import GoogleCompute
    ssl_certificates = GoogleCompute(cred_json_path).list_ssl_certificates()
    for i in range(len(ssl_certificates)):
        ssl_certificates[i].pop("certificate", None)
        ssl_certificates[i].pop("selfManaged", None)
    return ssl_certificates

def main(params):
    """查询证书列表
    """
    
    account = params["account"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info google {account}")
    )

    ssl_certificates = list_ssl_certificates(key_info["cred_path"])
    ssl_certificates = sorted(ssl_certificates, key=lambda x: (x['name']), reverse=False)

    for ssl_cert in ssl_certificates:
        print(json.dumps(ssl_cert))


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
