#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;

$|++;

use JSON;
use LWP::UserAgent;

=head1 SYNOPSIS

 $0
 $0 --close
 $0 id;taskuuid

id instance fingerprint startsAt  alertname 

=cut
use MYDan::Util::OptConf;
my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( close ) )->dump();

my @task;

if( @ARGV )
{
    @task = @ARGV;
}
else
{
    while(<STDIN>){ chomp; push @task, $_; }
}

$ENV{PATH} = "$ENV{PATH}:/data/Software/mydan/AGENT/pp";

sub updatehealing
{
    my ( $id, $instance, $fingerprint, $startsAt, $altername ) = split /;/, shift @_;
    return unless $id && $instance && $fingerprint && $startsAt && $altername;

    my @alters = `c3_agent_pp_current-alerts _`;
    chomp @alters;
    my %alters = map{ $_ => 1 }@alters;

    my $x = join ";", $instance, $fingerprint, $startsAt, $altername, 'UNKOWN';
    my $status = $alters{$x} ? 'fail' : 'success';
    return if ! $o{close} && $status ne 'success';
    system "c3_agent_pp_self-healing-settask $id --set \"healingstat='$status'\"";
}

map{ updatehealing( $_ )}@task;
