#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;

$|++;

use YAML::XS;

=head1 SYNOPSIS

 $0

=cut

local $/ = undef;
my @data = YAML::XS::Load( <STDIN> );
local $/ = "\n";

$ENV{PATH} = "$ENV{PATH}:/data/Software/mydan/AGENT/pp";

my @out;
sub adduser
{
    my $data = shift @_;
    return unless $data && ref $data eq 'HASH' && $data->{'labels.fromtreeid'} && $data->{'labels.fromtreeid'} =~ /^\d+$/;

    my @user = `c3_agent_pp_monitorusers user --filter 'projectid=$data->{"labels.fromtreeid"}'`;
    chomp @user;

    return unless @user;

    $data->{to} = \@user;
    push @out, $data;
}

map{ adduser($_ ) }@data;

print YAML::XS::Dump @out;
