#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;
use uuid;
use POSIX;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use MYDB;
use FindBin qw( $RealBin );
use MYDan::Util::OptConf;
use YAML::XS;
use Encode;
use MIME::Base64;
use LWP::UserAgent;
use JSON;
use IPC::Open3;

=head1 SYNOPSIS

 $0

=cut

local $/ = undef;
my @data = YAML::XS::Load( Encode::encode('utf8', <STDIN> ) );
local $/ = "\n";

$ENV{PATH} = "$ENV{PATH}:/data/Software/mydan/AGENT/pp";

my @out;
sub adduser
{
    my $data = shift @_;
    return unless $data && ref $data eq 'HASH' && $data->{'labels.fromtreeid'} && $data->{'labels.fromtreeid'} =~ /^\d+$/;

    my @user = `c3_agent_pp_monitorusers user --filter 'projectid=$data->{"labels.fromtreeid"}'`;
    chomp @user;

    next unless @user;

    $data->{to} = \@user;
    push @out, $data;

}

map{ adduser($_ ) }@data;

print YAML::XS::Dump @out;
