#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use Encode;
use YAML::XS;
use MYDan::Util::OptConf;
use MYDan::Agent::Proxy;
use Util;

=head1 SYNOPSIS

 $0 ip1 ip2 ... ipn
 $0 ip1 ip2 ... ipn --output /path/foo.yaml

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( output=s ) )->dump();

my %env = Util::envinfo( qw( appname appkey ) );
$ENV{MYDan_Agent_Proxy_Addr} = "http://api.agent.open-c3.org/proxy/0";
$ENV{MYDan_Agent_Proxy_Header} = "appname:$env{appname},appkey:$env{appkey}";

my $proxy = MYDan::Agent::Proxy->new();

my @ip;

if( @ARGV )
{
    @ip = @ARGV;
}
else
{
    while(<STDIN>){ chomp; push @ip, $_; }
}

my %proxy = $proxy->search( @ip );

if( $o{output} )
{
    YAML::XS::DumpFile "$o{output}.tmp", \%proxy;
    rename "$o{output}.tmp", $o{output} or die "rename fail: $!";
    exit;
}

print YAML::XS::Dump \%proxy;
