#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/AGENT/lib -I/data/Software/mydan/AGENT/private/lib
use strict;
use warnings;

$|++;

use FindBin qw( $RealBin );
use YAML::XS;

=head1 SYNOPSIS

 $0

=cut

my %conf;
while(<STDIN>){
    chomp;
    my $c = $_;
    if( $c && $c !~ /'/ )
    {
        $conf{$c} = 1;
    }
    else { warn "conf: $c"; }
}

sub get
{
    my %has;
    my @ps = `docker ps`;
    chomp @ps;
    my @name = map{ my ( $x )= reverse split /\s+/, $_;$x }@ps;
    map{ $has{$_} = 1 if /^openc3-redis-exporter-(\d+\.\d+\.\d+\.\d+-\d+)$/; }@name;
    return %has;
}

my %has = get();

sub run
{
    my ( $conf, $has ) = @_;

    die "format err" unless $conf && $conf =~ /(\d+\.\d+\.\d+\.\d+:\d+)/;
    my $name = $1;
    $name =~ s/:/-/;
    $name = "openc3-redis-exporter-$name";
    delete $has->{$name};
}

map{ run( $_, \%has ); }keys %conf;

map{
    system "docker stop $_ >/dev/null";
    system "docker rm $_ >/dev/null";
}keys %has;
