#Author: lijinfeng2011@gmail.com

FROM openc3/basev2:t2204065
MAINTAINER lijinfeng2011

#RUN sed -i 's/www.cpan.org/mirrors.163.com\/cpan/' /root/.cpan/CPAN/MyConfig.pm
#RUN curl -L http://installbj.mydan.org | MYDanInstallLatestVersion=1 bash

ADD make.sh /make.sh
ADD ./temp/my.cnf /my.cnf

ADD ./temp/Connector /data/Software/mydan/Connector
ADD ./temp/MYDan     /data/Software/mydan/MYDan
ADD ./temp/JOBX      /data/Software/mydan/JOBX
ADD ./temp/JOB       /data/Software/mydan/JOB
ADD ./temp/AGENT       /data/Software/mydan/AGENT
ADD ./temp/CI       /data/Software/mydan/CI
ADD ./temp/c3-front       /data/Software/mydan/c3-front
ADD ./temp/web-shell       /data/Software/mydan/web-shell

ADD ./temp/init.sql /tmp/init.sql

ADD ./temp/install-cache-bin/kubectl  /usr/bin/kubectl
ADD ./temp/install-cache-bin/json2yaml  /usr/bin/json2yaml
ADD ./temp/install-cache-bin/yaml2json  /usr/bin/yaml2json

ADD ./temp/CI/bin/aws_c3 /usr/local/bin/aws_c3

RUN /make.sh

ADD entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
