#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import subprocess


def main():
    bl_mode = subprocess.getoutput("c3mc-sys-ctl sys.bl.mode").strip()
    if bl_mode == 'none' or bl_mode == '':
        return

    user = subprocess.getoutput("c3mc-sys-ctl sys.bl.sync.{}.admin.user".format(bl_mode)).strip()
    passwd = subprocess.getoutput("c3mc-sys-ctl sys.bl.sync.{}.admin.pass".format(bl_mode)).strip()
    url = subprocess.getoutput("c3mc-sys-ctl sys.bl.sync.{}.url".format(bl_mode)).strip()
    app_key = os.getenv("OPEN_C3_RANDOM")


    command = "/data/Software/mydan/Connector/bl/sync/{}/{}".format(bl_mode, bl_mode)

    os.system("{} {} {} {} {} {}".format(command, user, passwd, url, "job", app_key))
    

if __name__ == '__main__':
    main()
