#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );

=head1 SYNOPSIS

 $0

=cut

$0 = 'ci_server_build';

$ENV{PATH} = "$ENV{PATH}:/data/Software/mydan/CI/pp";

chdir "$RealBin/.." or die "chdir err";

my $cmd = join '|', (
    "c3_ci_pp_versions projectid uuid --filter \"status='init' and pid is null order by id\"",
    "c3_ci_pp_grepitask",
    "awk -F';' '{print \$2}'",
    "xargs -i{} bash -c \"$RealBin/../bin/build --uuid {} 2>&1|c3_ci_pp_addtime > logs/build/{} 2>&1\"",
);
while(1)
{
    my $time = time;
    warn "[DEBUG]run build server: $cmd\n" if $ENV{DEBUG};
    system $cmd;
    my $due = $time + 3 - time;

    warn "[WARN] build server timeout $due sec" if $due < 0;
    sleep $due if $due > 0;
}
