#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );

=head1 SYNOPSIS

 $0

=cut

$0 = 'ci_server_findtags';

$ENV{PATH} = "$ENV{PATH}:/data/Software/mydan/CI/pp";

chdir "$RealBin/.." or die "chdir err";

sub runauto
{
    my $cmd = join '|', (
        "c3_ci_pp_projects id --filter 'status=1 and autofindtags=1'",
        "sort",
        "c3_ci_pp_grepitask",
        "c3_ci_pp_setproject --set \"slave='openc3-srv-docker'\"",
        "xargs -P 10 $RealBin/../bin/findtags",
    );
    while(1)
    {
        my $time = time;
        warn "[DEBUG]run auto: $cmd\n" if $ENV{DEBUG};
        system $cmd;
        my $due = $time + 60 - time;
        sleep $due if $due > 0;
    }
}

sub runonce
{
    my $cmd = join '|', (
        "c3_ci_pp_projects id --filter 'status=1 and findtags_at_once=1'",
        "sort",
        "c3_ci_pp_grepitask",
        "c3_ci_pp_setproject --set \"findtags_at_once=0,slave='openc3-srv-docker'\"",
        "xargs -P 10 $RealBin/../bin/findtags",
    );
    while(1)
    {
        my $time = time;
        warn "[DEBUG]run once: $cmd\n" if $ENV{DEBUG};
        system $cmd;
        my $due = $time + 3 - time;
        sleep $due if $due > 0;
    }
}

fork ? runonce() : runauto();
