#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use MYDB;
use FindBin qw( $RealBin );
use Carp;

=head1 SYNOPSIS

 $0

=cut

$0 = 'ci_server_keepalive';

$ENV{PATH} = "$ENV{PATH}:/data/Software/mydan/CI/pp";

sub keepalive
{
    my %param = @_;

    my ( $myname, $db ) = ( `c3_ci_pp_who`, $param{db} );

    eval{ $db->execute( sprintf "replace into openc3_ci_keepalive (`slave`,`time`) values( '$myname','%d')", time ); };
    confess( "update keepalive fail: $@" ) if $@;

    sleep 3;

    while( 1 )
    {
        print "do ...\n";
        eval{ $db->execute( sprintf "update openc3_ci_keepalive set time='%d' where slave='$myname'", time );};
        confess( "update keepalive fail: $@" ) if $@;

        sleep 45;
    }
}

my $db = MYDB->new( "$RealBin/../conf/conn" );
keepalive( db => $db );
