#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess
import boto3
import warnings

warnings.filterwarnings("ignore", message="Boto3 will no longer support Python 3.7")

def get(data, access_id, access_key, region):
    """
    输出 AWS Global Accelerator 的详情(json格式)
    """
    client = boto3.client(
        "globalaccelerator",
        aws_access_key_id=access_id,
        aws_secret_access_key=access_key,
        region_name='us-west-2',  
    )

    arn_field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field networking aws-globalaccelerator AcceleratorArn"
    )

    response = client.describe_accelerator(
        AcceleratorArn=data[arn_field_name]
    )

    accelerator = response['Accelerator']

    # 获取 tags
    tags_response = client.list_tags_for_resource(
        ResourceArn=accelerator['AcceleratorArn']
    )
    accelerator['Tags'] = tags_response['Tags']

    return accelerator

def main(data, access_id, access_key, region):
    data = get(data, access_id, access_key, region)
    print(json.dumps(data, default=str))

if __name__ == "__main__":
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise RuntimeError("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2], sys.argv[3], sys.argv[4])