#!/bin/bash

set -e

name=$(c3mc-sys-ctl sys.backup.name|grep -E "^[a-zA-Z0-9]+$")
if [ -z "$name" ]; then
    exit
fi

mkdir -p /data/open-c3-data/private

c3version=$(cat /data/Software/mydan/Connector/.versionname|grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$")

uuid=$(date +%y%m%d.%H%M%S)

/data/Software/mydan/Connector/maintain/dump-1-base.sh $uuid
/data/Software/mydan/Connector/maintain/dump-2-db.sh   $uuid

path=/data/open-c3-data/glusterfs/backup/c3maintain
mkdir -p $path
file="$path/c3-$name-$c3version-$uuid.tar.gz"

cd /data/open-c3-data/glusterfs && tar -zcvf $file maintain-$uuid
rm -rf maintain-$uuid

url=$(  c3mc-sys-ctl sys.backup.url   | grep -E "^http[s]*://[a-zA-Z0-9\.\/\-]+$")
token=$(c3mc-sys-ctl sys.backup.token | grep -E "^[a-zA-Z0-9]{32}$"              )

if [[ -z "$url" || -z "$token" ]]; then
    exit
fi

curl -X POST $url?checkmd5=$(md5sum $file|awk '{print $1}') -F "file=@$file" -H "token: $token"
