#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;

$|++;

=head1 SYNOPSIS

 $0 id1 id2 ... idn

=cut

sub get
{
    my $id = shift;
    die "id err" unless $id =~ /^\d+$/;

    system "c3mc-base-db-get  -t openc3_ci_project -y id status autofindtags callonlineenv calltestenv findtags_at_once autobuild name excuteflow calljobx calljob webhook webhook_password webhook_release rely buildimage buildscripts follow_up follow_up_ticketid callback groupid tag_regex addr  ticketid notify slave last_findtags last_findtags_success edit_user edit_time -f 'id=$id'";
}

if( @ARGV ) { map{ get($_) }@ARGV; } else { while(<STDIN>){ chomp; get($_); } }
