#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;
use utf8;
use YAML::XS;

=head1 SYNOPSIS

 $0
 $0 time|curr type subtype col1 ... coln

=cut

my ( $curr, $type, $subtype, @col ) = @ARGV;
die "argv err" unless @col;


my $path = $curr eq 'curr' ? 'curr' : "timemachine/$curr";

my ( $file, $colmap ) = map{ "/data/open-c3-data/device/$path/$type/$subtype/$_" }qw( data.tsv colmap.yml );
die "no data" unless -f $file;

if( -f $colmap )
{
    my $x = eval{ YAML::XS::LoadFile $colmap };
    die "load colmap fail: $@" if $@;
    @col = map{ $x->{$_} || $_ }@col;
}

my    @data  = `c3mc-device-cat $curr $type $subtype`;
chomp @data;

exit unless @data;

my $title = shift @data;

utf8::decode( $title );
my @title = split /\t/, $title;

map{ utf8::decode( $_ ); }@col;

for my $data ( @data )
{
     my @d = split /\t/, $data;
     my %d = map{ $title[ $_ ] => $d[ $_ ] } 0 .. @title - 1;
     printf "%s\n", join "\t", map{ $_ // '' } @d{@col};
}
