#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib
use strict;
use warnings;
use File::Temp;
use MYDB;

$|++;

=head1 SYNOPSIS

 $0

=cut

my $db = MYDB->new( "/data/Software/mydan/AGENT/conf/conn" );

my @col = qw( id name type config edit_time );
my $r = eval{ $db->query( sprintf("select %s from openc3_monitor_cloudmon order by id", join ',', @col ), \@col ); };   

sub dumpfile
{
    my ( $dist, $data ) = @_;
    my $tmp = File::Temp->new( SUFFIX => ".cloudmon_tmp", UNLINK => 0 );
    print $tmp $data;
    close $tmp;
    system "rm -rf '$dist'" if -d $dist;
    system sprintf "mv '%s' '$dist'",$tmp->filename;
    system "chmod a+r '$dist'";
}
sub srv
{
    my $x = shift @_;
    my $pluginDir = "/data/Software/mydan/AGENT/cloudmon/exporter/$x->{type}";

    unless( -d $pluginDir )
    {
        warn "unkown cloudmon plugin in id: $x->{id}";
        return;
    }

    my $tpl = `cat $pluginDir/openc3_cloudmon_sd.tpl.yml`;
    $tpl =~ s/\$\{cloudmonid\}/$x->{id}/g;
    my $name = $x->{name} =~ /^[a-zA-Z0-9][a-zA-Z0-9\.\-_]+$/ ? $x->{name} : 'unkown';
    $tpl =~ s/\$\{cloudmonname\}/$name/g;
    return $tpl;
}

my @srv = grep{ $_ }map { srv( $_ ); }@$r;

dumpfile( "/data/Software/mydan/prometheus/config/openc3_cloudmon_sd.yml", join "\n", '---', @srv );
system "curl -XPOST http://openc3-prometheus:9090/-/reload"
