#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

use JSON;
use YAML::XS;
use MYDan::Util::OptConf;
use LWP::UserAgent;

=head1 SYNOPSIS

 $0 --treeid id

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( treeid=i ) )->dump();
$option->assert(qw( treeid ));

my $ua = LWP::UserAgent->new();
$ua->agent('Mozilla/9 [en] (Centos; Linux)');
$ua->timeout( 15 );

my $conf = YAML::XS::LoadFile "/data/open-c3-data/ldctl.conf";
my ( $env, $url ) = @$conf{qw( env url )};

$ua->default_header( %$env );
my $cont = JSON::encode_json( +{ name => "sys.exctl.".time } );

my $res = $ua->post( "$url/api/ci/group/$o{treeid}", Content => $cont, 'Content-Type' => 'application/json');

my $err = sprintf "call fail:\n%s\n", YAML::XS::Dump $res;
$err =~ s/appkey:\s+['"]?[a-zA-Z0-9]{32}['"]?\b/appkey: ******/g;

die sprintf( "$err: code %s", $res->code ) unless $res->is_success;
my $v = eval{JSON::decode_json $res->decoded_content};
die sprintf( "$err: data no JSON: $@" )if $@;

die $err unless $v->{stat};
print $v->{id}, "\n";
