#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

use YAML::XS;

=head1 SYNOPSIS

 $0

=cut

local $/ = undef;
my @data = YAML::XS::Load( <STDIN> );
local $/ = "\n";

my @out;
sub adduser
{
    my $data = shift @_;
    die "account error" unless $data && ref $data eq 'HASH' && $data->{'labels.account'} && $data->{'labels.account'} =~ /^[a-zA-Z0-9][a-zA-Z0-9\.\-_]*$/;
    my $config = eval{ YAML::XS::LoadFile "/data/glusterfs/mailmon/conf/$data->{'labels.account'}"; };
    die "load config conf/$data->{'labels.account'} fail: $@" if $@;

    my $to = $config->{to};
    if( $config->{subscribe} && ref $config->{subscribe} eq 'ARRAY' )
    {
        for my $x ( @{$config->{subscribe}} )
        {
            next unless $x && ref $x eq 'HASH' && $x->{to} && $x->{sendto};
            if( $x->{to} eq $data->{'labels.to'} )
            {
                $to = $x->{to};
                last;
            }
        }
    }

    die "to error" unless $to && $to =~ /^[a-zA-Z0-9\.\-_@]+$/;

    my @user = `c3mc-app-usrext '$to'`;
    chomp @user;

    return unless @user;

    $data->{to} = \@user;

    push @out, $data;
}

map{ adduser($_ ) }@data;

print YAML::XS::Dump @out;
