#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib -I/data/Software/mydan/Connector/private/lib
use strict;
use warnings;
use POSIX;

$|++;

while(<>)
{
    map{printf "%s %s\n", POSIX::strftime( "%Y-%m-%d %H:%M:%S", localtime ), $_ }split /\r|\n/, $_;
}
