#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib
use strict;
use warnings;

$|++;

use YAML::XS;
use uuid;
use POSIX;
use Time::Local;

=head1 SYNOPSIS

 $0

=cut

local $/ = undef;
my @data = YAML::XS::Load( <STDIN> );
local $/ = "\n";

sub gettime
{
    my $t = shift;
    return $t unless $t =~ /^(\d+)-(\d+)-(\d+)T(\d+):(\d+):(\d+)\.\d+Z$/;
    my $x = timelocal($6,$5,$4,$3,$2-1,$1);
    return POSIX::strftime( "%Y-%m-%dT%H:%M:%S", localtime( $x + 8 * 3600) );
}

my @out;
sub adduser
{
    my $data = shift @_;
    unless( $data && ref $data eq 'HASH'
        && defined $data->{'fingerprint'         } && $data->{'fingerprint'         } =~ /^[a-zA-Z0-9]+$/
        && defined $data->{'startsAt'            } && $data->{'startsAt'            } =~ /^[a-zA-Z0-9:\.\-]+$/
        && defined $data->{'labels.fromtreeid'   } && $data->{'labels.fromtreeid'   } =~ /^\d+$/
    )
    {
        push @out, $data;
        return;
    }

    my $caseuuid = join '.',$data->{'fingerprint'}, gettime( $data->{'startsAt'} );
    my $treeid   = $data->{'labels.fromtreeid'};
    my $uuid     = uuid->new()->create_str;
    my $time     = time;

    my @acked = `c3mc-base-db-get id --table openc3_monitor_ack_active --filter "(uuid='$data->{fingerprint}' or uuid='$caseuuid' ) and type='G' and expire>$time"`;
    return if @acked;

    $data->{ack} = $uuid;
    $data->{c3monitormsguuid} = $caseuuid;

    my $labels = join ',', map{ "$_=$data->{$_}" }sort grep{ /^annotations/ || /^labels/}keys %$data;
    $labels =~ s/'|"//g;
    system "c3mc-base-db-ins -t openc3_monitor_ack_table fingerprint '$data->{fingerprint}' caseuuid '$caseuuid' ackuuid '$uuid' treeid '$treeid' labels '$labels'";
    push @out, $data;
}

map{ adduser($_ ) }@data;

print YAML::XS::Dump @out;
