#!/bin/bash

set -e

name=$(c3mc-sys-ctl sys.backup.name|grep -E "^[a-zA-Z0-9]+$")
if [ -z "$name" ]; then
    exit
fi

c3version=$(cat /data/Software/mydan/Connector/.versionname|grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$")

uuid=$(date +%y%m%d.%H%M%S)

dbfile=/data/open-c3-data/backup/mysql/openc3.${uuid}.sql
docker exec -i openc3-mysql mysqldump -h127.0.0.1 -uroot -popenc3123456^! --databases jobs jobx ci agent connector > $dbfile

path=/data/open-c3-data/backup/c3sys
mkdir -p $path
file="$path/c3-$name-$c3version-$uuid.tar.gz"

tar -zcvf $file $dbfile \
    /data/Software/mydan/Connector/config.ini/current \
    /data/open-c3-data/sysctl.conf \
    /data/Software/mydan/etc/agent/auth 

url=$(c3mc-sys-ctl sys.backup.url|grep -E "^http[s]*://[a-zA-Z0-9\.\/\-]+$")
token=$(c3mc-sys-ctl sys.backup.token | grep -E "^[a-zA-Z0-9]{32}$")

if [[ -z "$url" || -z "$token" ]]; then
    exit
fi

curl -X POST $url?checkmd5=$(md5sum $file|awk '{print $1}') -F "file=@$file" -H "token: $token"
