#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

sys.path.append("/data/Software/mydan/Connector/lib/pp")


def main(access_id, access_key, region):
    from c3mc_cloud_aws_elasticache import Elasticache
    client = Elasticache("redis", access_id, access_key, region)
    client.show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
