#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib
use strict;
use warnings;

$|++;

use Encode;
use YAML::XS;
use OPENC3::SysCtl;

=head1 SYNOPSIS

 $0 # dump
 $0 datakey

=cut

my $conf = OPENC3::SysCtl->new()->dump();

if( my $k = shift @ARGV )
{
    $k = Encode::decode('utf8', $k );
    print Encode::encode('utf8', $conf->{$k} ), "\n";
    exit;
}
map{ print Encode::encode('utf8', "$_: $conf->{$_}" ), "\n"; }keys %$conf;
