#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use YAML::XS;
use Encode;
use JSON;

=head1 SYNOPSIS

 echo 'project yaml' | $0

=cut

local $/ = undef;
my %project = %{ YAML::XS::Load( Encode::encode('utf8', <STDIN> ) ) };
local $/ = "\n";

my ( $username, $pass );

my ( $id, $ticketid, $addr ) = @project{qw( id ticketid addr )};
$addr =~ s/^harbor://;

if( $ticketid )
{
    my $x = `c3mc-base-db-get -t openc3_ci_ticket ticket --filter "id='$ticketid' and type='UsernamePassword'"`;
    chomp $x;
    ( $username, $pass ) = split /_:separator:_/, $x if $x;
}

my $ctrl = $pass ? "curl -u '$username:$pass'" : 'curl';

my @list;
eval{
    alarm 30;
    my $str = `$ctrl '$addr' 2>/dev/null`;
    my $data = eval{JSON::from_json $str};
    map{ push @list, $_->{name} }@$data;
    alarm 0;
};

map{ print "$id;$_\n" }@list;
