#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import json

import boto3


class Ec2:
    def __init__(self, access_id, access_key, region):
        self.access_id = access_id
        self.access_key = access_key
        self.region = region
        self.client = self.create_client()
        self.page_size = 25

    def create_client(self):
        client = boto3.client(
            "ec2",
            aws_access_key_id=self.access_id,
            aws_secret_access_key=self.access_key,
            region_name=self.region,
        )
        return client

    def get_instances_from_response(self, response_data):
        instances = []
        for reservation in response_data["Reservations"]:
            for instance in reservation["Instances"]:
                name = None
                hostname = None
                product_owner = None
                department = None
                ops_owner = None
                for tag in instance["Tags"]:
                    if tag["Key"].lower() == "name":
                        name = tag["Value"]
                    if tag["Key"].lower() == "hostname":
                        hostname = tag["Value"]
                    if tag["Key"].lower() == "productowner":
                        product_owner = tag["Value"]
                    if tag["Key"].lower() == "department":
                        department = tag["Value"]
                    if tag["Key"].lower() == "opsowner":
                        ops_owner = tag["Value"]

                if name is not None:
                    instance["Name"] = name
                if hostname is not None:
                    instance["Hostname"] = hostname
                if product_owner is not None:
                    instance["ProductOwner"] = product_owner
                if department is not None:
                    instance["Department"] = department
                if ops_owner is not None:
                    instance["OpsOwner"] = ops_owner

                instance["RegionId"] = instance["Placement"]["AvailabilityZone"][:-1]
                instances.append(instance)
        return instances

    def get_response(self):
        response = self.client.describe_instances(MaxResults=self.page_size)
        results = self.get_instances_from_response(response)
        while "NextToken" in response:
            response = self.client.describe_instances(
                MaxResults=self.page_size, NextToken=response["NextToken"])
            results.extend(self.get_instances_from_response(response))
        return results

    def show(self):
        instance_list = self.get_response()
        for instance in instance_list:
            print(json.dumps(instance, default=str))


def main(access_id, access_key, region):
    ec2 = Ec2(access_id, access_key, region)
    ec2.show()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
