#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

binmode STDIN,  ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use YAML::XS;
use MYDan::Util::OptConf;

=head1 SYNOPSIS

 prefix match

 $0 ip1 ip2 ... ipn --filter 10.10,12,122,

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw(   filter=s ) )->dump();
        $option->assert(qw( filter )   );

my @ip;

if( @ARGV )
{
    @ip = @ARGV;
}
else
{
    while(<STDIN>){ chomp; push @ip, $_; }
}

my @filter = split /,/, $o{filter};

for my $ip ( @ip )
{
    next unless $ip =~ /^\d+\.\d+\.\d+\.\d+$/;
    for my $f ( @filter )
    {
        if( 0 == index $ip, $f )
        {
            print "$ip\n";
            last;
        }
    }
}
