#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/Connector/lib
use strict;
use warnings;

use OPENC3::PP::Exec;
use OPENC3::PP::Server;

=head1 SYNOPSIS

 $0 servername

=cut

$|++;
my $name = shift @ARGV;
my %help = (
    promesd => 'make openc3_node_sd.yml to prometheus',
    sender => 'sender mesg from alertmanager',
);

unless( $name )
{
    map{ print "\$0 $_ # $help{$_}\n" }keys %help;
    exit;
}

if( $name eq 'promesd' )
{
    if( -f "/data/open-c3-data/promesd.off" ) {
        $0 = "agent_server_$name";
        warn ">> skip by /data/open-c3-data/promesd.off\n";
        sleep 10*365*86400;
        exit;
    }

    my $nodetemp = "/data/Software/mydan/AGENT/conf/promesd.temp";
    my $tempfile = "$nodetemp.$$";

    OPENC3::PP::Server->new(
        name => "agent_server_$name",
        interval => 1800,
        timeout => 3600,
    )->run(
       "c3mc-base-treemap | awk -F';' '{print \$1}'| c3mc-base-fullnodeinfo -c projectid,inip | tee $tempfile | c3mc-mon-nodesd-format --output /data/Software/mydan/prometheus/config/openc3_node_sd.yml",
       "mv $tempfile $nodetemp",
    );
}

if( $name eq 'rule' )
{
    OPENC3::PP::Server->new(
        name => "agent_server_$name",
        interval => 60,
        timeout => 120,
    )->run(
        "c3mc-mon-rule --output /data/Software/mydan/prometheus/config/openc3_rule.yml",
        "curl -XPOST http://OPENC3_PROMETHEUS_IP:9090/-/reload 2>/dev/null",
    );
}

if( $name eq 'sender' )
{
    chdir "/data/open-c3-data/monitor-sender" or die "chdir fail: $!";
    map{ die if system "mkdir -p  $_"; }qw( zsucc zfail run );

    OPENC3::PP::Server->new(
        name => "agent_server_$name",
        interval => 6,
        timeout => 60,
    )->run( "ls *.wait 2>/dev/null| xargs -P 5 -i{} bash -c \"c3mc-mon-sender {}\"" );
}
