#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;
use POSIX;

$|++;

my $name = $ENV{C3APPNAME} ? "[$ENV{C3APPNAME}] " : "";

while(<>)
{
    map{printf "%s $name%s\n", POSIX::strftime( "%Y-%m-%d %H:%M:%S", localtime ), $_ }split /\r|\n/, $_;
}
