#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;
use YAML::XS;
use POSIX;

$| ++;

my $dpath = "/data/glusterfs/gitreport";
system "rm $dpath/*/current_ 2>/dev/null";
my $idcmd = "c3mc-base-db-get -t openc3_ci_project groupid -f 'status=1 and addr like \"%git%\"' |sort|uniq";

die if system "$idcmd | xargs -i{} bash -c \"mkdir -p $dpath/{}; c3mc-ci-gitreport-once {} > $dpath/{}/current_\"";

system "c3mc-app-merge-report -p $dpath";

for my $p ( glob "$dpath/*" )
{
    next unless $p =~ /\/\d+$/;
    system -f "$p/current_" ? "mv '$p/current_' '$p/current'" : "echo > $p/current";
}

my $dstpath = "$dpath/4000000000";
system "mkdir -p '$dstpath'" unless -d $dstpath;
system "cat $dpath/*/current |sort|uniq > $dstpath/current_ && mv $dstpath/current_ $dstpath/current";

if( 1 == POSIX::strftime( "%u", localtime ) )
{
    my $date = POSIX::strftime( "%Y-%m-%d", localtime( time - 86400 ) ) ;
    system "cd $dpath && ls |grep -E '^[0-9]+\$' | xargs -i{} bash -c \"cp $dpath/{}/current $dpath/{}/$date.week\"";
}

if( 10 == POSIX::strftime( "%d", localtime ) )
{
    my $year = POSIX::strftime( "%Y", localtime( time - ( 30 * 86400 )) );
    my $month = POSIX::strftime( "%Y-%m", localtime( time - ( 30 * 86400 )) );

    system "cd $dpath && ls |grep -E '^[0-9]+\$' | xargs -i{} bash -c \"cat $dpath/{}/$year-*.week|grep ^$month > $dpath/{}/$month.month\"";
    system "cd $dpath && ls |grep -E '^[0-9]+\$' | xargs -i{} bash -c \"cat $dpath/{}/$year-*.month > $dpath/{}/$year.year\"";
}
