#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib
use strict;
use warnings;

binmode STDIN, ':utf8';
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

$|++;

use YAML::XS;
use Encode;
use Temp;

=head1 SYNOPSIS

 echo 'project yaml' | $0

=cut

local $/ = undef;
my %project = %{ YAML::XS::Load( Encode::encode('utf8', <STDIN> ) ) };
local $/ = "\n";

my $ssh_key;

my ( $id, $ticketid, $addr ) = @project{qw( id ticketid addr )};
if( $ticketid )
{
    my $x = `c3mc-base-db-get -t openc3_ci_ticket ticket --filter "id='$ticketid' and type='SSHKey'"`;
    chomp $x;
    $ssh_key = $x if $x;
}

my $ctrl = $ssh_key ? "c3mc-base-git -i " . Temp->new( chmod => 0600 )->dump( $ssh_key ) : 'git';

my @list; eval{ alarm 10; @list = `$ctrl ls-remote --tags $addr`; alarm 0; };
chomp @list;
map{ print "$id;$1\n" if $_ =~ /\w+\s+refs\/tags\/(.+)/ }grep{ $_ !~ /\^\{\}$/ }@list;
