#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;
use JSON;
use YAML::XS;

my ( $id, $ns, $name ) = @ARGV;
die "argv err" unless $id   && $id   =~ /^\d+$/;
die "argv err" unless $ns   && $ns   =~ /^[a-zA-Z0-9]+$/;
die "argv err" unless $name && $name =~ /^[a-zA-Z][a-zA-Z0-9\-]*$/;

my    $kubectl = `c3mc-k8s-kubectl-get -i $id`;
chomp $kubectl;

my $x = `$kubectl get deployment '$name' -n '$ns' -o json`;
my $data = eval{ JSON::decode_json( $x ); };
die "load data from json fail: $@" if $@;

my    $stat = `c3mc-spotx-affinity-check $id $ns $name`;
chomp $stat;

unless( $stat =~ /ok./ )
{
   print "stat: $stat => skip.\n";
   exit;
}

die "not spec"               unless $data->{spec};
die "not spec.template"      unless $data->{spec}{template};
die "not spec.template.spec" unless $data->{spec}{template}{spec};


my @affinity = @{ $data->{spec}{template}{spec}{affinity}{nodeAffinity}{preferredDuringSchedulingIgnoredDuringExecution} };
my @rollback;
for my $a ( @affinity )
{
    my $curr = YAML::XS::Dump $a;
    unless( index( $curr, 'c3.spotx.node.role/small' ) > 0 && index( $curr, 'c3.spotx.node.role/large' ) > 0 )
    {
        push @rollback, $a;
    }
}

$data->{spec}{template}{spec}{affinity}{nodeAffinity}{preferredDuringSchedulingIgnoredDuringExecution} = \@rollback;

my $json = eval{ JSON::encode_json( $data )};
die "to json fail: $@" if $@;
print "$json\n";
