#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

use YAML::XS;

=head1 SYNOPSIS

 $0

=cut

local $/ = undef;
my @data = YAML::XS::Load( my $x = <STDIN> );
local $/ = "\n";

my @out;
sub adduser
{
    my $data = shift @_;
    return unless $data && ref $data eq 'HASH' && defined $data->{'labels.fromtreeid'} && $data->{'labels.fromtreeid'} =~ /^\d+$/;

    my $filter = "projectid=$data->{'labels.fromtreeid'} and subgroup=\"\"";
    if( $data->{'labels.subgroup'} && $data->{'labels.subgroup'} =~ /^[a-zA-Z0-9]+$/ )
    {
        $filter = "projectid=$data->{'labels.fromtreeid'} and ( subgroup=\"\" or subgroup=\"$data->{'labels.subgroup'}\" )";
    }

    my @user = `c3mc-base-db-get user --table openc3_monitor_config_user --filter '$filter' | c3mc-app-usrext`;
    chomp @user;

    return unless @user;

    $data->{to} = \@user;
    push @out, $data;
}

map{ adduser($_ ) }@data;

print YAML::XS::Dump @out;
