#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use LWP::UserAgent;
use Util;
use JSON;

$| ++;

=head1 SYNOPSIS

    user => '',
    title => '',
    content => ''

=cut

return sub
{
    my %param = @_;

    map{ die "$_ undef" unless $param{$_} }qw( user title content );

    if( system "c3_connector_pp_addauditlog '$param{user}' '$param{title}' '$param{content}'" )
    {
        warn "auditlog err: $!";
        return undef;
    }

    return 1;
}
