#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;
use Logs;
use Fcntl 'O_RDONLY';
use Tie::File;

$| ++;

=head1 SYNOPSIS

    logs => 日志对象

=cut

return sub
{
    my ( %param, @list )= @_;
    my ( $logs ) = @param{qw(logs)};

    $logs = Logs->new( 'code.dockerimage' ) unless $logs;

    @list = ( 'centos:5','centos:6','centos:7' );
    my $file = "/etc/dockerimage.list";
    if( -f $file )
    {
        $logs->die( "tie fail: $!" ) unless tie my @x, 'Tie::File', $file, mode => O_RDONLY, recsep => "\n";
        my %x = map{ $_ => 1 }@x;
        @list = sort keys %x;
        untie @x;
    }

    return ( '', @list );

}
