#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/CI/lib -I/data/Software/mydan/CI/private/lib
use strict;
use warnings;

use FindBin qw( $RealBin );
use YAML::XS;
use Util;
use LWP::UserAgent;
use JSON;


$| ++;

=head1 SYNOPSIS

    id => 1,

=cut

return sub
{
    my %param = @_;
    my $id = $param{id};
    die "id not a number" unless $id =~ /^\d+$/;

    my %env = Util::envinfo( qw( appname appkey ) );
    my $ua = LWP::UserAgent->new;
    $ua->default_header( %env );
 
    my $res = $ua->get( "http://api.agent.open-c3.org/inherit/$id" );

    if( $res->is_success )
    {
        my $data = eval{JSON::from_json $res->content};
        return $data->{data}{fullname} if $data && $data->{stat};
    }
    return 'unkown';
}
