#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;
use FindBin qw( $RealBin );
use YAML::XS;

=head1 SYNOPSIS

 $0

=cut

print "reload job\n";

my $Config = eval{ YAML::XS::LoadFile "$RealBin/../config/Config";};
die "load Config fail: $!" unless $Config;

my $envname = `cat $RealBin/../conf/envname`;
chomp $envname;
die "envname undef" unless $envname;

die "envname $envname undef in Config" unless $Config = $Config->{$envname};

die "port undef" unless my $port = $Config->{port};

my $token = $ENV{OPEN_C3_RANDOM} || 'token';

for my $type ( qw( api api.slave ) )
{
    for my $port ( $port->{$type}{from} .. $port->{$type}{to} )
    {
        my $oldpid = `/usr/sbin/lsof -i:$port|tail -n 1|awk '{print \$2}'`;
        chomp $oldpid;

        system "curl -H 'token:$ENV{OPEN_C3_RANDOM}' localhost:$port/reload 2>/dev/null";

        my $newpid;
        for my $index ( 1 .. 30 )
        {
            print "check api ...\n";
            $newpid = `/usr/sbin/lsof -i:$port|tail -n 1|awk '{print \$2}'`;
            if( $newpid )
            {
                chomp $newpid;
                last if ! $oldpid || ( $oldpid ne $newpid );
            }
            else
            {
                die "reload port $port fail.\n" if $index == 30;
                sleep 1;
            }
        }

        print "reload $type port: $port old pid: $oldpid new pid: $newpid\n";
    }
}

for my $server ( qw( call bury crontab keepalive notify approval clean ) )
{
    my $oldpid = `ps -ef|grep [j]ob_server_$server|head -n 1|awk '{print \$2}'`;
    chomp $oldpid;

    system "killall job_server_$server";

    my $newpid;
    for my $index ( 1 .. 30 )
    {
        print "check server job_server_$server ...\n";
        $newpid = `ps -ef|grep [j]ob_server_$server|head -n 1|awk '{print \$2}'`;

        if( $newpid )
        {
            chomp $newpid;
            last if ! $oldpid || ( $oldpid ne $newpid );
        }
        else
        {
            die "restart server job_server_$server  fail.\n" if $index == 30;
            sleep 1;
        }
      
    }

    print "restart server job_server_$server old pid: $oldpid new pid: $newpid\n";
}
