#!/data/Software/mydan/perl/bin/perl
use strict;
use warnings;
use FindBin qw( $RealBin );
use Tie::File;

=head1 SYNOPSIS

 $0

=cut

my $service = @ARGV ? $ARGV[0] : '';
my $perl = $^X;

my $base = $RealBin;
$base =~ s#/[^/]+$##;

system "$base/tools/stop $service && $base/tools/start $service";

sleep 1;

$service ? system( "ps -ef|grep job|grep $service" ) : system( "ps -ef|grep job" );
