#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json
import subprocess

from googleapiclient import discovery
from google.oauth2 import service_account


def tag_add(data, cred_json_path):
    field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field compute google-vm id")
    zone_field_name = subprocess.getoutput(
        "c3mc-cloud-get-real-field compute google-vm zone")

    instance = json.loads(subprocess.getoutput(
        "c3mc-cloud-control --uuid {} --ctrl get none".format(data[field_name])))

    credentials = service_account.Credentials.from_service_account_file(
        cred_json_path)

    service = discovery.build('compute', 'v1', credentials=credentials)

    labels = {}
    for label in instance["tags_list"]:
        labels[label["Key"]] = label["Value"]

    labels[data["_control_"]["tag-add"]["key"]
           ] = data["_control_"]["tag-add"]["value"]

    request_body = {
        "labels": labels,
        "labelFingerprint": instance["labelFingerprint"]
    }

    request = service.instances().setLabels(project=credentials.project_id,
                                            zone=data[zone_field_name], instance=instance["name"], body=request_body)

    request.execute()


def main(data, cred_json_path):
    tag_add(data, cred_json_path)


if __name__ == '__main__':
    l = []
    for line in sys.stdin:
        l.append(line)
    if len(l) == 0 or len(l) > 1:
        raise Exception("数据格式不对, 需要一行json字符串")

    main(json.loads(l[0]), sys.argv[2])
