#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import sys
import json


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_utils import check_if_params_safe_in_recycle, safe_run_command, extract_ips


def main(params):
    email = params["email"]
    auth_type = params["auth_type"]
    ip_list = extract_ips(params["ip_list"])

    check_if_params_safe_in_recycle(ip_list, params["bpm_uuid"], "server-auth")

    print(f"开始处理用户: {email}, auth_type: {auth_type}, ip_list: {' '.join(ip_list)} 的权限申请")

    output = safe_run_command([
        "c3mc-base-bastion-add-server-auth",
        email,
        auth_type,
        params["ip_list"],
        "1"
    ])
    print(output)


if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
