#!/data/Software/mydan/perl/bin/perl -I/data/Software/mydan/JOB/lib -I/data/Software/mydan/JOB/private/lib
use strict;
use warnings;
use FindBin qw( $RealBin );

$| ++;

=head1 SYNOPSIS

=cut

return sub
{
    die "get cookie key fail: $!" if system "c3mc-base-configx cookiekey > $RealBin/../conf/cookiekey";
}
