#!/usr/bin/env /data/Software/mydan/python3/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import subprocess


sys.path.append("/data/Software/mydan/Connector/lib/pp")
from c3mc_cloud_google_compute import GoogleCompute


def list_all_instances_of_region(cred_json_path, region):
    return GoogleCompute(cred_json_path).list_region_instances(region)


def main(params):
    """查询指定区域下的vm列表
    """
    
    account = params["account"]
    region = params["region"]

    key_info = json.loads(
        subprocess.getoutput(f"c3mc-get-account-info google {account}")
    )

    try:
        vm_list = list_all_instances_of_region(key_info["cred_path"], region)
        for vm in vm_list:
            # 方便在后续处理中直接获取实例名称和所在可用区
            vm["name"] = f'{vm["name"]}/{vm["zone"].split("/")[-1]}'
            vm["machineType"] = vm["machineType"].split("/")[-1]
            print(json.dumps(vm))
    except Exception as e:
        raise RuntimeError("获取实例列表失败") from e
    

if __name__ == '__main__':
    l = list(sys.stdin)
    if not l or len(l) > 1:
        raise type('WrongInputData', (Exception,), {})('数据格式不对, 需要一行json字符串"')

    main(json.loads(l[0]))
